import PerfectPower.WeilOrbitSymmetry
import Mathlib.Data.Fintype.Quotient

noncomputable section
namespace PerfectPower.MonomialOrbitSpace
open scoped BigOperators
variable {K Ω Γ : Type*} [Field K]

/-- Unoriented connectivity generated by the supplied permutations. -/
def orbitSetoid (moves : Γ → Ω ≃ Ω) : Setoid Ω :=
  Relation.EqvGen.setoid (fun a b => ∃ g, moves g a=b)

abbrev Orbits (moves : Γ → Ω ≃ Ω) := Quotient (orbitSetoid moves)

instance orbitFintype [Fintype Ω] (moves : Γ → Ω ≃ Ω) : Fintype (Orbits moves) :=
  Fintype.ofFinite _

/-- Fixed coefficient functions after the phase has been gauged away. -/
def fixedSpace (moves : Γ → Ω ≃ Ω) : Submodule K (Ω → K) where
  carrier := {c | ∀ g w, c (moves g w)=c w}
  zero_mem' := by change ∀ g w, (0 : Ω → K) (moves g w)=0; intros; rfl
  add_mem' := by
    intro c d hc hd g w
    change c (moves g w)+d (moves g w)=c w+d w
    rw [hc g w,hd g w]
  smul_mem' := by
    intro a c hc g w
    change a • c (moves g w)=a • c w
    rw [hc g w]

theorem fixed_respects (moves : Γ → Ω ≃ Ω) (c : Ω → K)
    (hc : c ∈ fixedSpace moves) {a b : Ω} (h : (orbitSetoid moves).r a b) :
    c a=c b := by
  induction h with
  | rel a b h => obtain ⟨g,rfl⟩ := h; exact (hc g a).symm
  | refl => rfl
  | symm a b _ ih => exact ih.symm
  | trans a b c _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Every fixed function descends uniquely to the actual orbit quotient. -/
def quotientEquiv (moves : Γ → Ω ≃ Ω) :
    fixedSpace (K:=K) moves ≃ₗ[K] (Orbits moves → K) where
  toFun c := Quotient.lift c.val (fun _ _ h => fixed_respects moves c.val c.property h)
  invFun f := ⟨fun w => f (Quotient.mk _ w),by
    intro g w
    apply congrArg f
    exact (Quotient.sound (Relation.EqvGen.rel w (moves g w) ⟨g,rfl⟩)).symm⟩
  left_inv c := by apply Subtype.ext; rfl
  right_inv f := by funext q; induction q using Quotient.inductionOn; rfl
  map_add' c d := by funext q; induction q using Quotient.inductionOn; rfl
  map_smul' a c := by funext q; induction q using Quotient.inductionOn; rfl

/-- Counting orbits is the only remaining input to the fixed-space dimension. -/
theorem fixed_finrank [Fintype Ω] (moves : Γ → Ω ≃ Ω) :
    Module.finrank K (fixedSpace (K:=K) moves)=Fintype.card (Orbits moves) := by
  rw [(quotientEquiv (K:=K) moves).finrank_eq]
  exact Module.finrank_fintype_fun_eq_card K

/-- A monomial system with a nonvanishing global gauge. -/
def phaseSpace (moves : Γ → Ω ≃ Ω) (phase : Γ → Ω → K) : Submodule K (Ω → K) where
  carrier := {c | ∀ g w, c (moves g w)=phase g w*c w}
  zero_mem' := by change ∀ g w, (0 : Ω → K) (moves g w)=phase g w*0; intros; simp
  add_mem' := by
    intro c d hc hd g w
    change c (moves g w)+d (moves g w)=phase g w*(c w+d w)
    rw [hc g w,hd g w,mul_add]
  smul_mem' := by
    intro a c hc g w
    change a*c (moves g w)=phase g w*(a*c w)
    rw [hc g w]; ring

/-- Multiplying by a consistent gauge identifies plain and monomial fixed spaces. -/
def gaugeEquiv (moves : Γ → Ω ≃ Ω) (phase : Γ → Ω → K) (gauge : Ω → K)
    (hn : ∀ w, gauge w≠0) (hg : ∀ g w, gauge (moves g w)=phase g w*gauge w) :
    fixedSpace (K:=K) moves ≃ₗ[K] phaseSpace moves phase where
  toFun c := ⟨fun w => gauge w*c.val w,by
    intro g w
    simp only [hg,c.property g w,mul_assoc]⟩
  invFun c := ⟨fun w => c.val w/gauge w,by
    intro g w
    change c.val (moves g w)/gauge (moves g w)=c.val w/gauge w
    rw [c.property g w,hg]
    have hp : phase g w≠0 := by
      intro hz
      have he := hg g w
      rw [hz,zero_mul] at he
      exact hn (moves g w) he
    field_simp [hp,hn w]
    ring⟩
  left_inv c := by apply Subtype.ext; funext w; simp [hn w]
  right_inv c := by apply Subtype.ext; funext w; dsimp; field_simp [hn w]
  map_add' c d := by apply Subtype.ext; funext w; simp [mul_add]
  map_smul' a c := by apply Subtype.ext; funext w; simp [smul_eq_mul]; ring

theorem phase_finrank [Fintype Ω] (moves : Γ → Ω ≃ Ω) (phase : Γ → Ω → K)
    (gauge : Ω → K) (hn : ∀ w, gauge w≠0)
    (hg : ∀ g w, gauge (moves g w)=phase g w*gauge w) :
    Module.finrank K (phaseSpace moves phase)=Fintype.card (Orbits moves) := by
  rw [← (gaugeEquiv moves phase gauge hn hg).finrank_eq]
  exact fixed_finrank moves

/-- Orbit-preserving reflection transports every monomial fixed coefficient. -/
theorem reflection_coeff (moves : Γ → Ω ≃ Ω) (phase : Γ → Ω → K) (gauge : Ω → K)
    (hn : ∀ w, gauge w≠0) (hg : ∀ g w, gauge (moves g w)=phase g w*gauge w)
    (r : Ω → Ω) (twist : Ω → K)
    (hr : ∀ w, (orbitSetoid moves).r w (r w))
    (ht : ∀ w, gauge (r w)=twist w*gauge w)
    (c : phaseSpace moves phase) (w : Ω) : c.val (r w)=twist w*c.val w := by
  let e := gaugeEquiv moves phase gauge hn hg
  let a := e.symm c
  have he : ∀ v, gauge v*a.val v=c.val v := by
    intro v
    exact congrFun (congrArg Subtype.val (e.apply_symm_apply c)) v
  have ha : a.val w=a.val (r w) := fixed_respects moves a.val a.property (hr w)
  rw [← he (r w),← he w,ht w,← ha,mul_assoc]

end PerfectPower.MonomialOrbitSpace
