import PerfectPower
/-! Axiom audit: every public theorem must depend only on `propext`, `Classical.choice` and
`Quot.sound` (no `sorryAx`, no custom axioms).  Run with `lake env lean audit/Axioms.lean`. -/
open PerfectPower
-- Basic / Density
#print axioms H_eq_of_hasDensity
#print axioms hasDensity_zero_of_finite
#print axioms A_sub_eq_const
#print axioms H_surgery
#print axioms hasDensity_of_periodic
-- Rigid / Estimates / Dichotomy
#print axioms exists_denominator
#print axioms frac_periodic
#print axioms integral_closure_step
#print axioms exists_truncated_root
#print axioms pow_diff_bound
#print axioms eventually_no_hit
#print axioms rigid_dichotomy
-- ZeroOne
#print axioms hasDensity_one_of_pow
#print axioms rigid_zero_one
#print axioms rigid_H_mem
#print axioms twisted_hits_subset
#print axioms twisted_finite
#print axioms twisted_density_zero
-- Monomial
#print axioms rat_pow_eq_nat
#print axioms monomial_isHit_iff
#print axioms monomial_hitSet
#print axioms monomial_count
-- Examples
#print axioms consecutive_four_not_square
#print axioms consecutive_four_hitSet
#print axioms ljunggren_quartic
#print axioms ljunggren_hitSet
-- Pell example 2n^2 + 1
#print axioms hasDensity_zero_of_count_le
#print axioms pell_descent
#print axioms pell_hit_iff
#print axioms pell_hitSet_infinite
#print axioms pell_count_le
#print axioms pell_hasDensity_zero
-- Theorem R (integer form)
#print axioms pow_diff_bound'
#print axioms runge_pointwise
#print axioms runge_uniform
#print axioms runge_finite
#print axioms power_type_finite
-- Certificates and machine-generated hit sets
#print axioms not_isHit_between
#print axioms not_isHit_neg
#print axioms PerfectPower.Generated.ljunggren_quartic_hits
#print axioms PerfectPower.Generated.n4_plus_1_square_hits
#print axioms PerfectPower.Generated.consecutive4_square_hits
#print axioms PerfectPower.Generated.consecutive4_fourth_power_hits
#print axioms PerfectPower.Generated.consecutive6_square_hits
#print axioms PerfectPower.Generated.consecutive6_cube_hits
#print axioms PerfectPower.Generated.consecutive6_sixth_power_hits
#print axioms PerfectPower.Generated.consecutive8_square_hits
#print axioms PerfectPower.Generated.consecutive8_fourth_power_hits
#print axioms PerfectPower.Generated.consecutive8_eighth_power_hits
#print axioms PerfectPower.Generated.consecutive10_fifth_power_hits
#print axioms PerfectPower.Generated.consecutive12_square_hits
#print axioms PerfectPower.Generated.consecutive12_cube_hits
#print axioms PerfectPower.Generated.consecutive12_sixth_power_hits
#print axioms PerfectPower.Generated.n6_plus_n_plus_1_cube_hits
#print axioms PerfectPower.Generated.n4_plus_7_square_hits
#print axioms PerfectPower.Generated.sextic_1_2_3_4_5_6_1_cube_hits
-- Exponential sequences
#print axioms isHit_exp_shift
#print axioms exp_hasDensity
#print axioms two_pow_hasDensity_half
#print axioms PerfectPower.Generated.consecutive10_square_hits
#print axioms PerfectPower.Generated.consecutive12_fourth_power_hits
#print axioms no_hit_of_sandwich
-- Function field (unconditional) and abc-conditional layer (abc is a hypothesis, not an axiom)
#print axioms davenport
#print axioms davenport_sharp
#print axioms hall_of_abc
#print axioms pillai_bound_of_abc
#print axioms pillai_finite_of_abc
-- Mordell census points lie on their curves (completeness NOT checked; see TRUST_BOUNDARY)
#print axioms PerfectPower.Generated.Mordell.census_points_valid
-- Binomial coefficients via elliptic curves (point-list completeness is an explicit hypothesis)
#print axioms two_mul_choose_two
#print axioms six_mul_choose_three
#print axioms binomial_curve_points_valid
#print axioms choose_two_cube_iff
#print axioms choose_two_cube_hits
#print axioms choose_three_square_iff
#print axioms choose_three_square_hits
-- Valuation core of Theorem B
#print axioms exists_pow_iff_factorization
#print axioms isHit_iff_natAbs
#print axioms isHit_iff_rat
#print axioms mul_pow_isPow_iff_congr
#print axioms mul_pow_isPow_iff_param
-- PellGeneral (Theorem Q interfaces)
#print axioms quadratic_isHit_iff_norm
#print axioms unitAct_norm
#print axioms unitOrbit_norm
#print axioms unitOrbit_periodic
#print axioms goodClass_hits
#print axioms index_le_of_geometric
#print axioms le_of_index_le_geometric
#print axioms geometric_count_le
#print axioms le_geometric_count
-- RadicalCount (Theorem B count)
#print axioms count_periodic_eq
#print axioms count_periodic_le
#print axioms le_count_periodic
#print axioms card_Icc_filter_eq_count
#print axioms radical_hits_card
#print axioms radical_count_bound
-- Pell orbit representatives (finite box) and function-field Pillai
#print axioms pell_descent_box
#print axioms pell_box_finite
#print axioms pell_orbits_exhaust
#print axioms pillai_polynomial
#print axioms pillai_polynomial_balanced
#print axioms pillai_polynomial_sq_sharp
-- ProfileG (Theorem G, combinatorial half)
#print axioms S_le_one_iff
#print axioms profile_table_ok
#print axioms profiles12_length
-- Reflect (verified certificate checkers) and the reflective census
#print axioms PerfectPower.Reflect.check_sound
#print axioms PerfectPower.Reflect.mordellOK_sound
#print axioms PerfectPower.Reflect.ev_shift
#print axioms PerfectPower.Reflect.intervalPos_sound
#print axioms PerfectPower.Generated.cert_consecutive10_square_hits_ok
#print axioms PerfectPower.Generated.cert_consecutive12_fourth_power_hits_ok
#print axioms PerfectPower.Generated.Mordell.census_ok
#print axioms PerfectPower.Generated.Mordell.census_size
#print axioms unitOrbit_growth
#print axioms pell_count_log
#print axioms PerfectPower.Reflect.rungeCheck_sound
-- PellExact (exact Pell count) and the general Theorem G statement
#print axioms PerfectPower.PellExact.exists_root
#print axioms PerfectPower.PellExact.root_unique
#print axioms PerfectPower.PellExact.roots_finite
#print axioms PerfectPower.PellExact.orbit_fst_bracket
#print axioms PerfectPower.PellExact.count_near_geometric
#print axioms PerfectPower.PellExact.class_count
#print axioms PerfectPower.PellExact.orbit_count
#print axioms PerfectPower.PellExact.pell_exact_count
#print axioms chi_eq
#print axioms chi_neg_iff
-- RadicalAsymp (radical real-power asymptotic) and the Atlas interface
#print axioms radW_spec
#print axioms radW_approx
#print axioms radical_asymptotic
#print axioms radical_asymptotic_int
#print axioms isHit_mul_pow_iff
#print axioms atlas_power
#print axioms atlas_radical
#print axioms atlas_pell
#print axioms atlas_finite
-- Genus1 (checked Weierstrass reductions; Sage points as named hypotheses)
#print axioms PerfectPower.Genus1.cubic_sound
#print axioms PerfectPower.Genus1.quad_sound
#print axioms PerfectPower.Generated.Genus1.g1_sq_m1_m3_2_1_hits
#print axioms PerfectPower.Generated.Genus1.g1_cube_m6_m7_6_hits
-- MordellDescent (unconditional: no integral points on y^2 = x^3 + k)
#print axioms PerfectPower.MordellDescent.good_of_dvd
#print axioms PerfectPower.MordellDescent.exists_bad_prime
#print axioms PerfectPower.MordellDescent.goodDivisors_of_cert
#print axioms PerfectPower.MordellDescent.no_points
#print axioms PerfectPower.MordellDescent.not_isHit
#print axioms PerfectPower.MordellDescent.mordell_7
#print axioms PerfectPower.Generated.MordellDescent.no_points_m9985
#print axioms PerfectPower.Generated.MordellDescent.no_points_m9957
#print axioms PerfectPower.Generated.MordellDescent.no_points_m9201
-- MordellFLT3 (unconditional nonempty list, via Mathlib's FLT for exponent 3)
#print axioms PerfectPower.MordellFLT3.points
#print axioms PerfectPower.MordellFLT3.isHit_iff
#print axioms PerfectPower.MordellFLT3.hitSet_432
-- Positive rank, unconditional: y^2 = x^3 - 2 and y^2 = x^3 - 4
#print axioms PerfectPower.MordellMinus2.norm_mod_lt
#print axioms PerfectPower.MordellMinus2.points
#print axioms PerfectPower.MordellMinus2.hitSet
#print axioms PerfectPower.MordellMinus4.unit_is_cube
#print axioms PerfectPower.MordellMinus4.points
#print axioms PerfectPower.MordellMinus4.hitSet
-- Transport with integrality and exact counts
#print axioms PerfectPower.Transport.affine_count
#print axioms PerfectPower.Transport.affine_count_le
#print axioms PerfectPower.Transport.affine_cube_sub_two
#print axioms PerfectPower.Transport.complete_fermat
#print axioms PerfectPower.Transport.complete_of_no_points
#print axioms PerfectPower.Transport.cubic_sound_image
#print axioms PerfectPower.Transport.n3m2_hits
-- Class number two, unconditional: the ideal-free template and its instances D = 13, 5, 6
#print axioms PerfectPower.ClassTwo.exists_short
#print axioms PerfectPower.ClassTwo.box
#print axioms PerfectPower.ClassTwo.short_relation
#print axioms PerfectPower.ClassTwo.halvesOK_of_mod8
#print axioms PerfectPower.ClassTwo.cube_of_table
#print axioms PerfectPower.MordellMinus13.table13
#print axioms PerfectPower.MordellMinus13.points
#print axioms PerfectPower.MordellMinus13.hitSet
#print axioms PerfectPower.MordellMinus5.table5
#print axioms PerfectPower.MordellMinus5.no_points
#print axioms PerfectPower.MordellMinus5.not_isHit
#print axioms PerfectPower.MordellMinus6.table6
#print axioms PerfectPower.MordellMinus6.no_points
#print axioms PerfectPower.MordellMinus6.not_isHit
#print axioms PerfectPower.Transport.complete_cube_sub_thirteen
-- Rational Yun decomposition and general radical/Pell pointwise reductions (continuation, 31 theorems + 9 definitions)
#print axioms PerfectPower.RationalYun.radical_integer_reduction
#print axioms PerfectPower.RationalYun.Decomposition.integer_radical_reduction
#print axioms PerfectPower.RationalYun.Decomposition.integer_pell_reduction
#print axioms PerfectPower.RationalYun.Decomposition.quotientPart
#print axioms PerfectPower.RationalYun.Decomposition.remainderPart
#print axioms PerfectPower.RationalYun.Decomposition.powerSplit
#print axioms PerfectPower.RationalYun.Decomposition.weighted_degree
#print axioms PerfectPower.RationalYun.Decomposition.single_remainder
#print axioms PerfectPower.RationalYun.Decomposition.uniform_remainder
#print axioms PerfectPower.RationalYun.Decomposition.lead_eq_leadingCoeff
#print axioms PerfectPower.RationalYun.Decomposition.radical_shape
#print axioms PerfectPower.RationalYun.Decomposition.pellPart
#print axioms PerfectPower.RationalYun.Decomposition.pell_shape
#print axioms PerfectPower.RationalYun.unique_summand_of_sum_one
#print axioms PerfectPower.RationalYun.Decomposition.badDegree
#print axioms PerfectPower.RationalYun.Decomposition.radical_shape_of_badDegree_one
#print axioms PerfectPower.RationalYun.RatPower
#print axioms PerfectPower.RationalYun.ratPower_mul_pow_iff
#print axioms PerfectPower.RationalYun.integer_factor_reduction
#print axioms PerfectPower.RationalYun.Decomposition.hit_reduction
#print axioms PerfectPower.RationalYun.rat_even_power_reduction
#print axioms PerfectPower.RationalYun.pell_factor_reduction
#print axioms PerfectPower.RationalYun.opposite_squares_iff_zero
#print axioms PerfectPower.RationalYun.bag
#print axioms PerfectPower.RationalYun.layerSet
#print axioms PerfectPower.RationalYun.layer
#print axioms PerfectPower.RationalYun.normalized_irreducibles_coprime
#print axioms PerfectPower.RationalYun.layer_mem
#print axioms PerfectPower.RationalYun.layer_monic
#print axioms PerfectPower.RationalYun.squarefree_product
#print axioms PerfectPower.RationalYun.layer_squarefree
#print axioms PerfectPower.RationalYun.layers_coprime
#print axioms PerfectPower.RationalYun.grouped_product
#print axioms PerfectPower.RationalYun.ofNonzero
#print axioms PerfectPower.RationalYun.exists_decomposition
#print axioms PerfectPower.RationalYun.exists_integer_decomposition
#print axioms PerfectPower.RationalYun.Decomposition.ne_zero
#print axioms PerfectPower.RationalYun.decomposition_iff_nonzero
#print axioms PerfectPower.RationalYun.not_isCoprime_integer_X_X_add_two
#print axioms PerfectPower.RationalYun.isCoprime_rational_X_X_add_two
-- Theorem B as a count for a general F (exceptional zeros, signs, shifts, solvability)
#print axioms PerfectPower.RationalYun.card_zeros_le
#print axioms PerfectPower.RationalYun.count_or
#print axioms PerfectPower.RationalYun.shift_count
#print axioms PerfectPower.RationalYun.z0_dichotomy
#print axioms PerfectPower.RationalYun.nat_radical_count
#print axioms PerfectPower.RationalYun.int_coeff_count
#print axioms PerfectPower.RationalYun.int_count
#print axioms PerfectPower.RationalYun.Decomposition.radical_count
-- Theorem C as a count for a general F (squarefree quadratic, +-gamma branches, Pell units)
#print axioms PerfectPower.RationalYun.squarefree_prod_of_coprime
#print axioms PerfectPower.RationalYun.pellPart_squarefree
#print axioms PerfectPower.RationalYun.disc_ne_zero
#print axioms PerfectPower.RationalYun.card_zeros_le_rat
#print axioms PerfectPower.RationalYun.clear_denoms
#print axioms PerfectPower.RationalYun.branch_count
#print axioms PerfectPower.RationalYun.Decomposition.pell_count
-- Positivity of kappa: infinitude, and a finite check for the radical type
#print axioms PerfectPower.RationalYun.infinite_iff_unbounded
#print axioms PerfectPower.RationalYun.kappa_pos_iff_rpow
#print axioms PerfectPower.RationalYun.kappa_pos_iff_log
#print axioms PerfectPower.RationalYun.Decomposition.radical_count_pos
#print axioms PerfectPower.RationalYun.Decomposition.pell_count_pos
#print axioms PerfectPower.RationalYun.z0_dvd
#print axioms PerfectPower.RationalYun.nat_infinite_of_hit
#print axioms PerfectPower.RationalYun.nat_radical_infinite_iff
#print axioms PerfectPower.RationalYun.infinite_shift
#print axioms PerfectPower.RationalYun.zeros_finite
#print axioms PerfectPower.RationalYun.int_radical_infinite_iff
#print axioms PerfectPower.RationalYun.Decomposition.radical_kappa_decide
-- Positivity of the Pell constant: one point, a bounded search, and the F-level decision
#print axioms PerfectPower.RationalYun.hit_le_of_neg
#print axioms PerfectPower.RationalYun.hit_le_of_square
#print axioms PerfectPower.RationalYun.short_period
#print axioms PerfectPower.RationalYun.orbit_mono
#print axioms PerfectPower.RationalYun.orbit_growth
#print axioms PerfectPower.RationalYun.root_small
#print axioms PerfectPower.RationalYun.branch_point_infinite
#print axioms PerfectPower.RationalYun.branch_bounded_witness
#print axioms PerfectPower.RationalYun.branch_infinite_iff
#print axioms PerfectPower.RationalYun.branch_infinite_iff_bounded
#print axioms PerfectPower.RationalYun.Decomposition.pell_kappa_decide
-- Explicit error constant, radical type
#print axioms PerfectPower.RationalYun.rpow_inv_le
#print axioms PerfectPower.RationalYun.nat_radical_count_explicit
#print axioms PerfectPower.RationalYun.int_coeff_count_explicit
#print axioms PerfectPower.RationalYun.int_count_explicit
#print axioms PerfectPower.RationalYun.Decomposition.radical_count_explicit
-- Explicit error constant, Pell type
#print axioms PerfectPower.PellExact.count_near_geometric_of_lower
#print axioms PerfectPower.PellExact.orbit_lower
#print axioms PerfectPower.PellExact.class_count_explicit
#print axioms PerfectPower.PellExact.orbit_count_explicit
#print axioms PerfectPower.PellExact.pell_count_core
#print axioms PerfectPower.PellExact.pell_branch_explicit
#print axioms PerfectPower.RationalYun.branch_count_explicit
#print axioms PerfectPower.RationalYun.Decomposition.pell_count_explicit
-- Exact constraint reductions
#print axioms PerfectPower.Reduction.Exact.iff
#print axioms PerfectPower.Reduction.Exact.comp
#print axioms PerfectPower.Reduction.Exact.pull_complete
#print axioms PerfectPower.Reduction.Exact.exists_iff
#print axioms PerfectPower.Reduction.Exact.count_eq
#print axioms PerfectPower.Reduction.affine
#print axioms PerfectPower.Reduction.quadratic
#print axioms PerfectPower.Reduction.triangular
#print axioms PerfectPower.Reduction.triangular_count
#print axioms PerfectPower.Reduction.triangular_count_int
#print axioms PerfectPower.Reduction.triangular_count_nonneg
#print axioms PerfectPower.Reduction.tri_cube_complete
-- Filtered Pell orbits and plan certificates
#print axioms PerfectPower.FilteredPell.orbit_period
#print axioms PerfectPower.FilteredPell.point_infinite
#print axioms PerfectPower.FilteredPell.infinite_iff_state
#print axioms PerfectPower.FilteredPell.infinite_iff_root_state
#print axioms PerfectPower.FilteredPell.finite_bound
#print axioms PerfectPower.FilteredPell.quadHits_iff
#print axioms PerfectPower.FilteredPell.quadRoot_infinite_iff
#print axioms PerfectPower.FilteredPell.quadRoot_bound
#print axioms PerfectPower.FilteredPell.FinCert.sound
#print axioms PerfectPower.FilteredPell.quadGoodB_iff
#print axioms PerfectPower.FilteredPell.quadRoot_bound_of_cert
#print axioms PerfectPower.FilteredPell.quadRoot_infinite_of_witness
#print axioms PerfectPower.PlanCerts.power_transport
#print axioms PerfectPower.PlanCerts.root_transport
#print axioms PerfectPower.PlanCerts.quadRoot_subset_of_cert
#print axioms PerfectPower.Generated.Plans.plan_cube_transport
#print axioms PerfectPower.Generated.Plans.plan_root_cube
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_1
#print axioms PerfectPower.Generated.Plans.plan_filtered_finite_1
-- The filtered Pell count
#print axioms PerfectPower.FilteredPell.orbit_count_pred
#print axioms PerfectPower.FilteredPell.count_of_orbit_estimates
#print axioms PerfectPower.FilteredPell.card_filter_diff_le
#print axioms PerfectPower.FilteredPell.filtered_count
#print axioms PerfectPower.FilteredPell.count_of_cert
#print axioms PerfectPower.FilteredPell.countQuad_near
#print axioms PerfectPower.FilteredPell.quadRoot_count_of_cert
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_1_count
#print axioms PerfectPower.Generated.Plans.plan_far_first_hit
#print axioms PerfectPower.Generated.Plans.plan_far_first_hit_member
#print axioms PerfectPower.Generated.Plans.plan_late_transport
-- Compact certificates, minimality, and Mordell's family
#print axioms PerfectPower.FilteredPell.quadRoot_count_auto
#print axioms PerfectPower.FilteredPell.orbit_fst_mono
#print axioms PerfectPower.FilteredPell.roots_complete_of_check
#print axioms PerfectPower.FilteredPell.quadGoodExactB_iff
#print axioms PerfectPower.FilteredPell.quadRoot_isLeast
#print axioms PerfectPower.MordellFamily.mod4_x
#print axioms PerfectPower.MordellFamily.no_points
#print axioms PerfectPower.MordellFamily.good_of_cert
#print axioms PerfectPower.MordellFamily.no_points_cert
#print axioms PerfectPower.MordellFamily.family_not_isHit
#print axioms PerfectPower.Generated.Plans.plan_late_certified
#print axioms PerfectPower.Generated.Plans.plan_late_certified_count
#print axioms PerfectPower.Generated.Plans.plan_late_certified_first
#print axioms PerfectPower.Generated.Plans.plan_mordell_family_1
#print axioms PerfectPower.Generated.Plans.plan_mordell_family_2
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_2_count
#print axioms PerfectPower.Generated.Plans.plan_cube_minus13
#print axioms PerfectPower.Generated.Plans.plan_cube_minus4
#print axioms PerfectPower.Generated.Plans.plan_no_points_minus5
#print axioms PerfectPower.Generated.Plans.plan_triangular_cube
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_1_first
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_2
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_2_first
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_3
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_3_count
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_3_first
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_4
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_4_count
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_5
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_5_count
#print axioms PerfectPower.Generated.Plans.plan_filtered_infinite_5_first
#print axioms PerfectPower.Generated.Plans.plan_filtered_finite_2
#print axioms PerfectPower.Generated.Plans.plan_filtered_finite_3
#print axioms PerfectPower.Generated.Plans.plan_filtered_finite_4
#print axioms PerfectPower.Generated.Plans.plan_filtered_finite_5
#print axioms PerfectPower.FilteredPell.orbitCount_eq
#print axioms PerfectPower.FilteredPell.iterForce_eq
-- Descent certificates: complete nonempty point lists, and the bridge to the compiler's premise
#print axioms PerfectPower.Descent.W1_modEq
#print axioms PerfectPower.Descent.W2_modEq
#print axioms PerfectPower.Descent.divOK_of_divB
#print axioms PerfectPower.Descent.table_sound
#print axioms PerfectPower.Descent.cube_of_cert
#print axioms PerfectPower.Descent.points_of_cert
#print axioms PerfectPower.Descent.pointList_sound
#print axioms PerfectPower.Descent.complete_of_cert
#print axioms PerfectPower.Descent.image_of_complete
#print axioms PerfectPower.Descent.hits_of_cert
#print axioms PerfectPower.Generated.Plans.plan_descent_74
#print axioms PerfectPower.Generated.Plans.plan_descent_193
#print axioms PerfectPower.Generated.Plans.plan_thue_minus56
#print axioms PerfectPower.Generated.Plans.plan_branch_minus20
#print axioms PerfectPower.PlanCerts.pairs_of_list
-- Observations of orbits, and one orbit behind six sequences
#print axioms PerfectPower.Observation.count_between
#print axioms PerfectPower.Observation.filtered_obs_count
#print axioms PerfectPower.Observation.value_count
#print axioms PerfectPower.Observation.observed_count
#print axioms PerfectPower.SquareTriangular.sol_iff
#print axioms PerfectPower.SquareTriangular.sol_nat
#print axioms PerfectPower.SquareTriangular.even_of_pell
#print axioms PerfectPower.SquareTriangular.sqTriRoot_iff
#print axioms PerfectPower.SquareTriangular.triIdx_iff
#print axioms PerfectPower.SquareTriangular.sqTri_iff
#print axioms PerfectPower.SquareTriangular.pellIdx_iff
#print axioms PerfectPower.SquareTriangular.pellRoot_iff
#print axioms PerfectPower.SquareTriangular.oddSqTri_iff
#print axioms PerfectPower.SquareTriangular.eps_eq
#print axioms PerfectPower.SquareTriangular.sqTriRoot_count
#print axioms PerfectPower.SquareTriangular.triIdx_count
#print axioms PerfectPower.SquareTriangular.pellIdx_count
#print axioms PerfectPower.SquareTriangular.pellRoot_count
#print axioms PerfectPower.SquareTriangular.sqTri_count
#print axioms PerfectPower.SquareTriangular.oddSqTri_count
-- Eventually increasing observations; the orbit of 1 + sqrt 2 and thirteen OEIS definitions
#print axioms PerfectPower.Observation.card_filter_shift
#print axioms PerfectPower.Observation.observed_count_eventually
#print axioms PerfectPower.SqrtTwoOrbit.norm_AB
#print axioms PerfectPower.SqrtTwoOrbit.parity
#print axioms PerfectPower.SqrtTwoOrbit.even_sol_iff
#print axioms PerfectPower.SqrtTwoOrbit.odd_sol_iff
#print axioms PerfectPower.SqrtTwoOrbit.rec_unique
#print axioms PerfectPower.SqrtTwoOrbit.A000129_eq
#print axioms PerfectPower.SqrtTwoOrbit.A001541_eq
#print axioms PerfectPower.SqrtTwoOrbit.A001542_eq
#print axioms PerfectPower.SqrtTwoOrbit.A001109_eq
#print axioms PerfectPower.SqrtTwoOrbit.A001108_eq
#print axioms PerfectPower.SqrtTwoOrbit.A001652_eq
#print axioms PerfectPower.SqrtTwoOrbit.A002315_eq
#print axioms PerfectPower.SqrtTwoOrbit.A005319_eq
#print axioms PerfectPower.SqrtTwoOrbit.A001110_enumerates
#print axioms PerfectPower.SqrtTwoOrbit.A001653_enumerates
#print axioms PerfectPower.SqrtTwoOrbit.A075870_enumerates
#print axioms PerfectPower.SqrtTwoOrbit.A055997_enumerates
#print axioms PerfectPower.SqrtTwoOrbit.A084703_enumerates
#print axioms PerfectPower.SqrtTwoOrbit.A002315_A001653
#print axioms PerfectPower.SqrtTwoOrbit.cluster
#print axioms PerfectPower.SqrtTwoOrbit.pell_count
#print axioms PerfectPower.SqrtTwoOrbit.log_eps_eq
-- QuadOrbit / FibOrbit / OEISLib (the quadratic-unit orbit engine and the OEIS support library)
#print axioms PerfectPower.QuadOrbit.seeds_roots
#print axioms PerfectPower.QuadOrbit.roots_seeds
#print axioms PerfectPower.QuadOrbit.complete
#print axioms PerfectPower.QuadOrbit.unique
#print axioms PerfectPower.QuadOrbit.orbit_rec
#print axioms PerfectPower.QuadOrbit.fst_inj
#print axioms PerfectPower.QuadOrbit.snd_inj
#print axioms PerfectPower.QuadOrbit.cross_collision
#print axioms PerfectPower.QuadOrbit.fst_between
#print axioms PerfectPower.QuadOrbit.snd_between
#print axioms PerfectPower.QuadOrbit.rec_unique
#print axioms PerfectPower.QuadOrbit.orbit_mod
#print axioms PerfectPower.QuadOrbit.residues_periodic
#print axioms PerfectPower.FibOrbit.norm
#print axioms PerfectPower.FibOrbit.shift6
#print axioms PerfectPower.FibOrbit.unit5
#print axioms PerfectPower.FibOrbit.orbit
#print axioms PerfectPower.FibOrbit.cert_pos
#print axioms PerfectPower.FibOrbit.cert_neg
#print axioms PerfectPower.FibOrbit.pos_iff
#print axioms PerfectPower.FibOrbit.neg_iff
#print axioms PerfectPower.FibOrbit.F_strictMono
#print axioms PerfectPower.FibOrbit.fib_collision
#print axioms PerfectPower.FibOrbit.fib_parity_inj
#print axioms PerfectPower.FibOrbit.even_iff
#print axioms PerfectPower.FibOrbit.eps_eq
#print axioms PerfectPower.FibOrbit.fib_count
#print axioms PerfectPower.FibOrbit.even_fib_count
#print axioms PerfectPower.OEISLib.stride_one
#print axioms PerfectPower.OEISLib.stride_two
#print axioms PerfectPower.OEISLib.stride_four
#print axioms PerfectPower.OEISLib.stride_norm1
#print axioms PerfectPower.OEISLib.s3x_rec
#print axioms PerfectPower.OEISLib.s3y_rec
#print axioms PerfectPower.OEISLib.rec_unique3
#print axioms PerfectPower.OEISLib.gf2_eq
#print axioms PerfectPower.OEISLib.gf3_eq
#print axioms PerfectPower.OEISLib.setsq_iff
#print axioms PerfectPower.OEISLib.interleave_strictMono
#print axioms PerfectPower.OEISLib.setsq_enum
#print axioms PerfectPower.OEISLib.setsq_enumerates
-- SqrtTwoBatch (Pythagorean triples, matrix orbit, coprime splitting, exceptional set, residue filter)
#print axioms PerfectPower.SqrtTwoBatch.triple_iff
#print axioms PerfectPower.SqrtTwoBatch.triples_listed
#print axioms PerfectPower.SqrtTwoBatch.pos_triples_listed
#print axioms PerfectPower.SqrtTwoBatch.A046090_eq
#print axioms PerfectPower.SqrtTwoBatch.A115598_eq
#print axioms PerfectPower.SqrtTwoBatch.A115599_eq
#print axioms PerfectPower.SqrtTwoBatch.A098602_eq
#print axioms PerfectPower.SqrtTwoBatch.vM_eq
#print axioms PerfectPower.SqrtTwoBatch.A090390_eq
#print axioms PerfectPower.SqrtTwoBatch.A078522_enumerates
#print axioms PerfectPower.SqrtTwoBatch.sq_eq_two_sq
#print axioms PerfectPower.SqrtTwoBatch.A055792_enumerates
#print axioms PerfectPower.SqrtTwoBatch.A_mod4
#print axioms PerfectPower.SqrtTwoBatch.A046176_enumerates
#print axioms PerfectPower.SqrtTwoBatch.A008843_enumerates
#print axioms PerfectPower.SqrtTwoBatch.A008843_A002315
#print axioms PerfectPower.SqrtTwoBatch.A008844_enumerates
#print axioms PerfectPower.SqrtTwoBatch.A008844_A001653
-- Generated.OEISAuto (written by python/make_oeis_auto.py)
#print axioms PerfectPower.OEISAuto.A000032_eq
#print axioms PerfectPower.OEISAuto.A000045_eq
#print axioms PerfectPower.OEISAuto.A000129_eq
#print axioms PerfectPower.OEISAuto.A000204_eq
#print axioms PerfectPower.OEISAuto.A001075_eq
#print axioms PerfectPower.OEISAuto.A001108_eq
#print axioms PerfectPower.OEISAuto.A001109_eq
#print axioms PerfectPower.OEISAuto.A001353_eq
#print axioms PerfectPower.OEISAuto.A001519_eq
#print axioms PerfectPower.OEISAuto.A001541_eq
#print axioms PerfectPower.OEISAuto.A001542_eq
#print axioms PerfectPower.OEISAuto.A001652_eq
#print axioms PerfectPower.OEISAuto.A001653_cert
#print axioms PerfectPower.OEISAuto.A001653_order
#print axioms PerfectPower.OEISAuto.A001653_enumerates
#print axioms PerfectPower.OEISAuto.A001835_eq
#print axioms PerfectPower.OEISAuto.A001906_rec
#print axioms PerfectPower.OEISAuto.A002315_eq
#print axioms PerfectPower.OEISAuto.A005319_eq
#print axioms PerfectPower.OEISAuto.A011944_eq
#print axioms PerfectPower.OEISAuto.A048739_eq
#print axioms PerfectPower.OEISAuto.A052454_cert
#print axioms PerfectPower.OEISAuto.A052454_order
#print axioms PerfectPower.OEISAuto.A052454_enumerates
#print axioms PerfectPower.OEISAuto.A052530_eq
#print axioms PerfectPower.OEISAuto.A052542_eq
#print axioms PerfectPower.OEISAuto.A052995_eq
#print axioms PerfectPower.OEISAuto.A067900_eq
#print axioms PerfectPower.OEISAuto.A074061_cert
#print axioms PerfectPower.OEISAuto.A074061_order
#print axioms PerfectPower.OEISAuto.A074061_enumerates
#print axioms PerfectPower.OEISAuto.A075796_cert
#print axioms PerfectPower.OEISAuto.A075796_order
#print axioms PerfectPower.OEISAuto.A075796_enumerates
#print axioms PerfectPower.OEISAuto.A075835_cert
#print axioms PerfectPower.OEISAuto.A075835_order
#print axioms PerfectPower.OEISAuto.A075835_enumerates
#print axioms PerfectPower.OEISAuto.A075836_cert
#print axioms PerfectPower.OEISAuto.A075836_order
#print axioms PerfectPower.OEISAuto.A075836_enumerates
#print axioms PerfectPower.OEISAuto.A075839_cert
#print axioms PerfectPower.OEISAuto.A075839_order
#print axioms PerfectPower.OEISAuto.A075839_enumerates
#print axioms PerfectPower.OEISAuto.A075841_cert
#print axioms PerfectPower.OEISAuto.A075841_order
#print axioms PerfectPower.OEISAuto.A075841_enumerates
#print axioms PerfectPower.OEISAuto.A075843_cert
#print axioms PerfectPower.OEISAuto.A075843_order
#print axioms PerfectPower.OEISAuto.A075843_enumerates
#print axioms PerfectPower.OEISAuto.A075844_cert
#print axioms PerfectPower.OEISAuto.A075844_order
#print axioms PerfectPower.OEISAuto.A075844_enumerates
#print axioms PerfectPower.OEISAuto.A075848_cert
#print axioms PerfectPower.OEISAuto.A075848_order
#print axioms PerfectPower.OEISAuto.A075848_enumerates
#print axioms PerfectPower.OEISAuto.A075869_cert
#print axioms PerfectPower.OEISAuto.A075869_order
#print axioms PerfectPower.OEISAuto.A075869_enumerates
#print axioms PerfectPower.OEISAuto.A075870_cert
#print axioms PerfectPower.OEISAuto.A075870_order
#print axioms PerfectPower.OEISAuto.A075870_enumerates
#print axioms PerfectPower.OEISAuto.A075871_cert
#print axioms PerfectPower.OEISAuto.A075871_order
#print axioms PerfectPower.OEISAuto.A075871_enumerates
#print axioms PerfectPower.OEISAuto.A077446_cert
#print axioms PerfectPower.OEISAuto.A077446_order
#print axioms PerfectPower.OEISAuto.A077446_enumerates
#print axioms PerfectPower.OEISAuto.A078057_eq
#print axioms PerfectPower.OEISAuto.A079935_eq
#print axioms PerfectPower.OEISAuto.A080806_cert
#print axioms PerfectPower.OEISAuto.A080806_order
#print axioms PerfectPower.OEISAuto.A080806_enumerates
#print axioms PerfectPower.OEISAuto.A082405_eq
#print axioms PerfectPower.OEISAuto.A082651_cert
#print axioms PerfectPower.OEISAuto.A082651_order
#print axioms PerfectPower.OEISAuto.A082651_enumerates
#print axioms PerfectPower.OEISAuto.A094347_eq
#print axioms PerfectPower.OEISAuto.A106256_cert
#print axioms PerfectPower.OEISAuto.A106256_order
#print axioms PerfectPower.OEISAuto.A106256_enumerates
#print axioms PerfectPower.OEISAuto.A128588_eq
#print axioms PerfectPower.OEISAuto.A133283_cert
#print axioms PerfectPower.OEISAuto.A133283_order
#print axioms PerfectPower.OEISAuto.A133283_enumerates
#print axioms PerfectPower.OEISAuto.A133326_cert
#print axioms PerfectPower.OEISAuto.A133326_order
#print axioms PerfectPower.OEISAuto.A133326_enumerates
#print axioms PerfectPower.OEISAuto.A144797_cert
#print axioms PerfectPower.OEISAuto.A144797_order
#print axioms PerfectPower.OEISAuto.A144797_enumerates
#print axioms PerfectPower.OEISAuto.A176981_eq
#print axioms PerfectPower.OEISAuto.A182435_eq
#print axioms PerfectPower.OEISAuto.A212804_eq
#print axioms PerfectPower.OEISAuto.A215928_eq
#print axioms PerfectPower.OEISAuto.A239365_cert
#print axioms PerfectPower.OEISAuto.A239365_order
#print axioms PerfectPower.OEISAuto.A239365_enumerates
#print axioms PerfectPower.OEISAuto.A259131_cert
#print axioms PerfectPower.OEISAuto.A259131_order
#print axioms PerfectPower.OEISAuto.A259131_enumerates
#print axioms PerfectPower.OEISAuto.A273052_cert
#print axioms PerfectPower.OEISAuto.A273052_order
#print axioms PerfectPower.OEISAuto.A273052_enumerates
#print axioms PerfectPower.OEISAuto.A273053_cert
#print axioms PerfectPower.OEISAuto.A273053_order
#print axioms PerfectPower.OEISAuto.A273053_enumerates
#print axioms PerfectPower.OEISAuto.A273054_cert
#print axioms PerfectPower.OEISAuto.A273054_order
#print axioms PerfectPower.OEISAuto.A273054_enumerates
#print axioms PerfectPower.OEISAuto.A288219_eq
#print axioms PerfectPower.OEISAuto.A309330_cert
#print axioms PerfectPower.OEISAuto.A309330_order
#print axioms PerfectPower.OEISAuto.A309330_enumerates
#print axioms PerfectPower.OEISAuto.A373566_eq
-- EffectiveEnumeration (ported from expert_push)
#print axioms PerfectPower.EffectiveEnumeration.mem_boundedSolutions
#print axioms PerfectPower.EffectiveEnumeration.enumeration_complete
#print axioms PerfectPower.EffectiveEnumeration.even_quartic_forward
#print axioms PerfectPower.EffectiveEnumeration.even_quartic_lift
#print axioms PerfectPower.EffectiveEnumeration.even_quartic_zero_fibre
#print axioms PerfectPower.EffectiveEnumeration.even_quartic_complete
-- DescentBranch / MordellMinus1 / SqrtTwoBridges / Generated.MordellBranch
#print axioms PerfectPower.DescentBranch.mem_divs
#print axioms PerfectPower.DescentBranch.ysOf_spec
#print axioms PerfectPower.DescentBranch.sort3
#print axioms PerfectPower.DescentBranch.divYs_complete
#print axioms PerfectPower.DescentBranch.branch_entry
#print axioms PerfectPower.DescentBranch.mod_sound
#print axioms PerfectPower.DescentBranch.cube_branch
#print axioms PerfectPower.DescentBranch.y_mem
#print axioms PerfectPower.DescentBranch.complete_of_branch
#print axioms PerfectPower.MordellMinus1.units_are_cubes
#print axioms PerfectPower.MordellMinus1.common_factor_cubes
#print axioms PerfectPower.MordellMinus1.complete
#print axioms PerfectPower.MordellMinus1.points_iff
#print axioms PerfectPower.SqrtTwoBridges.cf_sqrt2_s
#print axioms PerfectPower.SqrtTwoBridges.cf_sqrt2_h
#print axioms PerfectPower.SqrtTwoBridges.contsAux_sqrt2
#print axioms PerfectPower.SqrtTwoBridges.convs_sqrt2
#print axioms PerfectPower.SqrtTwoBridges.coprime_AB
#print axioms PerfectPower.SqrtTwoBridges.A001333_eq
#print axioms PerfectPower.SqrtTwoBridges.A001333_num
#print axioms PerfectPower.SqrtTwoBridges.euclid_primitive
#print axioms PerfectPower.SqrtTwoBridges.euclid_converse
#print axioms PerfectPower.SqrtTwoBridges.euclid_consecutive
#print axioms PerfectPower.SqrtTwoBridges.A048624_eq
#print axioms PerfectPower.Generated.MordellBranch.minus1
#print axioms PerfectPower.Generated.MordellBranch.minus8
#print axioms PerfectPower.Generated.MordellBranch.minus11
#print axioms PerfectPower.Generated.MordellBranch.minus16
#print axioms PerfectPower.Generated.MordellBranch.minus19
#print axioms PerfectPower.Generated.MordellBranch.minus20
#print axioms PerfectPower.Generated.MordellBranch.minus24
#print axioms PerfectPower.Generated.MordellBranch.minus27
#print axioms PerfectPower.Generated.MordellBranch.minus31
#print axioms PerfectPower.Generated.MordellBranch.minus35
#print axioms PerfectPower.Generated.MordellBranch.minus40
#print axioms PerfectPower.Generated.MordellBranch.minus44
#print axioms PerfectPower.Generated.MordellBranch.minus50
#print axioms PerfectPower.Generated.MordellBranch.minus51
#print axioms PerfectPower.Generated.MordellBranch.minus54
#print axioms PerfectPower.Generated.MordellBranch.minus59
#print axioms PerfectPower.Generated.MordellBranch.minus64
#print axioms PerfectPower.Generated.MordellBranch.minus67
#print axioms PerfectPower.Generated.MordellBranch.minus68
#print axioms PerfectPower.Generated.MordellBranch.minus75
#print axioms PerfectPower.Generated.MordellBranch.minus76
#print axioms PerfectPower.Generated.MordellBranch.minus81
#print axioms PerfectPower.Generated.MordellBranch.minus83
#print axioms PerfectPower.Generated.MordellBranch.minus84
#print axioms PerfectPower.Generated.MordellBranch.minus88
#print axioms PerfectPower.Generated.MordellBranch.minus96
-- MonomialCount
#print axioms PerfectPower.MonomialCount.nat_of_rat_pow
#print axioms PerfectPower.MonomialCount.monomial_param
#print axioms PerfectPower.MonomialCount.monomial_count
#print axioms PerfectPower.MonomialCount.filtered_orbit_count
#print axioms PerfectPower.MonomialCount.residue_class_count
#print axioms PerfectPower.MonomialCount.card_union_collisions
#print axioms PerfectPower.MonomialCount.sq_branch_count
-- ThueLocal / DescentThue / Generated.MordellThue
#print axioms PerfectPower.ThueLocal.evalF_compF
#print axioms PerfectPower.ThueLocal.sols_transport
#print axioms PerfectPower.ThueLocal.empty_transport
#print axioms PerfectPower.ThueLocal.evalF_modEq
#print axioms PerfectPower.ThueLocal.lift_step
#print axioms PerfectPower.ThueLocal.mem_lvl
#print axioms PerfectPower.ThueLocal.no_solution_of_lvl
#print axioms PerfectPower.ThueLocal.nodeB_step
#print axioms PerfectPower.ThueLocal.sound_of_step
#print axioms PerfectPower.ThueLocal.descM_sound
#print axioms PerfectPower.ThueLocal.no_solution_of_descM
#print axioms PerfectPower.ThueLocal.evalF_divF
#print axioms PerfectPower.ThueLocal.evalF_scale
#print axioms PerfectPower.ThueLocal.descB_sound
#print axioms PerfectPower.ThueLocal.no_solution_of_desc
#print axioms PerfectPower.DescentThue.branchForm_eval
#print axioms PerfectPower.DescentThue.branchT_entry
#print axioms PerfectPower.DescentThue.y_mem_thue
#print axioms PerfectPower.DescentThue.complete_of_thue
#print axioms PerfectPower.Generated.MordellThue.obl_21
#print axioms PerfectPower.Generated.MordellThue.obl_22
#print axioms PerfectPower.Generated.MordellThue.obl_23
#print axioms PerfectPower.Generated.MordellThue.obl_24
#print axioms PerfectPower.Generated.MordellThue.obl_25
#print axioms PerfectPower.Generated.MordellThue.obl_26
#print axioms PerfectPower.Generated.MordellThue.obl_38
#print axioms PerfectPower.Generated.MordellThue.obl_42
#print axioms PerfectPower.Generated.MordellThue.obl_45
#print axioms PerfectPower.Generated.MordellThue.obl_51
#print axioms PerfectPower.Generated.MordellThue.obl_59
#print axioms PerfectPower.Generated.MordellThue.obl_63
#print axioms PerfectPower.Generated.MordellThue.obl_64
#print axioms PerfectPower.Generated.MordellThue.obl_70
#print axioms PerfectPower.Generated.MordellThue.obl_71
#print axioms PerfectPower.Generated.MordellThue.minus29
#print axioms PerfectPower.Generated.MordellThue.minus32
#print axioms PerfectPower.Generated.MordellThue.minus36
#print axioms PerfectPower.Generated.MordellThue.minus38
#print axioms PerfectPower.Generated.MordellThue.minus52
#print axioms PerfectPower.Generated.MordellThue.minus56
#print axioms PerfectPower.Generated.MordellThue.minus77
#print axioms PerfectPower.Generated.MordellThue.minus80
#print axioms PerfectPower.Generated.MordellThue.minus86
#print axioms PerfectPower.Generated.MordellThue.minus92
-- Interfaces
#print axioms PerfectPower.Interfaces.restricted_transport
#print axioms PerfectPower.Interfaces.restricted_empty
#print axioms PerfectPower.Interfaces.evalF_compF_mul
#print axioms PerfectPower.Interfaces.detM_mul
#print axioms PerfectPower.Interfaces.bound_transport
#print axioms PerfectPower.Interfaces.sublattice_branch
#print axioms PerfectPower.Interfaces.line_image
#print axioms PerfectPower.Interfaces.vert_image
#print axioms PerfectPower.Interfaces.shift_shift
#print axioms PerfectPower.Interfaces.split_prefix
#print axioms PerfectPower.Interfaces.A048624_terms_match
#print axioms PerfectPower.Interfaces.A048624_shift_unique
#print axioms PerfectPower.Interfaces.A048624_shift_of_terms
#print axioms PerfectPower.Interfaces.orbit_mod_three
-- NormForm
#print axioms PerfectPower.NormForm.mulMat_spec
#print axioms PerfectPower.NormForm.det_mulMat
#print axioms PerfectPower.NormForm.d72_det
#print axioms PerfectPower.NormForm.d72_mulMat
#print axioms PerfectPower.NormForm.d72_no_root_mod5
#print axioms PerfectPower.NormForm.d72_no_int_root
#print axioms PerfectPower.NormForm.d72_disc
#print axioms PerfectPower.NormForm.mulD_spec
#print axioms PerfectPower.NormForm.d72_beta_of_delta
#print axioms PerfectPower.NormForm.d72_gamma_delta
#print axioms PerfectPower.NormForm.d72_lattice
#print axioms PerfectPower.NormForm.d72_det_delta
#print axioms PerfectPower.NormForm.d72_norm_eps1
#print axioms PerfectPower.NormForm.d72_norm_eps2
#print axioms PerfectPower.NormForm.d72_norm_alpha
