import PerfectPower.Generated.LinearCatalogue
#print axioms PerfectPower.LinearPerturbation.coordinate_bound
#print axioms PerfectPower.LinearPerturbation.expanded
#print axioms PerfectPower.LinearPerturbation.squareRoots_complete
#print axioms PerfectPower.LinearPerturbation.complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_000_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_001_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_002_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_003_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_004_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_005_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_006_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_007_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_008_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_009_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_010_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_011_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_012_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_013_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_014_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_015_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_016_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_017_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_018_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_019_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_020_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_021_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_022_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_023_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_024_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_025_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_026_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_027_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_028_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_029_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_030_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_031_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_032_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_033_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_034_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_035_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_036_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_037_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_038_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_039_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_040_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_041_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_042_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_043_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_044_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_045_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_046_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_047_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_048_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_049_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_050_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_051_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_052_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_053_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_054_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_055_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_056_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_057_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_058_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_059_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_060_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_061_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_062_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_063_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_064_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_065_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_066_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_067_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_068_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_069_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_070_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_071_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_072_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_073_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_074_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_075_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_076_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_077_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_078_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_079_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_080_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_081_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_082_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_083_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_084_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_085_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_086_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_087_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_088_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_089_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_090_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_091_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_092_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_093_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_094_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_095_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_096_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_097_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_098_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_099_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_100_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_101_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_102_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_103_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_104_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_105_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_106_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_107_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_108_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_109_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_110_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_111_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_112_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_113_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_114_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_115_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_116_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_117_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_118_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_119_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_120_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_121_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_122_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_123_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_124_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_125_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_126_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_127_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_128_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_129_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_130_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_131_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_132_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_133_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_134_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_135_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_136_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_137_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_138_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_139_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_140_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_141_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_142_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_143_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_144_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_145_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_146_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_147_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_148_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_149_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_150_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_151_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_152_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_153_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_154_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_155_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_156_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_157_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_158_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_159_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_160_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_161_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_162_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_163_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_164_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_165_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_166_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_167_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_168_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_169_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_170_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_171_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_172_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_173_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_174_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_175_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_176_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_177_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_178_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_179_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_180_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_181_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_182_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_183_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_184_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_185_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_186_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_187_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_188_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_189_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_190_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_191_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_192_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_193_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_194_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_195_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_196_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_197_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_198_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_199_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_200_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_201_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_202_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_203_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_204_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_205_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_206_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_207_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_208_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_209_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_210_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_211_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_212_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_213_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_214_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_215_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_216_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_217_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_218_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_219_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_220_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_221_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_222_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_223_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_224_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_225_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_226_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_227_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_228_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_229_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_230_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_231_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_232_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_233_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_234_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_235_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_236_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_237_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_238_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_239_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_240_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_241_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_242_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_243_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_244_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_245_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_246_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_247_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_248_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_249_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_250_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_251_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_252_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_253_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_254_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_255_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_256_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_257_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_258_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_259_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_260_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_261_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_262_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_263_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_264_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_265_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_266_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_267_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_268_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_269_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_270_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_271_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_272_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_273_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_274_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_275_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_276_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_277_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_278_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_279_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_280_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_281_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_282_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_283_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_284_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_285_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_286_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_287_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_288_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_289_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_290_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_291_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_292_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_293_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_294_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_295_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_296_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_297_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_298_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_299_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_300_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_301_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_302_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_303_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_304_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_305_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_306_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_307_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_308_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_309_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_310_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_311_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_312_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_313_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_314_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_315_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_316_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_317_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_318_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_319_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_320_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_321_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_322_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_323_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_324_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_325_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_326_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_327_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_328_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_329_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_330_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_331_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_332_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_333_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_334_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_335_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_336_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_337_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_338_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_339_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_340_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_341_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_342_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_343_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_344_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_345_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_346_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_347_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_348_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_349_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_350_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_351_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_352_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_353_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_354_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_355_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_356_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_357_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_358_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_359_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_360_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_361_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_362_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_363_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_364_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_365_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_366_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_367_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_368_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_369_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_370_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_371_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_372_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_373_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_374_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_375_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_376_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_377_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_378_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_379_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_380_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_381_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_382_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_383_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_384_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_385_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_386_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_387_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_388_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_389_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_390_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_391_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_392_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_393_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_394_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_395_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_396_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_397_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_398_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_399_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_400_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_401_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_402_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_403_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_404_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_405_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_406_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_407_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_408_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_409_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_410_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_411_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_412_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_413_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_414_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_415_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_416_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_417_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_418_complete
#print axioms PerfectPower.Generated.LinearCatalogue.case_419_complete
#print axioms PerfectPower.Generated.LinearCatalogue.total_points
#print axioms PerfectPower.Generated.LinearCatalogue.empty_curves
native_linear_perturbation nonmonic_demo for 3, -2, 1, 5, -7
native_linear_perturbation zero_fibre_demo for 1, 0, -1, 2, 2
#print axioms nonmonic_demo_complete
#print axioms zero_fibre_demo_complete
example : (-1,0) ∈ zero_fibre_demo := by decide +kernel
example : True := by
  fail_if_success
    have bad : (100,0) ∈ nonmonic_demo := by decide +kernel
  trivial
