import PerfectPower.Exponential  -- every hand-written module; Generated/ is excluded
import PerfectPower.Davenport
import PerfectPower.ABC
import PerfectPower.Binomial
import PerfectPower.RadicalValuation
import PerfectPower.PellGeneral
import PerfectPower.RadicalCount
import PerfectPower.ProfileG
import PerfectPower.Reflect
import PerfectPower.PellExact
import PerfectPower.RadicalAsymp
import PerfectPower.Atlas
import PerfectPower.Genus1
import PerfectPower.MordellDescent
import PerfectPower.MordellFLT3
import PerfectPower.MordellMinus2
import PerfectPower.MordellMinus4
import PerfectPower.ClassTwo
import PerfectPower.MordellMinus13
import PerfectPower.MordellMinus5
import PerfectPower.MordellMinus6
import PerfectPower.Transport
import PerfectPower.Continuation.DenominatorReduction
import PerfectPower.Continuation.RadicalCountGeneral
import PerfectPower.Continuation.PellCountGeneral
import PerfectPower.Continuation.KappaPositive
import PerfectPower.Continuation.PellPositive
import PerfectPower.Continuation.ExplicitK
import PerfectPower.Continuation.PellExplicitK
import PerfectPower.Reduction
import PerfectPower.FilteredPell
import PerfectPower.FilteredCount
import PerfectPower.PlanCerts
import PerfectPower.FilteredAuto
import PerfectPower.MordellFamily
import PerfectPower.KernelArith
import PerfectPower.Descent
import PerfectPower.Observation
import PerfectPower.SquareTriangular
import PerfectPower.SqrtTwoOrbit
import PerfectPower.QuadOrbit
import PerfectPower.FibOrbit
import PerfectPower.OEISLib
import PerfectPower.SqrtTwoBatch
import PerfectPower.EffectiveEnumeration
import PerfectPower.DescentBranch
import PerfectPower.MordellMinus1
import PerfectPower.SqrtTwoBridges
import PerfectPower.SqrtTwoDefs
import PerfectPower.AbelianTransforms
import PerfectPower.DescentLists
import PerfectPower.Generated.Minus23
import PerfectPower.Generated.Minus45
import PerfectPower.Generated.Minus18
import PerfectPower.Generated.Minus89
import PerfectPower.OrderEmbedding
import PerfectPower.PowerCertificate
import PerfectPower.Generated.OrderMaps
import PerfectPower.Generated.Minus39
import PerfectPower.Generated.Minus47
import PerfectPower.Generated.Minus60
import PerfectPower.Generated.Minus72
import PerfectPower.Generated.Order1620
import PerfectPower.Generated.Minus15
import PerfectPower.Generated.Minus26
import PerfectPower.Generated.Minus48
import PerfectPower.Generated.Minus55
import PerfectPower.Generated.Minus71
import PerfectPower.NormCover
import PerfectPower.Generated.Covers2700
import PerfectPower.Generated.Order2700
import PerfectPower.Generated.Minus25
import PerfectPower.Generated.Minus100
import PerfectPower.Generated.Covers5724
import PerfectPower.Generated.Covers9396
import PerfectPower.Generated.Minus53
import PerfectPower.Generated.Minus87
import PerfectPower.Generated.Minus95
import PerfectPower.Generated.Covers6588
import PerfectPower.Generated.Minus61
import PerfectPower.NormRepSlices
import PerfectPower.UnitGenResidue
import PerfectPower.Weierstrass
import PerfectPower.Generated.OrderMaps8532
import PerfectPower.Generated.Covers8532
import PerfectPower.Generated.Minus79
import PerfectPower.MordellCubicForm
import PerfectPower.Generated.PositiveK
import PerfectPower.ReducibleThue
import PerfectPower.PositiveKCurve
import PerfectPower.Generated.PositiveKComplete
import PerfectPower.CubicReduction
import PerfectPower.ClassListProof
import PerfectPower.BVWorkflow
import PerfectPower.ArithmeticWorkflow
import PerfectPower.Generated.WorkflowInstances
import PerfectPower.Generated.WorkflowContexts
import PerfectPower.MonomialCount
import PerfectPower.ThueLocal
import PerfectPower.DescentThue
import PerfectPower.Interfaces
import PerfectPower.NormForm
import PerfectPower.BoundedPell
import PerfectPower.DirectReduction
import PerfectPower.UnitPremises
import PerfectPower.UnitGen
import PerfectPower.NormRepProof
import PerfectPower.RatInterval
import PerfectPower.AnalyticBridge
import PerfectPower.Generated.Order1944
import PerfectPower.Generated.D72Unit
import PerfectPower.D72Residual
import PerfectPower.UnitBox
import PerfectPower.DescentThueList
import PerfectPower.Generated.Field756
import Batteries.Tactic.Lint
import PerfectPower.Skolem3
import PerfectPower.Plus2
import PerfectPower.SkolemP
import PerfectPower.RankOne
import PerfectPower.DiophBridge
/-! Batteries' environment linters over the hand-written library, not the generated certificates (docstrings, unused haves,
simp-normal forms, ...).  Run with `lake env lean audit/Lint.lean`; it must report 0 errors. -/
#lint in PerfectPower
