import PerfectPower.PSGStructural
import PerfectPower.Generated.PSGStructuralPackets
import PerfectPower.SOESemantics
import PerfectPower.StructuralCertificates
import PerfectPower.StructuralSpecies
import PerfectPower.NewWorkClosure
import PerfectPower.AdaptiveDiagnosis
import PerfectPower.Generated.StructuralPackets
import PerfectPower.Generated.SOEModelPackets
#print axioms PerfectPower.PSGStructural.quadratic_norm_identity
#print axioms PerfectPower.PSGStructural.quadratic_elimination_identity
#print axioms PerfectPower.PSGStructural.quadratic_elimination_sound
#print axioms PerfectPower.PSGStructural.exceptional_source
#print axioms PerfectPower.PSGStructural.source_at_reconstruction
#print axioms PerfectPower.PSGStructural.cofactor_product
#print axioms PerfectPower.PSGStructural.redundant_pair
#print axioms PerfectPower.PSGStructural.affine_norm_transport
#print axioms PerfectPower.PSGStructural.regular_linear_unique
#print axioms PerfectPower.PSGStructural.norm_regular_square
#print axioms PerfectPower.PSGStructural.regular_reconstruction
#print axioms PerfectPower.PSGStructuralPackets.source_reduction
#print axioms PerfectPower.PSGStructuralPackets.recovered_norm
#print axioms PerfectPower.PSGStructuralPackets.original_source_sound
#print axioms PerfectPower.PSGStructuralPackets.darboux_0
#print axioms PerfectPower.PSGStructuralPackets.darboux_1
#print axioms PerfectPower.PSGStructuralPackets.darboux_2
#print axioms PerfectPower.PSGStructuralPackets.darboux_3
#print axioms PerfectPower.PSGStructuralPackets.darboux_4
#print axioms PerfectPower.PSGStructuralPackets.darboux_5
#print axioms PerfectPower.SOESemantics.run_transport
#print axioms PerfectPower.SOESemantics.behavior_transport
#print axioms PerfectPower.SOESemantics.quotient_complete
#print axioms PerfectPower.SOESemantics.witness_sound
#print axioms PerfectPower.SOESemantics.minimum_cost
#print axioms PerfectPower.SOESemantics.valuation_transport
#print axioms PerfectPower.StructuralCertificates.weighted_squares_nonnegative
#print axioms PerfectPower.StructuralCertificates.gram_sound
#print axioms PerfectPower.StructuralCertificates.constraint_product_nonnegative
#print axioms PerfectPower.StructuralCertificates.lower_bound_sound
#print axioms PerfectPower.StructuralCertificates.negative_quartic_of_nonpositive_middle
#print axioms PerfectPower.StructuralCertificates.cover_to_curve
#print axioms PerfectPower.StructuralCertificates.rank_bound_from_image_sizes
#print axioms PerfectPower.StructuralSpecies.occupations_reconstruct
#print axioms PerfectPower.StructuralSpecies.monomial_power
#print axioms PerfectPower.StructuralSpecies.bounded_power_exponent
#print axioms PerfectPower.NewWorkClosure.reconstruction_complete
#print axioms PerfectPower.NewWorkClosure.chart_inverse
#print axioms PerfectPower.NewWorkClosure.chart_forward
#print axioms PerfectPower.NewWorkClosure.chart_jacobian
#print axioms PerfectPower.NewWorkClosure.chart_observations
#print axioms PerfectPower.AdaptiveDiagnosis.optimal_correct
#print axioms PerfectPower.AdaptiveDiagnosis.optimal_cost
#print axioms PerfectPower.AdaptiveDiagnosis.zero_cost_leaf
#print axioms PerfectPower.AdaptiveDiagnosis.lower_bound
#print axioms PerfectPower.AdaptiveDiagnosis.fixed_three
#print axioms PerfectPower.AdaptiveDiagnosis.fixed_two_fail
#print axioms PerfectPower.StructuralPackets.ldl0
#print axioms PerfectPower.StructuralPackets.nonnegative0
#print axioms PerfectPower.StructuralPackets.dissipation0
#print axioms PerfectPower.StructuralPackets.ldl1
#print axioms PerfectPower.StructuralPackets.nonnegative1
#print axioms PerfectPower.StructuralPackets.dissipation1
#print axioms PerfectPower.StructuralPackets.ldl2
#print axioms PerfectPower.StructuralPackets.nonnegative2
#print axioms PerfectPower.StructuralPackets.ldl3
#print axioms PerfectPower.StructuralPackets.nonnegative3
#print axioms PerfectPower.StructuralPackets.global_energy
#print axioms PerfectPower.StructuralPackets.slice_energy
#print axioms PerfectPower.StructuralPackets.slice_attainment
#print axioms PerfectPower.SOEModelPackets.complete000
#print axioms PerfectPower.SOEModelPackets.complete001
#print axioms PerfectPower.SOEModelPackets.complete002
#print axioms PerfectPower.SOEModelPackets.complete003
#print axioms PerfectPower.SOEModelPackets.complete004
#print axioms PerfectPower.SOEModelPackets.complete005
#print axioms PerfectPower.SOEModelPackets.complete006
#print axioms PerfectPower.SOEModelPackets.complete007
#print axioms PerfectPower.SOEModelPackets.complete008
#print axioms PerfectPower.SOEModelPackets.complete009
#print axioms PerfectPower.SOEModelPackets.complete010
#print axioms PerfectPower.SOEModelPackets.complete011
#print axioms PerfectPower.SOEModelPackets.complete012
#print axioms PerfectPower.SOEModelPackets.complete013
#print axioms PerfectPower.SOEModelPackets.complete014
#print axioms PerfectPower.SOEModelPackets.complete015
#print axioms PerfectPower.SOEModelPackets.complete016
#print axioms PerfectPower.SOEModelPackets.complete017
#print axioms PerfectPower.SOEModelPackets.complete018
#print axioms PerfectPower.SOEModelPackets.complete019
#print axioms PerfectPower.SOEModelPackets.complete020
#print axioms PerfectPower.SOEModelPackets.complete021
#print axioms PerfectPower.SOEModelPackets.complete022
#print axioms PerfectPower.SOEModelPackets.complete023
#print axioms PerfectPower.SOEModelPackets.complete024
#print axioms PerfectPower.SOEModelPackets.complete025
#print axioms PerfectPower.SOEModelPackets.complete026
#print axioms PerfectPower.SOEModelPackets.complete027
#print axioms PerfectPower.SOEModelPackets.complete028
#print axioms PerfectPower.SOEModelPackets.complete029
#print axioms PerfectPower.SOEModelPackets.complete030
#print axioms PerfectPower.SOEModelPackets.complete031
#print axioms PerfectPower.SOEModelPackets.complete032
#print axioms PerfectPower.SOEModelPackets.complete033
#print axioms PerfectPower.SOEModelPackets.complete034
#print axioms PerfectPower.SOEModelPackets.complete035
#print axioms PerfectPower.SOEModelPackets.complete036
#print axioms PerfectPower.SOEModelPackets.complete037
#print axioms PerfectPower.SOEModelPackets.complete038
#print axioms PerfectPower.SOEModelPackets.complete039
#print axioms PerfectPower.SOEModelPackets.complete040
#print axioms PerfectPower.SOEModelPackets.complete041
#print axioms PerfectPower.SOEModelPackets.complete042
#print axioms PerfectPower.SOEModelPackets.complete043
#print axioms PerfectPower.SOEModelPackets.complete044
#print axioms PerfectPower.SOEModelPackets.complete045
#print axioms PerfectPower.SOEModelPackets.complete046
#print axioms PerfectPower.SOEModelPackets.complete047
#print axioms PerfectPower.SOEModelPackets.complete048
#print axioms PerfectPower.SOEModelPackets.complete049
#print axioms PerfectPower.SOEModelPackets.complete050
#print axioms PerfectPower.SOEModelPackets.complete051
#print axioms PerfectPower.SOEModelPackets.complete052
#print axioms PerfectPower.SOEModelPackets.complete053
#print axioms PerfectPower.SOEModelPackets.complete054
#print axioms PerfectPower.SOEModelPackets.complete055
#print axioms PerfectPower.SOEModelPackets.complete056
#print axioms PerfectPower.SOEModelPackets.complete057
#print axioms PerfectPower.SOEModelPackets.complete058
#print axioms PerfectPower.SOEModelPackets.complete059
#print axioms PerfectPower.SOEModelPackets.complete060
#print axioms PerfectPower.SOEModelPackets.complete061
#print axioms PerfectPower.SOEModelPackets.complete062
#print axioms PerfectPower.SOEModelPackets.complete063
#print axioms PerfectPower.SOEModelPackets.complete064
#print axioms PerfectPower.SOEModelPackets.complete065
#print axioms PerfectPower.SOEModelPackets.complete066
#print axioms PerfectPower.SOEModelPackets.complete067
#print axioms PerfectPower.SOEModelPackets.complete068
#print axioms PerfectPower.SOEModelPackets.complete069
#print axioms PerfectPower.SOEModelPackets.complete070
#print axioms PerfectPower.SOEModelPackets.complete071
#print axioms PerfectPower.SOEModelPackets.complete072
#print axioms PerfectPower.SOEModelPackets.complete073
#print axioms PerfectPower.SOEModelPackets.complete074
#print axioms PerfectPower.SOEModelPackets.complete075
#print axioms PerfectPower.SOEModelPackets.complete076
#print axioms PerfectPower.SOEModelPackets.complete077
#print axioms PerfectPower.SOEModelPackets.complete078
#print axioms PerfectPower.SOEModelPackets.complete079
#print axioms PerfectPower.SOEModelPackets.complete080
#print axioms PerfectPower.SOEModelPackets.complete081
#print axioms PerfectPower.SOEModelPackets.complete082
#print axioms PerfectPower.SOEModelPackets.complete083
#print axioms PerfectPower.SOEModelPackets.complete084
#print axioms PerfectPower.SOEModelPackets.complete085
#print axioms PerfectPower.SOEModelPackets.complete086
#print axioms PerfectPower.SOEModelPackets.complete087
#print axioms PerfectPower.SOEModelPackets.complete088
#print axioms PerfectPower.SOEModelPackets.complete089
#print axioms PerfectPower.SOEModelPackets.complete090
#print axioms PerfectPower.SOEModelPackets.complete091
#print axioms PerfectPower.SOEModelPackets.complete092
#print axioms PerfectPower.SOEModelPackets.complete093
#print axioms PerfectPower.SOEModelPackets.complete094
#print axioms PerfectPower.SOEModelPackets.complete095
#print axioms PerfectPower.SOEModelPackets.complete096
#print axioms PerfectPower.SOEModelPackets.complete097
#print axioms PerfectPower.SOEModelPackets.complete098
#print axioms PerfectPower.SOEModelPackets.complete099
#print axioms PerfectPower.SOEModelPackets.complete100
#print axioms PerfectPower.SOEModelPackets.complete101
#print axioms PerfectPower.SOEModelPackets.complete102
#print axioms PerfectPower.SOEModelPackets.complete103
#print axioms PerfectPower.SOEModelPackets.complete104
#print axioms PerfectPower.SOEModelPackets.complete105
#print axioms PerfectPower.SOEModelPackets.complete106
#print axioms PerfectPower.SOEModelPackets.complete107
#print axioms PerfectPower.SOEModelPackets.complete108
#print axioms PerfectPower.SOEModelPackets.complete109
#print axioms PerfectPower.SOEModelPackets.complete110
#print axioms PerfectPower.SOEModelPackets.complete111
#print axioms PerfectPower.SOEModelPackets.complete112
#print axioms PerfectPower.SOEModelPackets.complete113
#print axioms PerfectPower.SOEModelPackets.complete114
#print axioms PerfectPower.SOEModelPackets.complete115
#print axioms PerfectPower.SOEModelPackets.complete116
#print axioms PerfectPower.SOEModelPackets.complete117
#print axioms PerfectPower.SOEModelPackets.complete118
#print axioms PerfectPower.SOEModelPackets.complete119
#print axioms PerfectPower.SOEModelPackets.complete120
#print axioms PerfectPower.SOEModelPackets.complete121
#print axioms PerfectPower.SOEModelPackets.complete122
#print axioms PerfectPower.SOEModelPackets.complete123
#print axioms PerfectPower.SOEModelPackets.complete124
#print axioms PerfectPower.SOEModelPackets.complete125
#print axioms PerfectPower.SOEModelPackets.complete126
#print axioms PerfectPower.SOEModelPackets.complete127
#print axioms PerfectPower.SOEModelPackets.complete128
#print axioms PerfectPower.SOEModelPackets.complete129
#print axioms PerfectPower.SOEModelPackets.complete130
#print axioms PerfectPower.SOEModelPackets.complete131
#print axioms PerfectPower.SOEModelPackets.complete132
#print axioms PerfectPower.SOEModelPackets.complete133
#print axioms PerfectPower.SOEModelPackets.complete134
#print axioms PerfectPower.SOEModelPackets.complete135
#print axioms PerfectPower.SOEModelPackets.complete136
#print axioms PerfectPower.SOEModelPackets.complete137
#print axioms PerfectPower.SOEModelPackets.complete138
#print axioms PerfectPower.SOEModelPackets.complete139
#print axioms PerfectPower.SOEModelPackets.complete140
#print axioms PerfectPower.SOEModelPackets.complete141
#print axioms PerfectPower.SOEModelPackets.complete142
#print axioms PerfectPower.SOEModelPackets.complete143
#print axioms PerfectPower.SOEModelPackets.complete144
#print axioms PerfectPower.SOEModelPackets.complete145
#print axioms PerfectPower.SOEModelPackets.complete146
#print axioms PerfectPower.SOEModelPackets.complete147
#print axioms PerfectPower.SOEModelPackets.complete148
#print axioms PerfectPower.SOEModelPackets.complete149
#print axioms PerfectPower.SOEModelPackets.complete150
#print axioms PerfectPower.SOEModelPackets.complete151
#print axioms PerfectPower.SOEModelPackets.complete152
#print axioms PerfectPower.SOEModelPackets.complete153
#print axioms PerfectPower.SOEModelPackets.complete154
#print axioms PerfectPower.SOEModelPackets.complete155
#print axioms PerfectPower.SOEModelPackets.complete156
#print axioms PerfectPower.SOEModelPackets.complete157
#print axioms PerfectPower.SOEModelPackets.complete158
#print axioms PerfectPower.SOEModelPackets.complete159
#print axioms PerfectPower.SOEModelPackets.complete160
#print axioms PerfectPower.SOEModelPackets.complete161
#print axioms PerfectPower.SOEModelPackets.complete162
#print axioms PerfectPower.SOEModelPackets.complete163
#print axioms PerfectPower.SOEModelPackets.complete164
#print axioms PerfectPower.SOEModelPackets.complete165
#print axioms PerfectPower.SOEModelPackets.complete166
#print axioms PerfectPower.SOEModelPackets.complete167
#print axioms PerfectPower.SOEModelPackets.complete168
#print axioms PerfectPower.SOEModelPackets.complete169
#print axioms PerfectPower.SOEModelPackets.complete170
#print axioms PerfectPower.SOEModelPackets.complete171
#print axioms PerfectPower.SOEModelPackets.complete172
#print axioms PerfectPower.SOEModelPackets.complete173
#print axioms PerfectPower.SOEModelPackets.complete174
#print axioms PerfectPower.SOEModelPackets.complete175
#print axioms PerfectPower.SOEModelPackets.complete176
#print axioms PerfectPower.SOEModelPackets.complete177
#print axioms PerfectPower.SOEModelPackets.complete178
#print axioms PerfectPower.SOEModelPackets.complete179
#print axioms PerfectPower.SOEModelPackets.complete180
#print axioms PerfectPower.SOEModelPackets.complete181
#print axioms PerfectPower.SOEModelPackets.complete182
#print axioms PerfectPower.SOEModelPackets.complete183
#print axioms PerfectPower.SOEModelPackets.complete184
#print axioms PerfectPower.SOEModelPackets.complete185
#print axioms PerfectPower.SOEModelPackets.complete186
#print axioms PerfectPower.SOEModelPackets.complete187
#print axioms PerfectPower.SOEModelPackets.complete188
#print axioms PerfectPower.SOEModelPackets.complete189
#print axioms PerfectPower.SOEModelPackets.complete190
#print axioms PerfectPower.SOEModelPackets.complete191
#print axioms PerfectPower.SOEModelPackets.complete192
#print axioms PerfectPower.SOEModelPackets.complete193
#print axioms PerfectPower.SOEModelPackets.complete194
#print axioms PerfectPower.SOEModelPackets.complete195
#print axioms PerfectPower.SOEModelPackets.complete196
#print axioms PerfectPower.SOEModelPackets.complete197
#print axioms PerfectPower.SOEModelPackets.complete198
#print axioms PerfectPower.SOEModelPackets.complete199
#print axioms PerfectPower.SOEModelPackets.complete200
#print axioms PerfectPower.SOEModelPackets.complete201
#print axioms PerfectPower.SOEModelPackets.complete202
#print axioms PerfectPower.SOEModelPackets.complete203
#print axioms PerfectPower.SOEModelPackets.complete204
#print axioms PerfectPower.SOEModelPackets.complete205
#print axioms PerfectPower.SOEModelPackets.complete206
#print axioms PerfectPower.SOEModelPackets.complete207
#print axioms PerfectPower.SOEModelPackets.complete208
#print axioms PerfectPower.SOEModelPackets.complete209
#print axioms PerfectPower.SOEModelPackets.complete210
#print axioms PerfectPower.SOEModelPackets.complete211
#print axioms PerfectPower.SOEModelPackets.complete212
#print axioms PerfectPower.SOEModelPackets.complete213
#print axioms PerfectPower.SOEModelPackets.complete214
#print axioms PerfectPower.SOEModelPackets.complete215
#print axioms PerfectPower.SOEModelPackets.complete216
#print axioms PerfectPower.SOEModelPackets.complete217
#print axioms PerfectPower.SOEModelPackets.complete218
#print axioms PerfectPower.SOEModelPackets.complete219
#print axioms PerfectPower.SOEModelPackets.complete220
#print axioms PerfectPower.SOEModelPackets.complete221
#print axioms PerfectPower.SOEModelPackets.complete222
#print axioms PerfectPower.SOEModelPackets.complete223
#print axioms PerfectPower.SOEModelPackets.complete224
#print axioms PerfectPower.SOEModelPackets.complete225
#print axioms PerfectPower.SOEModelPackets.complete226
#print axioms PerfectPower.SOEModelPackets.complete227
#print axioms PerfectPower.SOEModelPackets.complete228
#print axioms PerfectPower.SOEModelPackets.complete229
#print axioms PerfectPower.SOEModelPackets.complete230
#print axioms PerfectPower.SOEModelPackets.complete231
#print axioms PerfectPower.SOEModelPackets.complete232
#print axioms PerfectPower.SOEModelPackets.complete233
#print axioms PerfectPower.SOEModelPackets.complete234
#print axioms PerfectPower.SOEModelPackets.complete235
#print axioms PerfectPower.SOEModelPackets.complete236
#print axioms PerfectPower.SOEModelPackets.complete237
#print axioms PerfectPower.SOEModelPackets.complete238
#print axioms PerfectPower.SOEModelPackets.complete239
#print axioms PerfectPower.SOEModelPackets.complete240
#print axioms PerfectPower.SOEModelPackets.complete241
#print axioms PerfectPower.SOEModelPackets.complete242
#print axioms PerfectPower.SOEModelPackets.complete243
#print axioms PerfectPower.SOEModelPackets.complete244
#print axioms PerfectPower.SOEModelPackets.complete245
#print axioms PerfectPower.SOEModelPackets.complete246
#print axioms PerfectPower.SOEModelPackets.complete247
#print axioms PerfectPower.SOEModelPackets.complete248
#print axioms PerfectPower.SOEModelPackets.complete249
#print axioms PerfectPower.SOEModelPackets.complete250
#print axioms PerfectPower.SOEModelPackets.complete251
#print axioms PerfectPower.SOEModelPackets.complete252
#print axioms PerfectPower.SOEModelPackets.complete253
#print axioms PerfectPower.SOEModelPackets.complete254
#print axioms PerfectPower.SOEModelPackets.complete255
#print axioms PerfectPower.SOEModelPackets.complete256
#print axioms PerfectPower.SOEModelPackets.complete257
#print axioms PerfectPower.SOEModelPackets.complete258
#print axioms PerfectPower.SOEModelPackets.complete259
#print axioms PerfectPower.SOEModelPackets.complete260
#print axioms PerfectPower.SOEModelPackets.complete261
#print axioms PerfectPower.SOEModelPackets.complete262
#print axioms PerfectPower.SOEModelPackets.complete263
#print axioms PerfectPower.SOEModelPackets.complete264
#print axioms PerfectPower.SOEModelPackets.complete265
#print axioms PerfectPower.SOEModelPackets.complete266
#print axioms PerfectPower.SOEModelPackets.complete267
#print axioms PerfectPower.SOEModelPackets.complete268
#print axioms PerfectPower.SOEModelPackets.complete269
#print axioms PerfectPower.SOEModelPackets.complete270
#print axioms PerfectPower.SOEModelPackets.complete271
#print axioms PerfectPower.SOEModelPackets.complete272
#print axioms PerfectPower.SOEModelPackets.complete273
#print axioms PerfectPower.SOEModelPackets.complete274
#print axioms PerfectPower.SOEModelPackets.complete275
#print axioms PerfectPower.SOEModelPackets.complete276
#print axioms PerfectPower.SOEModelPackets.complete277
#print axioms PerfectPower.SOEModelPackets.complete278
#print axioms PerfectPower.SOEModelPackets.complete279
#print axioms PerfectPower.SOEModelPackets.complete280
#print axioms PerfectPower.SOEModelPackets.complete281
#print axioms PerfectPower.SOEModelPackets.complete282
#print axioms PerfectPower.SOEModelPackets.complete283
#print axioms PerfectPower.SOEModelPackets.complete284
#print axioms PerfectPower.SOEModelPackets.complete285
#print axioms PerfectPower.SOEModelPackets.complete286
#print axioms PerfectPower.SOEModelPackets.complete287
#print axioms PerfectPower.SOEModelPackets.complete288
#print axioms PerfectPower.SOEModelPackets.complete289
#print axioms PerfectPower.SOEModelPackets.complete290
#print axioms PerfectPower.SOEModelPackets.complete291
#print axioms PerfectPower.SOEModelPackets.complete292
#print axioms PerfectPower.SOEModelPackets.complete293
#print axioms PerfectPower.SOEModelPackets.complete294
#print axioms PerfectPower.SOEModelPackets.complete295
#print axioms PerfectPower.SOEModelPackets.complete296
#print axioms PerfectPower.SOEModelPackets.complete297
#print axioms PerfectPower.SOEModelPackets.complete298
#print axioms PerfectPower.SOEModelPackets.complete299
#print axioms PerfectPower.SOEModelPackets.complete300
#print axioms PerfectPower.SOEModelPackets.complete301
#print axioms PerfectPower.SOEModelPackets.complete302
#print axioms PerfectPower.SOEModelPackets.complete303
#print axioms PerfectPower.SOEModelPackets.complete304
#print axioms PerfectPower.SOEModelPackets.complete305
#print axioms PerfectPower.SOEModelPackets.complete306
#print axioms PerfectPower.SOEModelPackets.complete307
#print axioms PerfectPower.SOEModelPackets.complete308
#print axioms PerfectPower.SOEModelPackets.complete309
#print axioms PerfectPower.SOEModelPackets.complete310
#print axioms PerfectPower.SOEModelPackets.complete311
#print axioms PerfectPower.SOEModelPackets.complete312
#print axioms PerfectPower.SOEModelPackets.complete313
#print axioms PerfectPower.SOEModelPackets.complete314
#print axioms PerfectPower.SOEModelPackets.complete315
#print axioms PerfectPower.SOEModelPackets.complete316
#print axioms PerfectPower.SOEModelPackets.complete317
#print axioms PerfectPower.SOEModelPackets.complete318
#print axioms PerfectPower.SOEModelPackets.complete319
#print axioms PerfectPower.SOEModelPackets.complete320
#print axioms PerfectPower.SOEModelPackets.complete321
#print axioms PerfectPower.SOEModelPackets.complete322
#print axioms PerfectPower.SOEModelPackets.complete323
