import PerfectPower.WeilMonomial

#print axioms PerfectPower.MonomialOrbitSpace.fixed_respects
#print axioms PerfectPower.MonomialOrbitSpace.fixed_finrank
#print axioms PerfectPower.MonomialOrbitSpace.phase_finrank
#print axioms PerfectPower.MonomialOrbitSpace.reflection_coeff
#print axioms PerfectPower.MonomialOrbitSpace.quotientEquiv
#print axioms PerfectPower.MonomialOrbitSpace.gaugeEquiv
#print axioms PerfectPower.WeilMonomial.coeff_synth
#print axioms PerfectPower.WeilMonomial.synth_coeff
#print axioms PerfectPower.WeilMonomial.basis_apply
#print axioms PerfectPower.WeilMonomial.heisenberg_apply
#print axioms PerfectPower.WeilMonomial.fourier_mul_heisenberg_entry
#print axioms PerfectPower.WeilMonomial.heisenberg_mul_fourier_entry
#print axioms PerfectPower.WeilMonomial.fourier_intertwines
#print axioms PerfectPower.WeilMonomial.chirp_intertwines
#print axioms PerfectPower.WeilMonomial.heisenberg_transpose
#print axioms PerfectPower.WeilMonomial.basis_repr
#print axioms PerfectPower.WeilMonomial.expansion
#print axioms PerfectPower.WeilMonomial.synth_as_sum
#print axioms PerfectPower.WeilMonomial.reindex_synth
#print axioms PerfectPower.WeilMonomial.fourier_conjugates
#print axioms PerfectPower.WeilMonomial.fourier_synth
#print axioms PerfectPower.WeilMonomial.conjugation_fixed_iff
#print axioms PerfectPower.WeilMonomial.monomial_fixed_iff
#print axioms PerfectPower.WeilMonomial.commute_fourier_iff
#print axioms PerfectPower.WeilMonomial.chirp_inverse
#print axioms PerfectPower.WeilMonomial.inverse_chirp
#print axioms PerfectPower.WeilMonomial.chirp_conjugates
#print axioms PerfectPower.WeilMonomial.chirp_synth
#print axioms PerfectPower.WeilMonomial.commute_chirp_iff
#print axioms PerfectPower.WeilMonomial.commutant_iff
#print axioms PerfectPower.WeilMonomial.character_ne_zero
#print axioms PerfectPower.WeilMonomial.odd_gauge_consistent
#print axioms PerfectPower.WeilMonomial.odd_commutant_finrank
#print axioms PerfectPower.WeilMonomial.transpose_synth
#print axioms PerfectPower.WeilMonomial.odd_commutant_symmetric
#print axioms PerfectPower.WeilMonomial.odd_commutative_of_reflection
#print axioms PerfectPower.WeilMonomial.odd_level_finrank
#print axioms PerfectPower.WeilMonomial.coordinates
#print axioms PerfectPower.WeilMonomial.basis
#print axioms PerfectPower.WeilMonomial.commutantEquiv
#print axioms PerfectPower.WeilMonomial.oddOrbitEquiv
