import {gcd,mod,crt,population,integerInput,overlap} from './dresden-math.ts';
export type Rational={n:bigint;d:bigint};
export function rational(n:bigint,d=1n):Rational{if(!d)throw Error('Zero denominator');if(d<0n){n=-n;d=-d;}const g=gcd(n,d);return {n:n/g,d:d/g};}
export function parseRational(s:string):Rational{if(s.length>160)throw Error('Reference has too many digits');if(/^-?\d+\/[1-9]\d*$/.test(s)){const[a,b]=s.split('/');return rational(BigInt(a),BigInt(b));}if(!/^-?\d+(\.\d+)?$/.test(s))throw Error('Use a decimal or integer fraction');const negative=s.startsWith('-'),[a,b='']=s.replace('-','').split('.');return rational(BigInt(a+b)*(negative?-1n:1n),10n**BigInt(b.length));}
export const add=(a:Rational,b:Rational)=>rational(a.n*b.d+b.n*a.d,a.d*b.d);
export const sub=(a:Rational,b:Rational)=>rational(a.n*b.d-b.n*a.d,a.d*b.d);
export const mul=(a:Rational,b:Rational)=>rational(a.n*b.n,a.d*b.d);
export const abs=(a:Rational)=>rational(a.n<0n?-a.n:a.n,a.d);
export const compare=(a:Rational,b:Rational)=>a.n*b.d<b.n*a.d?-1:a.n*b.d>b.n*a.d?1:0;
export const exact=(a:Rational)=>a.d===1n?a.n.toString():`${a.n}/${a.d}`;
export function decimal(a:Rational,places=6){const scale=10n**BigInt(places),sign=a.n<0n?'-':'',n=a.n<0n?-a.n:a.n,scaled=(n*scale+a.d/2n)/a.d;return sign+scaled/scale+(places?'.'+(scaled%scale).toString().padStart(places,'0'):'');}
export function solveCalendar(number:number,sign:number,haab:number,venus:number|null,lo:bigint,hi:bigint,rank=0n){if(!Number.isInteger(number)||number<1||number>13||!Number.isInteger(sign)||sign<0||sign>19||!Number.isInteger(haab)||haab<0||haab>364||venus!==null&&(!Number.isInteger(venus)||venus<0||venus>583))throw Error('Calendar phase is outside its canonical range');if(lo<0n||hi<lo||rank<0n)throw Error('Bounds and rank must be ordered nonnegative integers');let p=crt(BigInt(number-4),13n,BigInt(sign-19),20n)!;p=crt(p.residue,p.modulus,BigInt(haab-348),365n)!;if(p&&venus!==null)p=crt(p.residue,p.modulus,BigInt(venus),584n)!;if(!p)return {compatible:false as const};const count=population(p.residue,p.modulus,lo,hi),first=lo+mod(p.residue-lo,p.modulus);return {compatible:true as const,...p,count,first:count?first:null,last:count?first+(count-1n)*p.modulus:null,selected:rank<count?first+rank*p.modulus:null};}
export function daysFromDigits(digits:number[]){if(!digits.length||digits.some(d=>!Number.isInteger(d)||d<0))throw Error('Nonnegative integer digits required');let weight=1n,total=0n;for(let i=digits.length-1;i>=0;i--){const pos=digits.length-1-i;if(i&&digits[i]>=(pos===1?18:20))throw Error('Noncanonical lower digit');total+=BigInt(digits[i])*weight;weight*=pos===0?20n:pos===1?18n:20n;}return total;}
export const venusModels=[{id:'canonical_584',label:'584-day recurrence',rounds:1n,days:584n},{id:'aldana_CVI1',label:'71,240 / 122 rounds',rounds:122n,days:71240n},{id:'aldana_CVI2',label:'106,860 / 183 rounds',rounds:183n,days:106860n}];
export function venusExperiment(rounds:bigint,model:number,reference:Rational){if(rounds<0n||!Number.isInteger(model)||model<0||model>2||reference.n<=0n)throw Error('Positive mean and nonnegative round horizon required');const rule=venusModels[model],q=rounds/rule.rounds,r=rounds%rule.rounds;const at=(n:bigint)=>{const day=n/rule.rounds*rule.days+n%rule.rounds*584n;return {day,error:sub(rational(day),mul(rational(n),reference))};};const candidates=new Set([0n,rounds,q*rule.rounds]);if(q)candidates.add(rule.rounds-1n).add((q-1n)*rule.rounds).add(q*rule.rounds-1n);const values=[...candidates].sort((a,b)=>a<b?-1:a>b?1:0).map(n=>({round:n,...at(n)}));let minimum=values[0],maximum=values[0];values.forEach(v=>{if(compare(v.error,minimum.error)<0)minimum=v;if(compare(v.error,maximum.error)>0)maximum=v;});return {model:rule.id,rounds,reference,mean:rational(rule.days,rule.rounds),blocks:q,remainder:r,...at(rounds),minimum,maximum,candidateRounds:values.map(v=>v.round)};}
export function intervalDistribution(days:number[],span:number,start=0,end=days.length){if(!Number.isInteger(span)||span<1||!Number.isInteger(start)||!Number.isInteger(end)||start<0||end>days.length||end-start<=span)throw Error('Window must contain more appearances than its month span');if(days.some((d,i)=>!Number.isSafeInteger(d)||i>0&&days[i-1]>=d))throw Error('Strictly increasing integer days required');const hist=new Map<number,number>();for(let i=start;i+span<end;i++){const d=days[i+span]-days[i];hist.set(d,(hist.get(d)??0)+1);}return [...hist].sort((a,b)=>a[0]-b[0]).map(([days,count])=>({days,count}));}
export function distributionSummary(rows:{days:number;count:number}[]){if(!rows.length||rows.some(r=>!Number.isSafeInteger(r.days)||!Number.isSafeInteger(r.count)||r.count<=0))throw Error('Positive empirical count histogram required');let count=0n,sum=0n,squares=0n;for(const r of rows){const c=BigInt(r.count),d=BigInt(r.days);count+=c;sum+=c*d;squares+=c*d*d;}const mean=rational(sum,count),variance=sub(rational(squares,count),mul(mean,mean));const sorted=[...rows].sort((a,b)=>a.days-b.days);const quantile=(numerator:bigint,denominator:bigint)=>{let rank=(count*numerator+denominator-1n)/denominator;if(rank<1n)rank=1n;let acc=0n;for(const r of sorted){acc+=BigInt(r.count);if(acc>=rank)return r.days;}return sorted.at(-1)!.days;};return {count,mean,variance,median:quantile(1n,2n),central95:[quantile(1n,40n),quantile(39n,40n)]};}
export function totalVariation(a:{days:number;count:number}[],b:{days:number;count:number}[],aOffset=0,bOffset=0){const an=a.reduce((s,r)=>s+r.count,0),bn=b.reduce((s,r)=>s+r.count,0);if(!an||!bn)throw Error('Nonempty distributions required');const A=new Map<number,number>(),B=new Map<number,number>();for(const [rows,hist,offset]of [[a,A,aOffset],[b,B,bOffset]]as const)for(const r of rows){if(!Number.isSafeInteger(r.days)||!Number.isSafeInteger(r.count)||r.count<=0)throw Error('Positive empirical counts required');const d=r.days-offset;hist.set(d,(hist.get(d)??0)+r.count);}let distance=rational(0n);for(const d of new Set([...A.keys(),...B.keys()]))distance=add(distance,abs(sub(rational(BigInt(A.get(d)??0),BigInt(an)),rational(BigInt(B.get(d)??0),BigInt(bn)))));return mul(distance,rational(1n,2n));}
export function rankPrediction(schedule:ReturnType<typeof overlap>,rank:bigint,start=0n){if(rank<0n||start<0n||!schedule.first.size)throw Error('Nonnegative rank/start and a nonempty schedule required');const prior=start?schedule.count(start-1n):0n,target=prior+rank+1n;let lo=start,hi=start+BigInt(schedule.period)*(rank/BigInt(schedule.first.size)+2n)+BigInt(Math.max(...schedule.first.values()));while(schedule.count(hi)<target)hi=hi*2n+1n;while(lo<hi){const mid=(lo+hi)/2n;if(schedule.count(mid)<target)lo=mid+1n;else hi=mid;}return lo;}
export function customRestartOrders(long:Rational,short:Rational){const orders=Array.from({length:5},(_,position)=>{let value=rational(0n),peak=rational(0n);const prefixes=[value];for(let j=0;j<5;j++){value=add(value,j===position?short:long);prefixes.push(value);if(compare(abs(value),peak)>0)peak=abs(value);}return {position,prefixes,peak,terminal:value};});const best=orders.reduce((a,b)=>compare(a.peak,b.peak)<=0?a:b).peak;return {orders,best,winners:orders.filter(o=>compare(o.peak,best)===0).map(o=>o.position)};}
export function exportJson(name:string,value:unknown){const blob=new Blob([JSON.stringify(value,(_key,v)=>typeof v==='bigint'?v.toString():v,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
