[main]
datadir = "/workspace/scratch/109155aec88d/why3_runtime/usr/share/why3"
libdir = "/workspace/scratch/109155aec88d/why3_runtime/usr/lib/ocaml/why3"
default_editor = ""
running_provers_max = 1
magic = 14


[prover]
name = "Z3"
version = "5.1.0"
alternative = "native"
command = "/workspace/scratch/109155aec88d/workflow_deps/bin/z3 -smt2 -T:%t %f"
driver = "/workspace/scratch/109155aec88d/why3_runtime/usr/share/why3/drivers/z3_487.drv"

[prover]
name = "Z3"
version = "5.1.0"
alternative = "pp"
command = "python /workspace/scratch/109155aec88d/perfectpower_real_workflow_push/pp_z3.py --solver /workspace/scratch/109155aec88d/workflow_deps/bin/z3 --seconds %t --receipts /workspace/scratch/109155aec88d/perfectpower_real_workflow_push/receipts/host_certificates %f"
driver = "/workspace/scratch/109155aec88d/why3_runtime/usr/share/why3/drivers/z3_487.drv"
