import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import source from './ingested-population.json';
import {createComparisonNotebook} from './comparison-notebook.js';
import {explainDesign,explainFamily} from './detail.js';
import {createWorkbench} from './workbench.js';
import {createScenarios} from './scenarios.js';
import {createMuseum,ROOM,gearGeometry,roundedBlock} from './museum.js';

const $=id=>document.getElementById(id);
const models=[];for(let m=1;m<=12;m++)for(let g=1;g<=8;g++)for(let a=1;a<=3;a++)models.push({id:models.length,m,g,a,cost:8*m+3*g+4*a,size:m+g+a,drive:m*g});
let matrixDirty=true,renderDirty=true;
let scenarios,bench;let inspecting=false,designReport=null;
let museum,hiddenRejected=false,presentation=false,narrating=false;
let current='workshop', layout=false, selected=-1, matches=[], step=0, searching=false, checked=0, searchStart=0, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches, auto=false, autoTime=0;
let T=10n**40n, familyRank=T+1n, scene, camera, renderer, controls, machineGroup, familyGroup, floor, marker, scanRing, items=[], parts=[], rotors=[], last=performance.now(), toastTimer, transition=null;
const pale=new THREE.Color('#253e4c'),gold=new THREE.Color('#d4ad6d'),mint=new THREE.Color('#7fdac3'),amber=new THREE.Color('#f6cb80');
const compareColors={both:new THREE.Color('#82dfcb'),onlyA:new THREE.Color('#f2b782'),onlyB:new THREE.Color('#c5b4ff'),neither:pale};
const origin=new THREE.Vector3();const dummy=new THREE.Object3D();const ray=new THREE.Raycaster();const mouse=new THREE.Vector2();
const chapters=[
 ['A room full of possibilities.','Each little machine is a different design. This room contains every combination of the choices in our example.'],
 ['Search finds one good answer.','An inspection ring visits designs one at a time. When it finds a working machine, it stops. The rest of the collection still matters.'],
 ['A requirement changes the collection.','Increase the lifting score or reduce the size limit. Whole groups of designs fall outside the rules. Every count comes from the same 288 objects.'],
 ['Give every answer a place.','The machines move into a map: motor choice runs left to right, gear choice runs front to back, and arm length determines the level. Their identities stay the same.'],
 ['Ask again without starting over.','Select the least-cost answer, visit another, or jump to an address. These questions reuse the current collection. Change a requirement and its addresses update.'],
 ['What changed between two questions?','Capture a collection as A, change the requirements, and capture B. Colors distinguish designs in both, only A, only B, and neither. Each design keeps its identity.'],
 ['Now enter a room you cannot draw.','For 2x² = 3y³, the origin and two branches give every integer point. A ceiling T gives 2T + 1 points. Seventeen are pictured; the exact count reaches much farther.'],
 ['An address works in both directions.','At T = 10⁴⁰, address T + 1 selects (−18, 6). Recovering its address uses the family structure. Save this scene, export the point, or explore another exact address.']
];
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200)}
function conditions(){return {load:Number($('load').value),size:Number($('size').value),square:$('square').checked}}
function reasons(d){let c=conditions(),r=[];if(d.drive<c.load*d.a)r.push('Lifting score is too low');if(d.size>c.size)r.push('Size score exceeds the limit');if(c.square&&!Number.isInteger(Math.sqrt(d.drive)))r.push('Drive value is not a square');return r}
function update(){matrixDirty=true;document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed','false'));stopSearch();matches=models.filter(d=>!reasons(d).length);$('count').textContent=matches.length;$('load-value').textContent=$('load').value;$('size-value').textContent=$('size').value;$('empty').hidden=current!=='workshop'||matches.length>0;$('rank').max=String(matches.length);for(let id of ['best','another','jump'])$(id).disabled=!matches.length; $('address-hint').textContent=matches.length?`Working addresses: 1–${matches.length}, ordered by motor, gears, arm.`:'No working addresses in this collection.';if(selected>=0)showSelection(selected,false);refreshColors();updateTextView();updateWaterfall();scenarios?.sync();museum?.update({...conditions(),visible:!inspecting&&layout&&current==='workshop',room:inspecting?'workshop':current==='family'?'family':layout?'map':'workshop'})}
function updateTextView(){const rows=matches.slice(0,30);$('text-view').innerHTML=`<p>${matches.length} working designs. Showing the first ${rows.length}.</p><table><thead><tr><th>Address</th><th>Motor</th><th>Gears</th><th>Arm</th><th>Cost</th></tr></thead><tbody>${rows.map((d,i)=>`<tr><td>${i+1}</td><td>${d.m}</td><td>${d.g}</td><td>${d.a}</td><td>${d.cost}</td></tr>`).join('')}</tbody></table>`}
function refreshColors(){renderDirty=true;if(!parts.length)return;const allowed=new Set(matches.map(d=>d.id));for(let part of parts){models.forEach(d=>{let category=scenarios?.category(d.id);let color=category?compareColors[category]:d.id===selected?amber:(allowed.has(d.id)?(part.userData.metal?gold:mint):pale);part.setColorAt(d.id,color);});part.instanceColor.needsUpdate=true;}}
function stopSearch(){searching=false;checked=0;if(scanRing)scanRing.visible=false;if($('search-meter'))$('search-meter').hidden=true;$('search').textContent='Find one by searching'}
function startSearch(){stopSearch();setExhibit('workshop');selected=-1;$('selection').hidden=true;searching=true;$('search-meter').hidden=false;$('search-status').textContent='Inspecting the room';searchStart=performance.now();refreshColors();$('search').textContent='Searching… click to stop';if(reduced){finishSearch(matches[0]?.id??-1, matches[0]?matches[0].id+1:288)}}
function finishSearch(id,n){searching=false;scanRing.visible=false;$('search-status').textContent=id>=0?'A working design found':'The entire room checked';$('search-count').textContent=String(n);$('search-progress').value=n;$('search').textContent='Find one by searching';if(id>=0){showSelection(id,true);notify(`Found a working design after ${n} ${n===1?'check':'checks'}.`)}else notify('All 288 designs checked. None meet these requirements.')}
function showSelection(id,focus=true){selected=id;const d=models[id],rank=matches.findIndex(x=>x.id===id),r=reasons(d);$('selection').hidden=false;$('selected-title').textContent=`Design ${String(id+1).padStart(3,'0')}`;$('selected-badge').textContent=rank<0?'Outside the current requirements':`Working address ${rank+1} of ${matches.length}`;$('selected-badge').style.color=rank<0?'var(--danger)':'var(--mint)';$('selected-values').innerHTML=`<span>Motor<strong>${d.m}</strong></span><span>Gears<strong>${d.g}</strong></span><span>Arm length<strong>${d.a}</strong></span><span>Lifting score<strong>${Math.floor(d.drive/d.a)}</strong></span><span>Size score<strong>${d.size}</strong></span><span>Cost score<strong>${d.cost}</strong></span>`;$('selected-reason').textContent=r.length?r.join('. ')+'.':`Drive ${d.drive}${Number.isInteger(Math.sqrt(d.drive))?' = '+Math.sqrt(d.drive)+'²':''}. Meets every active requirement.`;if(scenarios?.state.active)$('selected-reason').textContent+=' '+scenarios.membership(id);if(rank>=0)$('rank').value=String(rank+1);if(inspecting){renderWorkbench();bench?.setModel(d);museum?.update({...conditions(),visible:false,room:'workshop'})}refreshColors();if(marker){marker.visible=current==='workshop'&&!inspecting;marker.position.copy(items[id].position);marker.position.y+=.035;}if(focus&&controls&&!inspecting){let pos=items[id].position;moveCamera(new THREE.Vector3(pos.x+7,pos.y+6,pos.z+8),pos.clone().add(new THREE.Vector3(0,.8,0)),1.1)}}
function goRank(){const value=Number($('rank').value);if(!Number.isInteger(value)||value<1||value>matches.length){notify('Enter an address in the current collection.');return}showSelection(matches[value-1].id)}
function best(){if(!matches.length)return;const objective=$('objective').value,score=d=>objective==='lift'?-Math.floor(d.drive/d.a):objective==='size'?d.size:d.cost;let minimum=Math.min(...matches.map(score));let opts=matches.filter(d=>score(d)===minimum);showSelection(opts[0].id);notify(`${objective==='lift'?'Highest lifting score: '+(-minimum):objective==='size'?'Smallest size score: '+minimum:'Least cost: '+minimum}. ${opts.length===1?'One design achieves it.':opts.length+' designs tie; showing the first.'}`)}
function another(){if(!matches.length)return;let i=matches.findIndex(d=>d.id===selected);showSelection(matches[(i+1)%matches.length].id)}
function save(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCollection(){save('perfectpower-machine-collection.json',{schema:'pp-room-machine-model/1',domain:{motor:[1,12],gears:[1,8],arm:[1,3]},requirements:conditions(),count:matches.length,order:'motor, gears, arm; displayed addresses start at one',scope:'Fictional integer design model; not a physical performance prediction or a Lean proof.',designs:matches.map((d,i)=>({address:i+1,...d}))});notify('Exported the current collection.')}
function moveCamera(position,target,duration=2.1){if(!camera)return;if(camera.aspect<.85){position=target.clone().add(position.clone().sub(target).multiplyScalar(1.32));}if(reduced){camera.position.copy(position);controls.target.copy(target);controls.update();transition=null;return}transition={start:performance.now(),duration:duration*1000,p0:camera.position.clone(),p1:position,t0:controls.target.clone(),t1:target};}
function resetCamera(){if(inspecting){moveCamera(new THREE.Vector3(10,8,15),new THREE.Vector3(0,2.6,0));return}const offset=current==='family'?ROOM.family:layout?ROOM.map:ROOM.workshop;if(current==='family')moveCamera(new THREE.Vector3(offset+15,11,21),new THREE.Vector3(offset,2.8,0));else if(layout)moveCamera(new THREE.Vector3(offset+21,19,29),new THREE.Vector3(offset,3,0));else moveCamera(new THREE.Vector3(29,27,35),new THREE.Vector3(0,0,0));}
function setLayout(value){if(inspecting)closeWorkbench(false);layout=value;syncRoom();museum?.update({...conditions(),visible:layout&&current==='workshop',room:current==='family'?'family':layout?'map':'workshop'});$('layout').setAttribute('aria-pressed',String(value));$('layout').textContent=value?'Workshop floor':'Spatial map';$('map').textContent=value?'Return to the workshop':'Map all working designs';$('view-heading').textContent=value?'A map of the whole collection':'The machine workshop';$('view-subheading').textContent=value?'Motor / horizontal · gears / depth · arm / level':'12 motors · 8 gear settings · 3 arm lengths';resetCamera()}
function setExhibit(value){if(inspecting)closeWorkbench(false);stopSearch();current=value;document.querySelector('.sidebar').scrollTop=0;let isFamily=value==='family';$('family-panel').hidden=!isFamily;$('workshop-panel').hidden=isFamily;$('family-tab').setAttribute('aria-pressed',String(isFamily));$('workshop-tab').setAttribute('aria-pressed',String(!isFamily));$('family-tab').classList.toggle('active',isFamily);$('workshop-tab').classList.toggle('active',!isFamily);$('legend').hidden=isFamily;$('layout').hidden=isFamily;$('family-readout').hidden=!isFamily;$('empty').hidden=isFamily||matches.length>0;$('selection').hidden=true;if(machineGroup)machineGroup.visible=!isFamily;if(familyGroup)familyGroup.visible=isFamily;syncRoom();museum?.update({...conditions(),visible:layout&&!isFamily,room:isFamily?'family':layout?'map':'workshop'});if(marker)marker.visible=false;$('view-heading').textContent=isFamily?'The exact family / parameter chart':layout?'A map of the whole collection':'The machine workshop';$('view-subheading').textContent=isFamily?'17 illustrated points · exact queries reach the full family':layout?'Motor / horizontal · gears / depth · arm / level':'12 motors · 8 gear settings · 3 arm lengths';if(isFamily){$('tour').hidden=true;showFamilyPoint();}else $('tour').hidden=false;$('tour-toggle').textContent=$('tour').hidden?'Show tour':'Hide tour';scenarios?.sync();resetCamera()}
function readNatural(id){let raw=$(id).value.trim();if(!/^\d{1,61}$/.test(raw))throw new Error('Enter a whole nonnegative number, up to 61 digits.');let v=BigInt(raw),limit=(id==='family-rank'?2n:1n)*10n**60n;if(v>limit)throw new Error('This demonstration supports ceilings up to 10⁶⁰ and their corresponding addresses.');return v}
function applyBound(){try{const nextT=readNatural('bound');T=nextT;if(familyRank>2n*T)familyRank=2n*T;$('family-rank').value=familyRank.toString();showFamilyPoint();notify('Updated the bound. The family formula is reused.')}catch(e){notify(e.message)}}
function familySelect(rank){if(rank<0n||rank>2n*T)throw new Error('Choose an address from zero through '+(2n*T).toString()+'.');if(rank===0n)return {rank,t:0n,x:0n,y:0n,chart:'zero'};let positive=rank<=T,t=positive?rank:rank-T;return {rank,t,x:(positive?18n:-18n)*t*t*t,y:6n*t*t,chart:positive?'positive x':'negative x'}}
function showFamilyPoint(){renderDirty=true;const p=familySelect(familyRank);if(familyGroup)for(const obj of familyGroup.children){if(obj.userData.familyT>0){const active=BigInt(obj.userData.familyT)<=T;obj.material.color.copy(active?mint:pale);obj.material.emissiveIntensity=active?.3:0;}}const total=(2n*T+1n).toString(),tString=T.toString(),powers='⁰¹²³⁴⁵⁶⁷⁸⁹';$('family-count').textContent=/^10+$/.test(tString)&&tString.length>10?'2 × 10'+String(tString.length-1).split('').map(n=>powers[Number(n)]).join('')+' + 1':(2n*T+1n).toLocaleString('en-US');$('family-count').title=total;const huge=p.x.toString().length>25; $('family-point').innerHTML=`<small>Selected address ${p.rank.toLocaleString('en-US')} · ${p.chart}</small><div>x = ${huge?(p.x<0n?'−':'')+'18 × t³':p.x}</div><div>y = ${huge?'6 × t²':p.y}</div>${huge?'<details class="coordinate-details"><summary>Full integer coordinates</summary><div>x = '+p.x+'</div><div>y = '+p.y+'</div></details>':''}`;$('family-detail').textContent=p.t===0n?'The origin has one owner and is counted once.':`This point uses t = ${p.t}. Its coordinates satisfy 2x² = 3y³ exactly.`;$('family-prev').disabled=familyRank===0n;$('family-next').disabled=familyRank===2n*T;window.__atlasState.family={bound:T.toString(),count:(2n*T+1n).toString(),rank:familyRank.toString(),x:p.x.toString(),y:p.y.toString()};renderFamilyGuide(p);if(familyMarker){const z=Number(p.t>8n?8n:p.t),x=p.t===0n?0:(p.x>0n?1:-1)*(1.5+z*.65);familyMarker.position.set(x,.16+z*.65, -2+z*.45);familyMarker.visible=p.t<=8n;}}
function jumpFamily(){try{let value=readNatural('family-rank');familySelect(value);familyRank=value;showFamilyPoint()}catch(e){notify(e.message)}}
function tourStep(i){
 autoTime=performance.now();step=Math.max(0,Math.min(chapters.length-1,i));
 $('tour-kicker').textContent=`The guided walkthrough / ${step+1} of ${chapters.length}`;
 $('tour-title').textContent=chapters[step][0];$('tour-text').textContent=chapters[step][1];
 $('prev').disabled=step===0;$('next').textContent=step===chapters.length-1?'Explore on your own':'Continue';
 document.querySelectorAll('#steps button').forEach((b,j)=>b.setAttribute('aria-pressed',String(j===step)));
 setExhibit(step>=6?'family':'workshop');$('tour').hidden=false;$('tour-toggle').textContent='Hide tour';
 if(step===0){$('load').value=12;$('size').value=10;$('square').checked=false;$('objective').value='cost';$('best').textContent='Least cost';hiddenRejected=false;$('hide-rejected').checked=false;if($('compare-view').checked){$('compare-view').checked=false;$('compare-view').dispatchEvent(new Event('change'))}update();setLayout(false);resetCamera()}
 if(step===1){setLayout(false);startSearch()}
 if(step===2){stopSearch();applyPreset('square');resetCamera();$('tour-text').textContent='With lifting score 12 and size limit 10, thirteen designs work. Requiring a square drive leaves one. Try the sliders to explore another collection.';}
 if(step===3)setLayout(true);
 if(step===4){setLayout(true);best()}
 if(step===5){stopSearch();setLayout(true);$('comparison-panel').open=true;selected=-1;$('selection').hidden=true;if(marker)marker.visible=false;$('load').value=12;$('size').value=10;$('square').checked=false;update();$('capture-A').click();$('square').checked=true;update();$('capture-B').click();$('tour-text').textContent='A holds the original thirteen designs. B adds the square-drive rule: one stays in both, twelve work only in A, and none work only in B. Try a different B to see new possibilities.';moveCamera(new THREE.Vector3(ROOM.map+26,24,32),new THREE.Vector3(ROOM.map,3,0))}
 if(step===6){T=10n**40n;familyRank=0n;$('bound').value=T.toString();$('family-rank').value='0';showFamilyPoint();resetCamera()}
 if(step===7){T=10n**40n;$('bound').value=T.toString();familyRank=T+1n;$('family-rank').value=familyRank.toString();showFamilyPoint();$('inverse-x').value='-18';$('inverse-y').value='6';locatePoint()}
 if(narrating)speak(chapters[step][0]+' '+$('tour-text').textContent)
}
for(let i=0;i<chapters.length;i++){const b=document.createElement('button');b.textContent=String(i+1);b.setAttribute('aria-label',`Tour chapter ${i+1}: ${chapters[i][0]}`);b.onclick=()=>{auto=false;syncAuto();tourStep(i)};$('steps').append(b)}
function syncAuto(){$('autoplay').textContent=auto?'Pause tour':'Play tour';$('autoplay').setAttribute('aria-pressed',String(auto))}
$('next').onclick=()=>{if(step===chapters.length-1){auto=false;syncAuto();$('tour').hidden=true;$('tour-toggle').textContent='Show tour'}else tourStep(step+1)};$('prev').onclick=()=>tourStep(step-1);$('autoplay').onclick=()=>{auto=!auto;autoTime=performance.now();syncAuto()};$('tour-toggle').onclick=()=>{$('tour').hidden=!$('tour').hidden;$('tour-toggle').textContent=$('tour').hidden?'Show tour':'Hide tour';if($('tour').hidden){auto=false;syncAuto()}};
for(let id of ['load','size','square'])$(id).addEventListener('input',update);$('search').onclick=()=>searching?stopSearch():startSearch();$('map').onclick=()=>setLayout(!layout);$('layout').onclick=()=>setLayout(!layout);$('reset-camera').onclick=resetCamera;$('best').onclick=best;$('another').onclick=another;$('jump').onclick=goRank;$('rank').onkeydown=e=>{if(e.key==='Enter')goRank()};$('export').onclick=exportCollection;$('close-selection').onclick=()=>{selected=-1;$('selection').hidden=true;if(marker)marker.visible=false;refreshColors()};$('workshop-tab').onclick=()=>{setExhibit('workshop');setLayout(false)};$('family-tab').onclick=()=>{auto=false;syncAuto();setExhibit('family')};$('apply-bound').onclick=applyBound;$('family-jump').onclick=jumpFamily;$('family-rank').onkeydown=e=>{if(e.key==='Enter')jumpFamily()};$('bound').onkeydown=e=>{if(e.key==='Enter')applyBound()};$('family-prev').onclick=()=>{if(familyRank>0n)familyRank--; $('family-rank').value=familyRank.toString();showFamilyPoint()};$('family-next').onclick=()=>{if(familyRank<2n*T)familyRank++;$('family-rank').value=familyRank.toString();showFamilyPoint()};$('family-export').onclick=()=>{let p=familySelect(familyRank);save('perfectpower-exact-point.json',{schema:'pp-room-exact-point/1',source_commit:source.source_commit,equation:'2*x^2=3*y^3',bound:T.toString(),population_count:(2n*T+1n).toString(),point:Object.fromEntries(Object.entries(p).map(([k,v])=>[k,typeof v==='bigint'?v.toString():v])),execution:'Exact BigInt chart evaluation; not a new Lean proof.'})};$('motion').checked=reduced;$('motion').onchange=()=>{reduced=$('motion').checked;$('lab-motion').checked=reduced;if(reduced&&searching)finishSearch(matches[0]?.id??-1,matches[0]?matches[0].id+1:288)};
window.__atlasState={version:'4.0',ready:false,source,models,query:()=>({conditions:conditions(),count:matches.length,ids:matches.map(d=>d.id),layout,current,selected,hiddenRejected,presentation,inspecting}),explain:id=>explainDesign(models[id],conditions(),models),detail:()=>({active:inspecting,report:designReport,explode:bench?.amount,components:bench?.componentCount}),familyExplanation:()=>explainFamily(T,familySelect(familyRank)),scenarios:()=>scenarios?.state,positions:()=>items.map(i=>i.position.toArray()),family:{},familySelect:r=>{const p=familySelect(BigInt(r));return Object.fromEntries(Object.entries(p).map(([k,v])=>[k,typeof v==='bigint'?v.toString():v]))}};



function renderWorkbench(){
 const d=models[selected];designReport=explainDesign(d,conditions(),models);$('lab-title').textContent=`Design ${String(d.id+1).padStart(3,'0')}`;
 for(const [id,key] of [['lab-m','m'],['lab-g','g'],['lab-a','a']])$(id).value=String(d[key]);
 $('lab-status').textContent=designReport.passes?'This design meets every current requirement.':'This design falls outside the current requirements.';$('lab-status').style.borderColor=designReport.passes?'var(--mint)':'#f4a9a0';
 $('lab-checks').innerHTML=designReport.checks.map(x=>`<section class="lab-check"><header><span>${x.name}</span><span class="${x.pass?'pass':'fail'}">${x.pass?'Pass':'Fail'}</span></header><p>${x.expression}</p><small>${x.margin===null?'':`Margin: ${x.margin}. `}${x.meaning}</small></section>`).join('');
 $('lab-cost').textContent=designReport.cost_expression;$('lab-repair').textContent=designReport.repair?`${designReport.repair_reason} Result: lifting ${designReport.repair.load}, size ${designReport.repair.size}, square rule ${designReport.repair.square?'on':'off'}.`:designReport.repair_reason;
 $('lab-relax').disabled=!designReport.repair;
 const n=designReport.nearest;$('lab-neighbor').textContent=n?`Design ${String(n.id+1).padStart(3,'0')} is ${n.distance} choice steps away. ${n.ties} alternative${n.ties===1?'':'s'} tie at that distance; showing the first by ID.`:'No other working design exists under the current rules.';$('lab-nearest').disabled=!n;
 $('lab-comparison').textContent=scenarios?.membership(d.id)||'';
}
function openWorkbench(){
 if(current!=='workshop')return;stopSearch();auto=false;syncAuto();if(selected<0)showSelection(matches[0]?.id??0,false);inspecting=true;$('toast').hidden=true;clearTimeout(toastTimer);$('lab-motion').checked=reduced;document.body.classList.add('workbench');$('detail-panel').hidden=false;
 if(machineGroup)machineGroup.visible=false;if(marker)marker.visible=false;axisLabels.forEach(x=>x.visible=false);bench?.open(models[selected]);renderWorkbench();museum?.update({...conditions(),visible:false,room:'workshop'});$('room-number').textContent='04';$('room-name').textContent='The design workbench';$('view-subheading').textContent='Separate the parts · inspect the exact rules';document.querySelector('.camera-hint').textContent='Drag to orbit · scroll or pinch to zoom · use selectors to change parts';window.dispatchEvent(new Event('resize'));resetCamera();$('close-workbench').focus();
}
function closeWorkbench(reset=true){
 inspecting=false;document.body.classList.remove('workbench');$('detail-panel').hidden=true;bench?.close();if(machineGroup)machineGroup.visible=current==='workshop';matrixDirty=true;renderDirty=true;if(marker)marker.visible=current==='workshop'&&selected>=0;syncRoom();museum?.update({...conditions(),visible:layout&&current==='workshop',room:current==='family'?'family':layout?'map':'workshop'});$('view-subheading').textContent=current==='family'?'17 illustrated points · exact queries reach the full family':layout?'Motor / horizontal · gears / depth · arm / level':'12 motors · 8 gear settings · 3 arm lengths';window.dispatchEvent(new Event('resize'));document.querySelector('.camera-hint').textContent='Drag to orbit · scroll or pinch to zoom · click a machine';if(reset){resetCamera();$('open-workbench').focus()}
}
for(const [id,max] of [['lab-m',12],['lab-g',8],['lab-a',3]]){for(let n=1;n<=max;n++)$(id).add(new Option(String(n),String(n)));$(id).onchange=()=>{const m=Number($('lab-m').value),g=Number($('lab-g').value),a=Number($('lab-a').value);showSelection(((m-1)*8+g-1)*3+a-1,false);renderDirty=true}}
$('open-workbench').onclick=openWorkbench;$('inspect-selected').onclick=openWorkbench;$('close-workbench').onclick=()=>closeWorkbench();$('explode-parts').onchange=()=>renderDirty=true;$('lab-motion').onchange=()=>{$('motion').checked=$('lab-motion').checked;$('motion').dispatchEvent(new Event('change'))};
$('lab-relax').onclick=()=>{const r=designReport.repair;if(!r)return;$('load').value=r.load;$('size').value=r.size;$('square').checked=r.square;update();museum?.update({...conditions(),visible:false,room:'workshop'});notify('Rules relaxed just enough for this design within the available sliders.')};
$('lab-nearest').onclick=()=>{if(designReport.nearest)showSelection(designReport.nearest.id,false)};
$('lab-export').onclick=()=>save('perfectpower-design-explanation.json',{schema:'pp-room-design-explanation/1',...designReport,scope:'Exact arithmetic for an invented teaching model; not physical engineering predictions.'});
function renderFamilyGuide(p){
 const e=explainFamily(T,p);$('guide-positive').textContent=T.toString();$('guide-negative').textContent=T.toString();$('guide-total').textContent=`Total: 1 + ${T} + ${T} = ${e.count}`;
 $('guide-selected').textContent=`Address ${p.rank}; ${p.chart}; t = ${p.t}. x = ${p.x}; y = ${p.y}.`;$('guide-equation').textContent=`Left side 2x² = ${e.equation.left}. Right side 3y³ = ${e.equation.right}. Both exact totals agree.`;
 const rows=T===0n?[['0',0n,'The origin']]:[['0',0n,'The origin'],['1',1n,'First positive point'],['T',T,'Last positive point'],['T + 1',T+1n,'First negative point'],['2T',2n*T,'Last negative point']];
 $('guide-addresses').replaceChildren();const groups=new Map();for(const [name,rank,meaning] of rows){const key=rank.toString();if(groups.has(key)){const entry=groups.get(key);entry.name+=' / '+name;entry.meaning+=' · '+meaning;}else groups.set(key,{name,rank,meaning})}
 for(const {name,rank,meaning} of groups.values()){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td'),button=document.createElement('button');a.textContent=name;a.title=rank.toString();b.textContent=meaning;button.textContent='Visit';button.setAttribute('aria-label','Visit family address '+name);button.onclick=()=>{familyRank=rank;$('family-rank').value=rank.toString();showFamilyPoint()};c.append(button);tr.append(a,b,c);$('guide-addresses').append(tr)}

}
$('open-family-guide').onclick=()=>{$('family-guide').showModal();renderFamilyGuide(familySelect(familyRank))};$('close-family-guide').onclick=()=>$('family-guide').close();
$('guide-small').onclick=()=>{$('bound').value='8';applyBound();familyRank=9n;$('family-rank').value='9';showFamilyPoint()};$('guide-large').onclick=()=>{$('bound').value=(10n**40n).toString();applyBound();familyRank=T+1n;$('family-rank').value=familyRank.toString();showFamilyPoint()};

function captureScene(){return current==='family'?{kind:'family',bound:T.toString(),rank:familyRank.toString()}:{kind:'workshop',rules:conditions(),objective:$('objective').value,layout,selected,hiddenRejected}}
function restoreScene(s){auto=false;syncAuto();if(s.kind==='family'){T=BigInt(s.bound);familyRank=BigInt(s.rank);$('bound').value=s.bound;$('family-rank').value=s.rank;setExhibit('family');showFamilyPoint()}else{$('load').value=s.rules.load;$('size').value=s.rules.size;$('square').checked=s.rules.square;$('objective').value=s.objective;$('objective').dispatchEvent(new Event('change'));hiddenRejected=s.hiddenRejected;$('hide-rejected').checked=hiddenRejected;selected=-1;setExhibit('workshop');update();setLayout(s.layout);if(s.selected>=0)showSelection(s.selected,false)}$('tour').hidden=true;$('tour-toggle').textContent='Show tour';resetCamera()}
scenarios=createScenarios({models,getScene:captureScene,restore:restoreScene,onChange:()=>{matrixDirty=true;refreshColors()},save,notify});

function syncRoom(){const family=current==='family';$('map-tab').classList.toggle('active',!family&&layout);$('map-tab').setAttribute('aria-pressed',String(!family&&layout));$('workshop-tab').classList.toggle('active',!family&&!layout);$('workshop-tab').setAttribute('aria-pressed',String(!family&&!layout));$('room-number').textContent=family?'03':layout?'02':'01';$('room-name').textContent=family?'The exact family':layout?'The constraint atlas':'The search hall';$('map-key').hidden=family||!layout;}
function updateWaterfall(){const c=conditions(),lift=models.filter(d=>d.drive>=c.load*d.a),size=lift.filter(d=>d.size<=c.size),sq=size.filter(d=>!c.square||Number.isInteger(Math.sqrt(d.drive)));$('flow-lift').textContent=lift.length;$('flow-size').textContent=size.length;$('flow-square').textContent=sq.length;}
const presets={compact:{load:6,size:8,square:false},heavy:{load:24,size:15,square:false},square:{load:12,size:10,square:true},empty:{load:48,size:3,square:false}};
function applyPreset(name){let p=presets[name];$('load').value=p.load;$('size').value=p.size;$('square').checked=p.square;update();document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===name)));}
function cubeRoot(n){let lo=0n,hi=1n<<BigInt(Math.ceil(n.toString(2).length/3)+1);while(lo+1n<hi){const mid=(lo+hi)/2n;if(mid*mid*mid<=n)lo=mid;else hi=mid}return lo}
function locatePoint(){try{const parse=id=>{const raw=$(id).value.trim();if(!/^-?\d{1,183}$/.test(raw))throw Error('Enter integer coordinates, up to 183 digits.');return BigInt(raw)};const x=parse('inverse-x'),y=parse('inverse-y');let rank;if(x===0n&&y===0n)rank=0n;else{const abs=x<0n?-x:x;if(abs%18n!==0n)throw Error('This point is not in the equation family.');const t=cubeRoot(abs/18n);if(t===0n||18n*t*t*t!==abs||6n*t*t!==y)throw Error('This point is not in the equation family.');if(t>T)throw Error('This point is outside the current parameter ceiling.');rank=x>0n?t:T+t;}familyRank=rank;$('family-rank').value=rank.toString();showFamilyPoint();$('inverse-result').textContent='Address '+rank.toString();notify('Recovered the exact address.')}catch(e){$('inverse-result').textContent=e.message;notify(e.message)}}
function sampleRank(){const N=2n*T+1n,bits=N.toString(2).length,bytes=Math.ceil(bits/8),mask=(1n<<BigInt(bits))-1n;let rank;do{const arr=new Uint8Array(bytes);crypto.getRandomValues(arr);rank=0n;for(const b of arr)rank=(rank<<8n)+BigInt(b);rank&=mask;}while(rank>=N);familyRank=rank;$('family-rank').value=rank.toString();showFamilyPoint();notify('Selected a random address in the complete collection.');}
function speak(text){if(!('speechSynthesis' in window))return;const voice=speechSynthesis.getVoices().find(v=>v.localService&&v.lang.startsWith('en'));if(!voice){notify('No local English voice is available. The tour text remains on screen.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.voice=voice;u.rate=.94;speechSynthesis.speak(u);}
$('map-tab').onclick=()=>{setExhibit('workshop');setLayout(true)};
for(const b of document.querySelectorAll('[data-preset]'))b.onclick=()=>applyPreset(b.dataset.preset);
$('hide-rejected').onchange=()=>{hiddenRejected=$('hide-rejected').checked;matrixDirty=true;renderDirty=true};
$('objective').onchange=()=>{$('best').textContent=$('objective').value==='lift'?'Highest lift':$('objective').value==='size'?'Smallest size':'Least cost'};
$('inverse-find').onclick=locatePoint;$('random-point').onclick=sampleRank;
$('presentation').onclick=()=>{presentation=!presentation;document.body.classList.toggle('presentation',presentation);$('presentation').setAttribute('aria-pressed',String(presentation));$('presentation').textContent=presentation?'Show controls':'Presentation';window.dispatchEvent(new Event('resize'));resetCamera()};
$('narration').onclick=()=>{narrating=!narrating;$('narration').setAttribute('aria-pressed',String(narrating));$('narration').textContent=narrating?'Narration on':'Narration';if(narrating)speak(chapters[step][0]+' '+$('tour-text').textContent);else if('speechSynthesis' in window)speechSynthesis.cancel()};
$('eye-level').onclick=()=>{const offset=current==='family'?ROOM.family:layout?ROOM.map:0;moveCamera(new THREE.Vector3(offset+17,5,21),new THREE.Vector3(offset,2,0),2.6)};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&inspecting)closeWorkbench();else if(e.key==='Escape'&&presentation)$('presentation').click()});
function box(w,h,d){return new THREE.BoxGeometry(w,h,d)}
function addPart(geometry,metal,transform,group){const material=new THREE.MeshStandardMaterial({color:'#ffffff',metalness:metal?.8:.35,roughness:metal?.26:.5});const mesh=new THREE.InstancedMesh(geometry,material,288);mesh.userData.metal=metal;mesh.userData.transform=transform;mesh.castShadow=false;mesh.receiveShadow=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;parts.push(mesh);group.add(mesh);return mesh}
function cylinderBetween(start,end,radius,material){let length=start.distanceTo(end),geo=new THREE.CylinderGeometry(radius,radius,length,12);let mesh=new THREE.Mesh(geo,material);mesh.position.copy(start).add(end).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),end.clone().sub(start).normalize());return mesh}
function label(text,position,size=2.5,color='#adc1c8'){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.font='500 36px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const wall=text==='THE ROOM OF POSSIBILITIES'||text==='DEFINED CHOICES. COMPLETE COLLECTIONS.';const sprite=wall?new THREE.Mesh(new THREE.PlaneGeometry(size,size/4),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false})):new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));sprite.position.copy(position);if(!wall)sprite.scale.set(size,size/4,1);return sprite}
let familyMarker,axisLabels=[];
function initialize(){scene=new THREE.Scene();scene.background=new THREE.Color('#0b1821');scene.fog=new THREE.FogExp2('#0b1821',.014);camera=new THREE.PerspectiveCamera(43,1,.1,250);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.domElement.setAttribute('aria-label','3D machines: drag to orbit, scroll to zoom. A text view is available below.');renderer.domElement.setAttribute('tabindex','0');$('stage').appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=4;controls.maxDistance=105;controls.maxPolarAngle=Math.PI*.49;controls.addEventListener('start',()=>transition=null);controls.addEventListener('change',()=>renderDirty=true);camera.position.set(32,30,38);controls.target.set(0,0,0);controls.update();scene.add(new THREE.HemisphereLight('#bfdae4','#253132',2));const light=new THREE.DirectionalLight('#f9dfb0',3.4);light.position.set(-10,25,12);scene.add(light);const rim=new THREE.DirectionalLight('#6ebcca',2.5);rim.position.set(12,8,-16);scene.add(rim);
 museum=createMuseum(scene,renderer);
 machineGroup=new THREE.Group();scene.add(machineGroup);for(let d of models){let row=Math.floor(d.id/18),col=d.id%18;items.push({position:new THREE.Vector3((col-8.5)*2.04,0,(row-7.5)*2.05)});}
 addPart(roundedBlock(1.42,.12,1.34,.09),true,()=>({p:[0,.08,0],s:[1,1,1]}),machineGroup);
 addPart(roundedBlock(.72,.36,.65,.08),false,d=>({p:[-.21,.32,0],s:[.75+d.m/28,1,1]}),machineGroup);
 addPart(new THREE.CylinderGeometry(.21,.21,.59,16),true,d=>({p:[-.31,.62,0],r:[Math.PI/2,0,0],s:[1+d.m/25,1,1+d.m/25]}),machineGroup);
 addPart(box(.12,.8,.12),true,d=>({p:[.3,.63,0],s:[1,1+(d.a-1)*.24,1]}),machineGroup);
 addPart(box(.85,.10,.13),true,d=>({p:[.58,1.01+(d.a-1)*.1,0],r:[0,0,-.15],s:[.70+d.a*.17,1,1]}),machineGroup);
 addPart(gearGeometry(),true,d=>({p:[.22,.61,.39],r:[0,0,0],s:[.78+d.g*.06,.78+d.g*.06,1]}),machineGroup).userData.rotor=true;
 addPart(new THREE.TorusGeometry(.235,.025,6,24),true,d=>({p:[-.3,.62,.36],s:[1+d.m/25,1+d.m/25,1]}),machineGroup);
 addPart(box(.027,.36,.05),false,d=>({p:[-.3,.62,.37],s:[1,1+d.m/25,1]}),machineGroup).userData.rotor=true;
 addPart(new THREE.CylinderGeometry(.024,.024,.48,8),true,d=>({p:[-.3,.62,0],r:[Math.PI/2,0,0],s:[1,1,1]}),machineGroup);
 const spokes=addPart(box(.035,.31,.08),false,d=>({p:[.22,.61,.44],r:[0,0,0],s:[1,1,1]}),machineGroup);spokes.userData.rotor=true;
 addPart(box(.035,.48,.035),true,d=>({p:[.88, .74+(d.a-1)*.1,0],s:[1,1,1]}),machineGroup);
 addPart(box(.25,.24,.25),false,d=>({p:[.88,.47+(d.a-1)*.1,0],s:[1,1,1]}),machineGroup);
 const ringGeo=new THREE.TorusGeometry(.83,.022,6,48);marker=new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({color:'#f2c680'}));marker.rotation.x=Math.PI/2;marker.visible=false;scene.add(marker);scanRing=new THREE.Mesh(new THREE.TorusGeometry(.94,.035,6,40),new THREE.MeshBasicMaterial({color:'#f2c680'}));scanRing.rotation.x=Math.PI/2;scanRing.visible=false;scene.add(scanRing);
 axisLabels=[label('MOTOR CHOICE',new THREE.Vector3(0,.4,12),8),label('ARM LEVEL',new THREE.Vector3(-12,5,1),5),label('GEAR CHOICE',new THREE.Vector3(12,.4,-2),6)];axisLabels.forEach(s=>{s.visible=false;s.userData.baseX=s.position.x;machineGroup.add(s)});
 familyGroup=new THREE.Group();familyGroup.position.x=ROOM.family;scene.add(familyGroup);familyGroup.visible=false;const branchMat=new THREE.LineBasicMaterial({color:'#adb9ff'});const ballMat=new THREE.MeshStandardMaterial({color:'#81d9c4',emissive:'#1c413c',emissiveIntensity:.3,metalness:.45,roughness:.25});for(let sign of [-1,1]){const pts=[new THREE.Vector3(0,.16,-2)];for(let t=1;t<=8;t++)pts.push(new THREE.Vector3(sign*(1.5+t*.65),.16+t*.65,-2+t*.45));const curve=new THREE.CatmullRomCurve3(pts);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(80)),branchMat);familyGroup.add(line);for(let t=1;t<=8;t++){const pos=pts[t],ball=new THREE.Mesh(new THREE.SphereGeometry(.23,20,14),ballMat.clone());ball.position.copy(pos);ball.userData.familyT=t;ball.userData.sign=sign;familyGroup.add(ball);familyGroup.add(label(`${sign>0?'+':'−'}18·${t}³`,pos.clone().add(new THREE.Vector3(sign*.75,.3,0)),1.8));}}
 const zero=new THREE.Mesh(new THREE.SphereGeometry(.23,18,12),new THREE.MeshStandardMaterial({color:'#e9bd75',emissive:'#5b452c',emissiveIntensity:.2}));zero.position.set(0,.16,-2);zero.userData.familyT=0;zero.userData.sign=1;familyGroup.add(zero);familyGroup.add(label('(0, 0)',new THREE.Vector3(0,.9,-2),2));familyGroup.add(label('NEGATIVE x CHART',new THREE.Vector3(-6,6.8,1),6));familyGroup.add(label('POSITIVE x CHART',new THREE.Vector3(6,6.8,1),6));familyMarker=new THREE.Mesh(new THREE.TorusGeometry(.32,.025,6,40),new THREE.MeshBasicMaterial({color:'#f2c680'}));familyMarker.rotation.x=Math.PI/2;familyGroup.add(familyMarker);
 let down;renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);if(current==='workshop'&&!inspecting){let hits=ray.intersectObjects(parts,false);if(hits.length)showSelection(hits[0].instanceId)}else if(current==='family'){let hits=ray.intersectObjects(familyGroup.children,false).filter(h=>h.object.userData.familyT!==undefined);if(hits.length){let d=hits[0].object.userData,t=BigInt(d.familyT);if(t>T){notify('This illustrated point is outside your current bound.');return}familyRank=t===0n?0n:d.sign>0?t:T+t;$('family-rank').value=familyRank.toString();showFamilyPoint()}}});
 renderer.domElement.addEventListener('keydown',e=>{if(e.key==='Home')resetCamera();if(current==='workshop'&&e.key==='ArrowRight'){e.preventDefault();another()}});
 bench=createWorkbench(scene,parts);
 const resize=()=>{renderDirty=true;let w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;if(inspecting){if(w>700)camera.setViewOffset(w,h,210,0,w,h);else camera.clearViewOffset();}else if(w>700&&!presentation)camera.setViewOffset(w,h,-145,0,w,h);else camera.clearViewOffset();camera.updateProjectionMatrix()};new ResizeObserver(resize).observe($('stage'));window.addEventListener('resize',resize);resize();$('loading').hidden=true;window.__atlasState.ready=true;update();showFamilyPoint();tourStep(0);requestAnimationFrame(frame);
}
function frame(now){let dt=Math.min((now-last)/1000,1);last=now;const benchMoving=inspecting&&bench?bench.frame(now,dt,$('explode-parts').checked,reduced):false;let speed=reduced?1:1-Math.exp(-dt*4.5),moving=false;models.forEach(d=>{let p=items[d.id].position,target=layout?new THREE.Vector3(ROOM.map+(d.m-6.5)*1.65,(d.a-1)*2.7,(d.g-4.5)*2.8):new THREE.Vector3((d.id%18-8.5)*2.04,0,(Math.floor(d.id/18)-7.5)*2.05);if(p.distanceToSquared(target)>1e-6)moving=true;p.lerp(target,speed)});if(current==='workshop'&&!inspecting){for(let part of parts){if(!matrixDirty&&!moving&&(!part.userData.rotor||reduced))continue;for(let d of models){let local=part.userData.transform(d),p=items[d.id].position;dummy.position.set(p.x+local.p[0],p.y+local.p[1],p.z+local.p[2]);dummy.rotation.set(...(local.r||[0,0,0]));if(part.userData.rotor)dummy.rotation.z=reduced?0:now*.0006*(1+d.g*.08);dummy.scale.set(...local.s);if(hiddenRejected&&(scenarios?.includes(d.id)===null?reasons(d).length:!scenarios.includes(d.id)))dummy.scale.setScalar(0);dummy.updateMatrix();part.setMatrixAt(d.id,dummy.matrix)}part.instanceMatrix.needsUpdate=true}matrixDirty=false;axisLabels.forEach(s=>{s.visible=layout;s.position.x=s.userData.baseX+ROOM.map;});if(marker.visible&&selected>=0){marker.position.copy(items[selected].position);marker.position.y+=.045;}if(searching){let n=Math.min(288,Math.floor((now-searchStart)/65)+1);while(checked<n&&searching){checked++;$('search-count').textContent=String(checked);$('search-progress').value=checked;let d=models[checked-1];scanRing.visible=true;scanRing.position.copy(items[d.id].position);scanRing.position.y+=.06;if(!reasons(d).length)finishSearch(d.id,checked);else if(checked===288)finishSearch(-1,288)}}}if(transition){let x=Math.min(1,(now-transition.start)/transition.duration),f=x*x*(3-2*x);camera.position.lerpVectors(transition.p0,transition.p1,f);controls.target.lerpVectors(transition.t0,transition.t1,f);if(x===1)transition=null}const cameraChanged=controls.update();if(renderDirty||benchMoving||moving||transition||searching||cameraChanged||(!reduced&&current==='workshop')){renderer.render(scene,camera);renderDirty=false;}if(auto&&now-autoTime>10500){if(step<chapters.length-1)tourStep(step+1);else{auto=false;syncAuto();$('tour').hidden=true;$('tour-toggle').textContent='Show tour'}}requestAnimationFrame(frame)}
try{initialize()}catch(e){$('loading').hidden=true;$('stage').innerHTML='<div class="fallback"><h2>Your browser could not open the 3D view.</h2><p>The collection controls and text view still work. Try a browser with WebGL 2 enabled for the gallery.</p></div>';window.__atlasState.error=e.message;console.error(e);update();showFamilyPoint()}

const exactNotebook=createComparisonNotebook(source,(ceiling,rank)=>{setExhibit('family');T=ceiling;familyRank=rank;$('bound').value=T.toString();$('family-rank').value=rank.toString();showFamilyPoint()});
window.__atlasState.exactComparison=exactNotebook.state;

// Check the exhibit's rank convention against every exported repository example.
for(const row of source.rank_examples){const r=BigInt(row.rank),p=familySelect(r);if(p.x.toString()!==row.values.x||p.y.toString()!==row.values.y)throw new Error('Source chart order disagrees with exhibit.');}
for(const row of source.small_population){const t=BigInt(row.parameter),x=BigInt(row.values.x),y=BigInt(row.values.y);if((x<0n?-x:x)!==18n*t*t*t||y!==6n*t*t)throw new Error('Illustrated point disagrees with source export.');}
