const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=__dirname;let checks=0;const check=(a,b)=>{assert.deepEqual(a,b);checks++};
const allowed=(d,c)=>Math.floor(d.m*d.g/d.a)>=c.load&&d.m+d.g+d.a<=c.size&&(!c.square||[1,4,9,16,25,36,49,64,81].includes(d.m*d.g));
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH||(fs.existsSync(root+'/../browser-runtime/chromium')?root+'/../browser-runtime/chromium':undefined),args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-zygote'],env:{...process.env,LD_LIBRARY_PATH:process.env.BROWSER_LIBRARY_PATH||root+'/../browser-runtime',FONTCONFIG_PATH:'/etc/fonts'}});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});
 await page.goto('file://'+root+'/PerfectPower-Room-of-Possibilities.html');await page.waitForFunction(()=>window.__atlasState?.ready);await page.check('#motion');
 for(const c of [{load:12,size:10,square:false},{load:12,size:10,square:true},{load:48,size:3,square:false},{load:24,size:15,square:false}]){
  await page.evaluate(c=>{for(const k of ['load','size'])document.getElementById(k).value=c[k];document.getElementById('square').checked=c.square;document.getElementById('load').dispatchEvent(new Event('input'))},c);
  const reports=await page.evaluate(()=>window.__atlasState.models.map(d=>window.__atlasState.explain(d.id)));check(reports.length,288);check(reports.every(r=>r.passes===allowed(r.design,c)),true);
  check(reports.every(r=>!r.repair||(r.repair.load>=1&&r.repair.load<=48&&r.repair.size>=3&&r.repair.size<=15&&allowed(r.design,r.repair))),true);
  check(reports.every(r=>{const q=r.repair;if(!q)return true;return(q.load===c.load||!allowed(r.design,{...q,load:q.load+1}))&&(q.size===c.size||!allowed(r.design,{...q,size:q.size-1}))&&(q.square===c.square||!allowed(r.design,{...q,square:true}))}),true);
  check(reports.every(r=>{const choices=reports.map(x=>x.design).filter(d=>d.id!==r.design.id&&allowed(d,c));if(!choices.length)return r.nearest===null;const dist=d=>Math.abs(d.m-r.design.m)+Math.abs(d.g-r.design.g)+Math.abs(d.a-r.design.a),minimum=Math.min(...choices.map(dist)),best=choices.filter(d=>dist(d)===minimum);return r.nearest.distance===minimum&&r.nearest.id===best[0].id&&r.nearest.ties===best.length}),true);
 }
 await page.click('[data-preset=square]');await page.click('#best');await page.click('#inspect-selected');check(await page.locator('#detail-panel').isVisible(),true);check((await page.evaluate(()=>window.__atlasState.detail())).report.design.id,81);check((await page.evaluate(()=>window.__atlasState.detail())).components,12);check(await page.locator('.sidebar').isVisible(),false);check(await page.locator('#lab-relax').isDisabled(),true);
 await page.waitForFunction(()=>window.__atlasState.detail().explode>.99);await page.screenshot({path:root+'/workbench.png'});
 await page.uncheck('#explode-parts');await page.waitForFunction(()=>window.__atlasState.detail().explode<.01);check((await page.evaluate(()=>window.__atlasState.detail())).report.passes,true);await page.check('#explode-parts');
 await page.selectOption('#lab-m','1');await page.selectOption('#lab-g','1');await page.selectOption('#lab-a','3');check(await page.locator('#lab-relax').isDisabled(),true);check((await page.evaluate(()=>window.__atlasState.detail())).report.repair,null);check((await page.evaluate(()=>window.__atlasState.detail())).report.passes,false);
 await page.selectOption('#lab-m','12');await page.selectOption('#lab-g','8');check(await page.locator('#lab-relax').isDisabled(),true);check((await page.evaluate(()=>window.__atlasState.detail())).report.design.size,23);
 await page.selectOption('#lab-m','3');await page.selectOption('#lab-g','5');await page.selectOption('#lab-a','1');const before=await page.evaluate(()=>window.__atlasState.detail().report);check(before.passes,false);check(before.repair,{load:12,size:10,square:false});await page.click('#lab-relax');check((await page.evaluate(()=>window.__atlasState.detail())).report.passes,true);check((await page.evaluate(()=>window.__atlasState.query())).conditions,before.repair);
 const download=page.waitForEvent('download');await page.click('#lab-export');const dl=await download,data=JSON.parse(fs.readFileSync(await dl.path()));check(data.design,{id:60,m:3,g:5,a:1,cost:43,size:9,drive:15});check(data.passes,true);
 const nearest=await page.evaluate(()=>window.__atlasState.detail().report.nearest.id);await page.click('#lab-nearest');check((await page.evaluate(()=>window.__atlasState.query())).selected,nearest);
 await page.uncheck('#lab-motion');await page.uncheck('#explode-parts');await page.waitForFunction(()=>window.__atlasState.detail().explode<.01);await page.check('#explode-parts');await page.waitForFunction(()=>window.__atlasState.detail().explode>.99);await page.check('#lab-motion');
 for(const width of [1100,700,390]){await page.setViewportSize({width,height:900});await page.click('#reset-camera');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);check(await page.evaluate(()=>{const p=document.getElementById('detail-panel').getBoundingClientRect();return p.left>=0&&p.right<=innerWidth}),true)}await page.waitForTimeout(800);await page.screenshot({path:root+'/mobile-workbench.png',fullPage:true});
 await page.keyboard.press('Escape');check((await page.evaluate(()=>window.__atlasState.query())).inspecting,false);check(await page.locator('.sidebar').isVisible(),true);await page.setViewportSize({width:1440,height:1000});await page.click('#family-tab');await page.click('#open-family-guide');check(await page.locator('#family-guide').isVisible(),true);
 await page.click('#guide-small');check((await page.evaluate(()=>window.__atlasState.family)).count,'17');check(await page.locator('#guide-addresses tr').count(),5);
 await page.getByRole('button',{name:'Visit family address 2T',exact:true}).click();check((await page.evaluate(()=>window.__atlasState.family)).x,'-9216');check((await page.evaluate(()=>window.__atlasState.family)).y,'384');let e=await page.evaluate(()=>window.__atlasState.familyExplanation());check(e.equation.left,(2n*9216n**2n).toString());check(e.equation.left,e.equation.right);
 await page.getByRole('button',{name:'Visit family address 0',exact:true}).click();check((await page.evaluate(()=>window.__atlasState.familyExplanation())).equation.left,'0');await page.click('#guide-large');check((await page.evaluate(()=>window.__atlasState.family)).rank,(10n**40n+1n).toString());check((await page.evaluate(()=>window.__atlasState.family)).x,'-18');await page.screenshot({path:root+'/family-guide.png'});
 await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);check(await page.locator('#guide-selected').isVisible(),true);await page.keyboard.press('Escape');check(await page.locator('#family-guide').isVisible(),false);
 await page.fill('#bound','0');await page.click('#apply-bound');await page.click('#open-family-guide');check(await page.locator('#guide-addresses tr').count(),1);check(await page.locator('#guide-positive').textContent(),'0');check(await page.locator('#guide-negative').textContent(),'0');await page.click('#close-family-guide');
 await page.fill('#bound','1');await page.click('#apply-bound');await page.click('#open-family-guide');check(await page.locator('#guide-addresses tr').count(),3);check(await page.locator('#guide-addresses tr').nth(1).locator('td').first().textContent(),'1 / T');check(await page.locator('#guide-addresses tr').nth(2).locator('td').first().textContent(),'T + 1 / 2T');await page.getByRole('button',{name:'Visit family address T + 1 / 2T',exact:true}).click();check((await page.evaluate(()=>window.__atlasState.family)).x,'-18');await page.click('#close-family-guide');
 check(errors,[]);check(external,[]);await browser.close();fs.writeFileSync(root+'/detail-checks.json',JSON.stringify({checks,result:'passed',bundle_sha256:require('crypto').createHash('sha256').update(fs.readFileSync(root+'/PerfectPower-Room-of-Possibilities.html')).digest('hex'),page_errors:errors,external_requests:external,covered_designs:288,rule_sets:4,coverage:'Workbench formulas, coordinate-wise minimal repairs, nearest alternatives, animation, mobile layout, exact family boundaries and arithmetic.'},null,2));console.log(JSON.stringify({checks,result:'passed'}));
})().catch(e=>{console.error(e);process.exit(1)});
