'use client';
import {useMemo,useState} from 'react';
import {Download,Play} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {integerInput} from '@/lib/dresden-math';
import {exportJson} from '@/lib/dresden-research';
import {polynomialCalendar,polynomialPresets} from '@/lib/dresden-polynomial';
import proof from '@/lib/data/lean_proof_status.json';

type Props={residue:bigint|null;period:bigint|null;lo:string;hi:string;onCalendar:(day:string)=>void};
export default function PolynomialExplorer({residue,period,lo,hi,onCalendar}:Props){
 const [preset,setPreset]=useState('0'),[draft,setDraft]=useState(JSON.stringify(polynomialPresets[0].predicate,null,2)),[submitted,setSubmitted]=useState(draft),[rank,setRank]=useState('0'),[focus,setFocus]=useState('accepted');
 const output=useMemo(()=>{try{if(residue===null||period===null)throw Error('Choose compatible calendar phases above before applying a polynomial condition');if(submitted.length>20000)throw Error('Predicate text exceeds the supported size');return {result:polynomialCalendar(JSON.parse(submitted),residue,period,integerInput(lo),integerInput(hi),integerInput(rank)),error:''};}catch(e){return {result:null,error:(e as Error).message};}},[submitted,residue,period,lo,hi,rank]);
 const r=output.result;let left=0n,right=1n;try{left=integerInput(lo);right=integerInput(hi);}catch{}
 if(focus==='accepted'&&r?.dayIntervals.length){left=r.dayIntervals[0].first;right=r.dayIntervals.at(-1)!.last;}
 const X=(n:bigint)=>40+Number((n-left)*1000000n/(right-left||1n))*720/1000000;
 const choose=(i:string)=>{const text=JSON.stringify(polynomialPresets[Number(i)].predicate,null,2);setPreset(i);setDraft(text);setSubmitted(text);setRank('0');};
 return <article className="panel polynomial-explorer"><div className="section-head"><div><span className="eyebrow">Polynomial conditions / original day coordinates</span><h2>Restrict the calendar population</h2></div><span className="badge">Exact integer arithmetic</span></div><p>Apply a polynomial condition to the matching days from the calendar query above. Coefficients are in ascending order: [−9, 0, 1] means day² − 9. Large coefficients must be quoted decimal strings. The browser supports degree eight, sixteen atoms and a bounded root subdivision budget.</p>
 <div className="lab-grid"><div><label className="input-label" id="polynomial-preset-label">Starting condition</label><Select value={preset} onValueChange={choose}><SelectTrigger className="research-select" aria-labelledby="polynomial-preset-label"><SelectValue/></SelectTrigger><SelectContent className="research-select-menu">{polynomialPresets.map((p,i)=><SelectItem key={i} value={String(i)}>{p.label}</SelectItem>)}</SelectContent></Select></div><div><label className="input-label" htmlFor="restricted-rank">Rank within the restricted population</label><input id="restricted-rank" className="number-input" value={rank} inputMode="numeric" onChange={e=>setRank(e.target.value)}/></div><div><label className="input-label" id="polynomial-focus-label">Diagram extent</label><Select value={focus} onValueChange={setFocus}><SelectTrigger className="research-select" aria-labelledby="polynomial-focus-label"><SelectValue/></SelectTrigger><SelectContent className="research-select-menu"><SelectItem value="accepted">Focus on accepted days</SelectItem><SelectItem value="window">Entire query window</SelectItem></SelectContent></Select></div></div>
 <label className="input-label" htmlFor="polynomial-predicate">Original-day polynomial predicate</label><textarea id="polynomial-predicate" className="predicate-editor mono" rows={9} spellCheck={false} value={draft} onChange={e=>setDraft(e.target.value)}/><div className="lab-actions"><button className="download" onClick={()=>setSubmitted(draft)}><Play size={15}/>Apply condition</button>{draft!==submitted&&<span className="note">Edited condition has not been applied.</span>}</div>
 {output.error?<p className="error" role="alert">{output.error}</p>:r&&<><div className="research-results"><div className="research-result"><span>Restricted matching days</span><strong className="mono wrap">{r.count.toString()}</strong></div><div className="research-result"><span>Accepted progression ranges</span><strong>{r.dayIntervals.length}</strong></div><div className="research-result"><span>Selected original day</span><strong className="mono wrap">{r.selected?.toString()??'Rank outside population'}</strong></div><div className="research-result"><span>Root subdivision nodes</span><strong>{r.rootNodes}</strong></div></div>
 <div className="polynomial-strip"><svg viewBox="0 0 800 116" role="img" aria-label="Accepted calendar progression ranges within the selected diagram extent"><title>Accepted calendar progression ranges</title><line x1="40" x2="760" y1="42" y2="42" stroke="#354654" strokeWidth="20"/>{r.dayIntervals.map((v,i)=><g key={i}><rect x={X(v.first)} y="32" width={Math.max(1,X(v.last)-X(v.first))} height="20" rx="3" fill="#65b7b4"/><text x={(X(v.first)+X(v.last))/2} y="25" textAnchor="middle" fill="#c4dbd9" fontSize="11">{i+1}</text></g>)}{r.selected!==null&&r.selected>=left&&r.selected<=right&&<path d={`M ${X(r.selected)-5} 64 L ${X(r.selected)} 55 L ${X(r.selected)+5} 64 Z`} fill="#dfac7e"/>}<text x="40" y="91" fill="#9aabba" fontSize="11">{left.toString()}</text><text x="760" y="109" textAnchor="end" fill="#9aabba" fontSize="11">{right.toString()}</text></svg></div><p className="note">Bands show ranges of a progression, with {period?.toString()} days between adjacent accepted dates. Exact endpoints and counts appear below; pixel positions are rounded. Orange marks the selected day.</p>
 <div className="lab-actions"><button className="download" disabled={r.selected===null} onClick={()=>r.selected!==null&&onCalendar(r.selected.toString())}>Show restricted selection on the rings</button><button className="download" onClick={()=>exportJson('dresden-polynomial-calendar.json',r)}><Download size={15}/>Export conditions and root transcript</button></div>
 <div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Range</TableHead><TableHead>Parameter k / inclusive</TableHead><TableHead>First original day</TableHead><TableHead>Last original day</TableHead><TableHead>Exact count</TableHead></TableRow></TableHeader><TableBody>{r.dayIntervals.map((v,i)=><TableRow key={i}><TableCell>{i+1}</TableCell><TableCell className="mono wrap">{r.parameterIntervals[i].map(String).join(' → ')}</TableCell><TableCell className="mono wrap">{v.first.toString()}</TableCell><TableCell className="mono wrap">{v.last.toString()}</TableCell><TableCell className="mono wrap">{v.count.toString()}</TableCell></TableRow>)}</TableBody></Table></div>{!r.dayIntervals.length&&<p className="alert">The calendar and polynomial constraints have no matching day in this window.</p>}
 <details className="polynomial-transport"><summary>Inspect the transformed polynomial coefficients</summary><p>Each polynomial is evaluated after substituting day = {r.chart.residue.toString()} + {r.chart.period.toString()} × k. The original-day condition is retained in the export.</p>{r.transportedAtoms.map((a,i)=><p key={i} className="mono wrap">Atom {i+1}: [{a.poly.map(String).join(', ')}] {a.relation} 0</p>)}</details></>}
 <div className="proof-status"><span className="eyebrow">Proof scope / {proof.toolchain}</span><h3>The coordinate bridge is kernel checked</h3><p>The Lean theorems preserve polynomial comparisons and Boolean combinations, map bounded parameter sets to original days without duplicates, and preserve count and rank. The browser root solver and JSON parser are tested implementations; general Sturm completeness and end-to-end interpreter verification remain open.</p><div className="lab-actions"><a className="download" href="/sources/DresdenCalendar.lean" download="DresdenCalendar.lean">Read the Lean source</a><a className="download" href="/sources/dresden-lean-axioms.log" download="dresden-lean-axioms.log">Read the kernel audit</a></div></div>
 </article>;
}
