"""Emit a self-contained Lean theorem 'the hit set of F(n) = m^d is exactly H' (Runge branch).

The emitted proof uses only `runge_pointwise`, `not_isHit_between`, `not_isHit_neg` from the
compiled kernel plus `ring`/`positivity`/`norm_num`.  Python chooses the data (threshold x0, the
t-range T, Taylor-shifted polynomials); Lean re-checks every identity and inequality, so a
compiled generated file is a machine-checked proof that trusts nothing in this module.

Strategy for n >= x0 (write n = x0 + k, k >= 0):
  * P(x0 + k), (T+1) P^(d-1) -+ R', and for odd d P^d -+ R' are polynomials in k with
    nonnegative coefficients and positive constant term (checked here, re-proved by positivity);
  * runge_pointwise then gives D^d F(n) = (P(n) + t)^d with |t| <= T;
  * for each such t, G_t(x0 + k) has all coefficients of one strict sign, a contradiction.
For 1 <= n < x0 every value is decided individually (hit witness, or strictly between
consecutive d-th powers, or negative for even d).
"""
from __future__ import annotations

from fractions import Fraction

from .core import floor_nth_root, integer_power_root, normalize, power, rigid_certificate
from .polyalg import add, compose_linear, scale, subtract

Z = Fraction


def _ints(p) -> list[int]:
    return [int(c) for c in p]


def _shift(p, x0: int):
    return compose_linear(p, x0, 1)            # p(x0 + k)


def _definite(p) -> int:
    """+1 if all coefficients >= 0 with constant > 0; -1 for the mirror image; 0 otherwise."""
    c = list(p)
    if c[0] > 0 and all(x >= 0 for x in c):
        return 1
    if c[0] < 0 and all(x <= 0 for x in c):
        return -1
    return 0


def _expr(p, var: str) -> str:
    """Lean integer expression for a polynomial with integer coefficients in `var`."""
    terms = []
    for i, c in enumerate(p):
        c = int(c)
        if c == 0:
            continue
        mono = '' if i == 0 else (var if i == 1 else f'{var} ^ {i}')
        if i == 0:
            terms.append(f'({c})')
        elif c == 1:
            terms.append(mono)
        else:
            terms.append(f'({c}) * {mono}')
    return ' + '.join(terms) if terms else '0'


def plan(coefficients, d: int, T_max: int = 3, x0_max: int = 300):
    """Choose (x0, T) and all shifted polynomials; None if no plan within the limits."""
    cert = rigid_certificate(coefficients, d)
    if cert is None or cert.exact_identity:
        return None
    F = normalize(coefficients)
    if F[-1] <= 0:
        return None
    D = cert.denominator
    P = normalize(cert.root_numerators)
    if P[-1] < 0:                                   # use the positive root branch
        P = scale(P, -1)
    Rp = subtract(scale(F, D ** d), power(P, d))    # R' = D^d F - P^d
    for x0 in range(1, x0_max + 1):
        Ps = _shift(P, x0)
        if _definite(Ps) != 1:
            continue
        side = []
        if d % 2:
            side += [subtract(power(P, d), Rp), add(power(P, d), Rp)]
        for T in range(0, T_max + 1):
            bound = scale(power(P, d - 1), T + 1)
            conds = side + [subtract(bound, Rp), add(bound, Rp)]
            shifted = [_shift(c, x0) for c in conds]
            if any(_definite(s) != 1 for s in shifted):
                continue
            Gs = {}
            ok = True
            for t in range(-T, T + 1):
                G = subtract(scale(F, D ** d), power(add(P, (Z(t),)), d))
                Gsh = _shift(G, x0)
                sgn = _definite(Gsh)
                if sgn == 0:
                    ok = False
                    break
                Gs[t] = (G, Gsh, sgn)
            if ok:
                return dict(F=F, d=d, D=D, P=P, Rp=Rp, x0=x0, T=T, Ps=Ps,
                            conds=list(zip(conds, shifted)), Gs=Gs)
    return None


def emit(name: str, coefficients, d: int, **kw) -> str | None:
    pl = plan(coefficients, d, **kw)
    if pl is None:
        return None
    F, D, P, x0, T = pl['F'], pl['D'], pl['P'], pl['x0'], pl['T']
    fi = _ints(F)
    hits = []
    cases = []
    for n in range(1, x0):
        v = sum(c * n ** i for i, c in enumerate(fi))
        m = integer_power_root(v, d)
        if m is not None:
            hits.append((n, m))
            cases.append('    · simp')
        elif v < 0 and d % 2 == 0:
            cases.append('    · exact absurd h (not_isHit_neg (by decide) (by norm_num))')
        else:
            a = floor_nth_root(abs(v), d)
            cases.append(f'    · exact absurd h (not_isHit_between (a := {a}) (by norm_num) '
                         f'(by norm_num) (by norm_num))')
    hitset = '{' + ', '.join(str(n) for n, _ in hits) + '}' if hits else '∅'
    Fz = _expr(fi, 'z')
    Pz = _expr(_ints(P), 'z')
    lines = ['set_option maxHeartbeats 4000000 in']
    lines.append(f'/-- Generated by `python -m perfectpower lean`: for `n ≥ 1`, '
                 f'`{_expr(fi, "n")} = m ^ {d}` is solvable in integers `m` iff `n ∈ {hitset}`. '
                 f'Runge data: `D = {D}`, `P = {_expr(_ints(P), "x")}`, `x₀ = {x0}`, `T = {T}`. -/')
    lines.append(f'theorem {name} (n : ℕ) (hn : 1 ≤ n) :')
    lines.append(f'    IsHit {d} (let z : ℤ := n; {Fz}) ↔ n ∈ ({hitset} : Finset ℕ) := by')
    lines.append('  constructor')
    lines.append('  · intro h')
    lines.append(f'    by_cases hx : n < {x0}')
    if x0 > 1:
        lines.append('    · interval_cases n')
        lines.extend('  ' + c for c in cases)
    else:
        lines.append('    · omega')
    lines.append('    · exfalso')
    lines.append('      push_neg at hx')
    lines.append('      obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hx')
    lines.append(f'      have hz : ((({x0} + k : ℕ)) : ℤ) = {x0} + (k : ℤ) := by push_cast; ring')
    lines.append(f'      generalize hzdef : ((({x0} + k : ℕ)) : ℤ) = z at h hz')
    lines.append('      simp only at h')
    kk = '(k : ℤ)'
    lines.append(f'      have eP : {Pz} = {_expr(_ints(pl["Ps"]), kk)} := by rw [hz]; ring')
    lines.append(f'      have hP : (0 : ℤ) < {Pz} := by rw [eP]; positivity')
    Rz = f'({D} ^ {d} * ({Fz}) - ({Pz}) ^ {d})'
    bnd = f'({T} + 1) * ({Pz}) ^ {d - 1}'
    idx = 0
    if d % 2:
        for sign, (c, sh) in zip(('-', '+'), pl['conds'][:2]):
            lines.append(f'      have o{idx} : ({Pz}) ^ {d} {sign} {Rz} = {_expr(_ints(sh), kk)} := by rw [hz]; ring')
            lines.append(f'      have p{idx} : (0 : ℤ) < ({Pz}) ^ {d} {sign} {Rz} := by rw [o{idx}]; positivity')
            idx += 1
        lines.append(f'      have hodd : Odd {d} → |{Rz}| < |{Pz}| ^ {d} := fun _ => by')
        lines.append('        rw [abs_of_pos hP, abs_lt]; constructor <;> linarith')
    else:
        lines.append(f'      have hodd : Odd {d} → |{Rz}| < |{Pz}| ^ {d} := fun ho => absurd ho (by decide)')
    sm = pl['conds'][-2:]
    for sign, (c, sh) in zip(('-', '+'), sm):
        lines.append(f'      have s{idx} : {bnd} {sign} {Rz} = {_expr(_ints(sh), kk)} := by rw [hz]; ring')
        lines.append(f'      have q{idx} : (0 : ℤ) < {bnd} {sign} {Rz} := by rw [s{idx}]; positivity')
        idx += 1
    lines.append(f'      have hsmall : |{Rz}| < ((({T} : ℕ) : ℤ) + 1) * |{Pz}| ^ {d - 1} := by')
    lines.append('        rw [abs_of_pos hP, abs_lt]; push_cast; constructor <;> linarith')
    lines.append(f'      obtain ⟨t, ht, heq⟩ := runge_pointwise (d := {d}) (by norm_num) '
                 f'(p := {Pz}) (D := {D}) (T := {T}) hP.ne\' hodd hsmall h')
    lines.append('      obtain ⟨htl, htr⟩ := abs_le.mp ht')
    lines.append('      push_cast at htl htr')
    lines.append('      interval_cases t')
    for t in range(-T, T + 1):
        G, Gsh, sgn = pl['Gs'][t]
        e = _expr(_ints(scale(Gsh, sgn)), kk)
        lhs = f'{sgn} * ({D} ^ {d} * ({Fz}) - ({Pz} + ({t})) ^ {d})'
        lines.append(f'      · have eG : {lhs} = {e} := by rw [hz]; ring')
        lines.append(f'        have pG : (0 : ℤ) < {lhs} := by rw [eG]; positivity')
        lines.append('        rw [heq] at pG; simp at pG')
    lines.append('  · intro h')
    if hits:
        lines.append('    simp only [Finset.mem_insert, Finset.mem_singleton] at h')
        lines.append('    rcases h with ' + ' | '.join('rfl' for _ in hits))
        for n, m in hits:
            lines.append(f'    · exact ⟨{m}, by norm_num⟩')
    else:
        lines.append('    simp at h')
    return '\n'.join(lines) + '\n'


def emit_file(entries, **kw) -> str:
    """entries: iterable of (name, coefficients, d); returns the text of a Lean module."""
    body = []
    for name, f, d in entries:
        thm = emit(name, f, d, **kw)
        if thm is None:
            raise ValueError(f'no Runge plan for {name}')
        body.append(thm)
    return ('import PerfectPower.Certificates\n\n'
            '/-! Machine-generated by `python -m perfectpower lean` (python/perfectpower/lean_emit.py).\n'
            'Do not edit by hand; regenerate with `python3 python/make_lean_certificates.py`. -/\n\n'
            'namespace PerfectPower.Generated\nopen PerfectPower\n\n'
            + '\n'.join(body) + '\nend PerfectPower.Generated\n')


def emit_reflective(name: str, coefficients, d: int, **kw) -> str | None:
    """The same hit-set theorem as `emit`, as data checked by `PerfectPower.Reflect.rungeCheck`
    (soundness `Reflect.rungeCheck_sound`, proved once)."""
    pl = plan(coefficients, d, **kw)
    if pl is None:
        return None
    F, D, P, x0, T = pl['F'], pl['D'], pl['P'], pl['x0'], pl['T']
    fi, Pi = _ints(F), _ints(P)
    segs, hits = [], []
    for n in range(1, x0):
        v = sum(c * n ** i for i, c in enumerate(fi))
        m = integer_power_root(v, d)
        if m is not None:
            segs.append(f'.hit {n} ({m})')
            hits.append(n)
        elif v < 0 and d % 2 == 0:
            segs.append(f'.neg {n}')
        else:
            segs.append(f'.gap {n} {floor_nth_root(abs(v), d)}')
    signs = [pl['Gs'][t][2] for t in range(-T, T + 1)]
    lst = lambda xs: '[' + ', '.join(f'({x})' if x < 0 else str(x) for x in xs) + ']'
    cert = f'cert_{name}'
    Fz = _expr(fi, 'z')
    stmt = f'IsHit {d} (let z : ℤ := n; {Fz})'
    hitset = '{' + ', '.join(map(str, hits)) + '}' if hits else '∅'
    seg_text = ', '.join(segs)
    return f'''/-- Runge certificate data for `{name}`: `D = {D}`, `P = {_expr(Pi, "x")}`, `x₀ = {x0}`, `T = {T}`. -/
def {cert} : Reflect.RungeCert where
  F := {lst(fi)}
  d := {d}
  D := {D}
  P := {lst(Pi)}
  x₀ := {x0}
  T := {T}
  segs := [{seg_text}]
  signs := {lst(signs)}

/-- The verified Runge checker accepts `{cert}` (kernel evaluation). -/
theorem {cert}_ok : Reflect.rungeCheck {cert} = true := by decide +kernel

/-- Complete hit set (Runge branch, reflective certificate): for `n ≥ 1`,
`{_expr(fi, "n")} = m ^ {d}` is solvable in integers iff `n ∈ {hitset}`. -/
theorem {name} (n : ℕ) (hn : 1 ≤ n) : {stmt} ↔ n ∈ ({hitset} : Finset ℕ) := by
  have h := Reflect.rungeCheck_sound {cert}_ok n hn
  have hF : {cert}.F = {lst(fi)} := rfl
  have e : Reflect.ev {cert}.F n = (let z : ℤ := n; {Fz}) := by
    rw [hF]; simp only [Reflect.ev]; ring
  have hh : Reflect.hitsOf {cert}.segs = {lst(hits)} := by decide +kernel
  have hd : {cert}.d = {d} := rfl
  rw [e, hh, hd] at h
  rw [h]
  simp
'''


def emit_file_reflective(entries, **kw) -> str:
    """Lean module of reflective Runge certificates for (name, coefficients, d) entries."""
    body = []
    for name, f, d in entries:
        thm = emit_reflective(name, f, d, **kw)
        if thm is None:
            raise ValueError(f'no Runge plan for {name}')
        body.append(thm)
    return ('import PerfectPower.Reflect\n\n'
            '/-! Machine-generated by `python3 python/make_lean_certificates.py`\n'
            '(python/perfectpower/lean_emit.py, `emit_reflective`): Runge certificates as data, checked\n'
            'by the verified checker `PerfectPower.Reflect.rungeCheck` (`rungeCheck_sound`).\n'
            'Do not edit by hand. -/\n\n'
            'namespace PerfectPower.Generated\nopen PerfectPower\n\n'
            + '\n'.join(body) + '\nend PerfectPower.Generated\n')
