import assert from 'node:assert/strict';
import fs from 'node:fs';
import {overlap} from '../lib/dresden-math.ts';
import {solveCalendar,venusExperiment,parseRational,exact,intervalDistribution,distributionSummary,totalVariation,rankPrediction,customRestartOrders,daysFromDigits} from '../lib/dresden-research.ts';
const f=JSON.parse(fs.readFileSync(new URL('./deep-python-fixtures.json',import.meta.url))),lunar=JSON.parse(fs.readFileSync(new URL('../lib/data/lunar_source.json',import.meta.url))),eclipse=JSON.parse(fs.readFileSync(new URL('../lib/data/eclipse_stations.json',import.meta.url)));
for(const row of f.calendar){const i=row.input,r=solveCalendar(i.number,i.sign,i.haab,i.venus,BigInt(i.lo),BigInt(i.hi),BigInt(i.rank));assert.equal(r.compatible,row.compatible);if(r.compatible){assert.equal(r.residue.toString(),row.residue);assert.equal(r.modulus.toString(),row.modulus);assert.equal(r.count.toString(),row.count);assert.equal(r.selected?.toString()??null,row.selected);}}
for(const row of f.venus){const r=venusExperiment(BigInt(row.rounds),row.model,parseRational(row.reference));assert.equal(r.day.toString(),String(row.execute.day));assert.equal(exact(r.error),row.execute.error_against_mean);assert.equal(exact(r.minimum.error),row.envelope.minimum);assert.equal(exact(r.maximum.error),row.envelope.maximum);assert.deepEqual(r.candidateRounds.map(String),row.envelope.candidate_rounds.map(String));}
for(const row of f.windows){const rows=intervalDistribution(lunar.days,row.span,row.start,row.end),s=distributionSummary(rows);assert.deepEqual(rows,row.distribution);assert.equal(s.count.toString(),String(row.summary.count));assert.equal(exact(s.mean),row.summary.mean);assert.equal(exact(s.variance),row.summary.variance);assert.deepEqual(s.central95,row.summary.central95);assert.equal(s.median,row.summary.median);}
for(const row of f.comparisons)assert.equal(exact(totalVariation(intervalDistribution(lunar.days,row.a),intervalDistribution(lunar.days,row.b),...row.offsets)),row.distance);
const stations=eclipse.stations.filter(s=>s.classification==='intended').map(s=>s.month);
for(const row of f.ranks){const schedule=overlap(stations,Array.from({length:5},(_,i)=>i===row.position?223:358));assert.equal(rankPrediction(schedule,BigInt(row.rank),BigInt(row.start)).toString(),row.selected);}
for(const row of f.policies){const p=customRestartOrders(parseRational(row.long),parseRational(row.short));assert.equal(exact(p.best),row.best);assert.deepEqual(p.winners,row.winners);assert.equal(exact(p.orders[0].terminal),row.terminal);}
for(const row of eclipse.selected_raw_cumulative_readings)assert.equal(daysFromDigits(row.digits)+BigInt(row.correction),BigInt(eclipse.stations[row.station-1].corrected_day));
assert.throws(()=>solveCalendar(14,0,0,null,0n,10n));assert.throws(()=>venusExperiment(1n,0,parseRational('0')));assert.throws(()=>intervalDistribution([1,1,2],1));assert.throws(()=>rankPrediction(overlap([1],[2]),-1n));assert.equal(exact(totalVariation([{days:1,count:2},{days:1,count:1}],[{days:1,count:3}])),'0');
console.log(`PASS: ${f.calendar.length} calendar queries; ${f.venus.length} exact Venus experiments/envelopes; ${f.windows.length} recomputed corpus windows; ${f.comparisons.length} distribution comparisons; ${f.ranks.length} exact ranked predictions; ${f.policies.length} rational restart policies including ties; all 14 raw corrections; invalid inputs.`);
