"""Emit PerfectPower/Generated/MordellPoints.lean from data/mordell_census.csv.

Lean's role here is deliberately narrow.  The points are data, grouped by curve as
`(k, [(x, y), ...])`; the verified checker `PerfectPower.Reflect.mordellOK` is run by kernel
evaluation (`decide +kernel`) on each block, and `Reflect.mordellOK_sound` turns the result into
the statement that every listed point satisfies y^2 = x^3 + k.  It does NOT check that the census
lists are complete; completeness is Sage's claim (see docs/TRUST_BOUNDARY.md).
"""
import csv
from math import isqrt
from pathlib import Path

BLOCK = 150            # points per block, to keep each kernel check and literal small
root = Path(__file__).resolve().parents[1]
curves = []
total = 0
for r in csv.DictReader(open(root / 'data' / 'mordell_census.csv')):
    k = int(r['k'])
    pts = []
    for x in r['x_coordinates'].split():
        x = int(x)
        y = isqrt(x ** 3 + k)
        assert y * y == x ** 3 + k
        pts.append((x, y))
    if pts:
        curves.append((k, pts))
        total += len(pts)

blocks, cur, size = [], [], 0
for k, pts in curves:
    cur.append((k, pts))
    size += len(pts)
    if size >= BLOCK:
        blocks.append(cur)
        cur, size = [], 0
if cur:
    blocks.append(cur)

out = ['import PerfectPower.Reflect', '',
       '/-! Machine-generated by `python3 python/make_lean_census.py` from `data/mordell_census.csv`.',
       '',
       'Points are data `(k, [(x, y), …])`, checked by the verified checker `Reflect.mordellOK`',
       '(kernel evaluation, `decide +kernel`; no `Lean.ofReduceBool`) and turned into a statement by',
       '`Reflect.mordellOK_sound`.  **Completeness of the census is not checked here**: it is',
       'certified externally by Sage (Mordell-Weil basis + elliptic-logarithm sieving).',
       f'Curves with points: {len(curves)}; total points (one per x, y >= 0): {total}. -/', '',
       'set_option maxHeartbeats 4000000', '', 'namespace PerfectPower.Generated.Mordell', '', 'open PerfectPower', '']
names = []
for i, blk in enumerate(blocks):
    n = f'block{i}'
    names.append(n)
    body = ',\n  '.join(f'({k}, [' + ', '.join(f'({x}, {y})' for x, y in pts) + '])' for k, pts in blk)
    out.append(f'/-- Census block {i}: curves `k = {blk[0][0]} … {blk[-1][0]}`. -/')
    out.append(f'def {n} : List (ℤ × List (ℤ × ℤ)) := [\n  {body}]')
    out.append(f'theorem {n}_ok : Reflect.mordellOK {n} = true := by decide +kernel')
    out.append('')
out.append('/-- The whole census, block by block. -/')
out.append('def census : List (ℤ × List (ℤ × ℤ)) :=\n  ' + ' ++\n  '.join(names))
out.append('')
out.append(f'/-- The census lists {len(curves)} curves and {total} points. -/')
out.append(f'theorem census_size : census.length = {len(curves)} ∧ '
           f'(census.map fun e => e.2.length).sum = {total} := by decide +kernel')
out.append('')
out.append('theorem census_ok : Reflect.mordellOK census = true := by')
out.append('  simp only [census, Reflect.mordellOK_append, ' + ', '.join(f'{n}_ok' for n in names)
           + ', Bool.and_self]')
out.append('')
out.append(f'/-- All {total} census points lie on their curves (completeness is not claimed). -/')
out.append('theorem census_points_valid : ∀ e ∈ census, ∀ p ∈ e.2, p.2 ^ 2 = p.1 ^ 3 + e.1 :=')
out.append('  Reflect.mordellOK_sound census_ok')
out.append('')
out.append('end PerfectPower.Generated.Mordell')
(root / 'PerfectPower' / 'Generated' / 'MordellPoints.lean').write_text('\n'.join(out) + '\n')
print(total, 'points on', len(curves), 'curves in', len(names), 'blocks')
