"""Emit PerfectPower/Generated/BoundedPlans.lean: bounded quadratic queries as kernel-checked theorems
(`BoundedPell.quad_bounded`).  The example is the configuration check of `examples/smt/vc_pairs_square.smt2`:
every `(N, S)` with `2 ≤ N ≤ 10⁹` and `N(N − 1) = 2S²`."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'python'))

from perfectpower.bounded_pell import lean_theorem, plan  # noqa: E402

INSTANCES = [('pairs_square_1e9', (2, 0, 0, 1, -1, 0, 2, 10 ** 9))]


def main():
    out = ['import PerfectPower.BoundedPell', '',
           '/-! Machine-generated by `python3 python/make_lean_bounded.py`; do not edit. -/', '',
           'namespace PerfectPower.Generated.BoundedPlans', '', 'open PerfectPower', '']
    for name, args in INSTANCES:
        P = plan(*args)
        out.append(lean_theorem(name, P))
        print(f'{name}: {len(P["L0"])} solutions, {P["J"]} orbit steps, seeds {P["seeds"]}')
    out.append('end PerfectPower.Generated.BoundedPlans\n')
    (ROOT / 'PerfectPower' / 'Generated' / 'BoundedPlans.lean').write_text('\n'.join(out))


if __name__ == '__main__':
    main()
