"""Emit PerfectPower/Generated/MordellDescent.lean and receipts/mordell_descent.json.

For every k with 0 < |k| <= K that can be written k = c^3 - D b^2 (D in {1, 2, -2}) so that the
descent of `PerfectPower/MordellDescent.lean` applies, emit an unconditional Lean theorem

    theorem no_points_k (x y : Int) : y ^ 2 ≠ x ^ 3 + k

The applicability test here only *searches* for (D, c, b, M, j, b1, u); Lean re-checks every
condition (the congruence by kernel evaluation, the divisor certificate b1 | u^2 + D, and
k = c^3 - D b^2).  Standard library only.
"""
import json
import sys
from math import isqrt
from pathlib import Path

root = Path(__file__).resolve().parents[1]
K = 10000
C_RANGE = 3000
GOOD = {1: {1, 5}, 2: {1, 3}, -2: {1, 7}}


def odd_part(b):
    j = 0
    while b % 2 == 0:
        b //= 2
        j += 1
    return j, b


def factor(n):
    fs, p = {}, 2
    while p * p <= n:
        while n % p == 0:
            fs[p] = fs.get(p, 0) + 1
            n //= p
        p += 1
    if n > 1:
        fs[n] = fs.get(n, 0) + 1
    return fs


def sqrt_mod_prime(a, p):
    a %= p
    for r in range(p) if p < 64 else ():
        if r * r % p == a:
            return r
    if pow(a, (p - 1) // 2, p) != 1:
        return None
    q, s = p - 1, 0
    while q % 2 == 0:
        q //= 2
        s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1:
        z += 1
    m, c, t, r = s, pow(z, q, p), pow(a, q, p), pow(a, (q + 1) // 2, p)
    while t != 1:
        i, t2 = 0, t
        while t2 != 1:
            t2 = t2 * t2 % p
            i += 1
        bb = pow(c, 1 << (m - i - 1), p)
        m, c, t, r = i, bb * bb % p, t * bb * bb % p, r * bb % p
    return r


def sqrt_neg_D(D, b1):
    """u with b1 | u^2 + D (b1 odd, every prime of b1 good for D), by Hensel lifting and CRT."""
    u, mod = 0, 1
    for p, e in factor(b1).items():
        r = sqrt_mod_prime(-D, p)
        if r is None:
            return None
        pe = p
        for _ in range(e - 1):          # Hensel: r -> r - (r^2 + D) / (2r) mod p^(k+1)
            pe *= p
            r = (r - (r * r + D) * pow(2 * r, -1, pe)) % pe
        # CRT
        u = (u + mod * ((r - u) * pow(mod, -1, pe) % pe)) % (mod * pe)
        mod *= pe
    assert (u * u + D) % b1 == 0
    return u


def cong_ok(D, c, b, M):
    for x in range(M):
        q = x * x - c * x + c * c
        rhs = (x ** 3 + c ** 3 - D * b * b) % M
        for y in range(M):
            if (y * y - rhs) % M == 0 and (q % 2 == 0 or q % 8 in GOOD[D]):
                return False
    return True


def search():
    found, cache = {}, {}
    for D in (1, 2, -2):
        for c in range(-C_RANGE, C_RANGE + 1):
            c3 = c ** 3
            lo, hi = c3 - K, c3 + K                 # D b^2 = c^3 - k in [lo, hi]
            if D > 0:
                if hi < 0:
                    continue
                bl, bh = isqrt(max(lo, 0) // D), isqrt(hi // D) + 1
            else:
                if lo > 0:
                    continue
                bl, bh = isqrt(max(-hi, 0) // 2), isqrt(-lo // 2) + 1
            for b in range(max(bl - 1, 1), bh + 1):
                k = c3 - D * b * b
                if k == 0 or abs(k) > K:
                    continue
                j, b1 = odd_part(b)
                if D == 1 and b1 % 2 == 0:
                    continue
                key = (D, c % 32, b % 32)
                if key not in cache:
                    cache[key] = next((M for M in (8, 16, 32) if cong_ok(D, c % 32, b % 32, M)), None)
                M = cache[key]
                if not M:
                    continue
                u = sqrt_neg_D(D, b1)
                if u is None:
                    continue
                cand = (M, len(str(b)), abs(c), D)
                if k not in found or cand < found[k][0]:
                    found[k] = (cand, dict(k=k, D=D, c=c, b=b, M=M, j=j, b1=b1, u=u))
    return [v[1] for _, v in sorted(found.items())]


def name(k):
    return f'no_points_{"m" if k < 0 else ""}{abs(k)}'


def main():
    rows = search()
    out = ['import PerfectPower.MordellDescent', '',
           '/-! Machine-generated by `python3 python/make_lean_mordell_descent.py`.  Each theorem is',
           'unconditional: `y^2 = x^3 + k` has no integral points.  The search for the parameters is',
           'in Python; every condition is re-checked by Lean.  Do not edit by hand. -/', '',
           'namespace PerfectPower.Generated.MordellDescent', '',
           'open PerfectPower.MordellDescent', '']
    for r in rows:
        k, D, c, b, M, j, b1, u = (r[x] for x in ('k', 'D', 'c', 'b', 'M', 'j', 'b1', 'u'))
        out.append(f'''theorem {name(k)} (x y : ℤ) : y ^ 2 ≠ x ^ 3 + ({k}) := by
  have h := no_points (D := {D}) (c := {c}) (b := {b}) (by norm_num)
    (goodDivisors_of_cert (by norm_num) {j} (b₁ := {b1}) (u := {u}) (by norm_num) (by norm_num))
    (M := {M}) (by norm_num) (by decide +kernel) x y
  rwa [show ({c} : ℤ) ^ 3 - ({D}) * {b} ^ 2 = {k} by norm_num] at h
''')
    out.append('end PerfectPower.Generated.MordellDescent')
    (root / 'PerfectPower' / 'Generated' / 'MordellDescent.lean').write_text('\n'.join(out) + '\n')
    census = {}
    cpath = root / 'data' / 'mordell_census.csv'
    if cpath.exists():
        import csv
        census = {int(r['k']): r for r in csv.DictReader(cpath.open())}
    upgraded = [r['k'] for r in rows if census.get(r['k'], {}).get('certification') != 'INDEPENDENT_COMPUTATION']
    conflicts = [r['k'] for r in rows if r['k'] in census and census[r['k']]['n_points_up_to_sign'] != '0']
    assert not conflicts, conflicts
    (root / 'receipts' / 'mordell_descent.json').write_text(json.dumps(
        {'K': K, 'c_range': C_RANGE, 'label': 'LEAN_CERTIFIED', 'curves': len(rows),
         'census_conflicts': conflicts, 'census_rows_not_independently_certified': upgraded,
         'by_D': {str(D): sum(r['D'] == D for r in rows) for D in (1, 2, -2)},
         'rows': rows}, indent=1) + '\n')
    print(len(rows), 'Mordell curves without integral points')


if __name__ == '__main__':
    sys.exit(main())
