"""Regenerate PerfectPower/Generated/Runge.lean: Lean-checked complete hit sets (Runge branch)."""
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from perfectpower.core import mul
import perfectpower.lean_emit as lean_emit


def consecutive(k):
    p = (Fraction(1),)
    for i in range(k):
        p = mul(p, (Fraction(i), Fraction(1)))
    return [int(x) for x in p]


ENTRIES = [
    ('ljunggren_quartic_hits', [1, 1, 1, 1, 1], 2),
    ('n4_plus_1_square_hits', [1, 0, 0, 0, 1], 2),
    ('consecutive4_square_hits', consecutive(4), 2),
    ('consecutive4_fourth_power_hits', consecutive(4), 4),
    ('consecutive6_square_hits', consecutive(6), 2),
    ('consecutive6_cube_hits', consecutive(6), 3),
    ('consecutive6_sixth_power_hits', consecutive(6), 6),
    ('consecutive8_square_hits', consecutive(8), 2),
    ('consecutive8_fourth_power_hits', consecutive(8), 4),
    ('consecutive8_eighth_power_hits', consecutive(8), 8),
    ('consecutive10_fifth_power_hits', consecutive(10), 5),
    ('consecutive12_square_hits', consecutive(12), 2),
    ('consecutive12_cube_hits', consecutive(12), 3),
    ('consecutive12_sixth_power_hits', consecutive(12), 6),
    ('n6_plus_n_plus_1_cube_hits', [1, 1, 0, 0, 0, 0, 1], 3),
    ('n4_plus_7_square_hits', [7, 0, 0, 0, 1], 2),
    ('sextic_1_2_3_4_5_6_1_cube_hits', [1, 2, 3, 4, 5, 6, 1], 3),
]

# Instances whose Runge plan needs a long scan below the threshold: interval-sandwich covers.
SANDWICH_ENTRIES = [
    ('consecutive10_square_hits', consecutive(10), 2),
    ('consecutive12_fourth_power_hits', consecutive(12), 4),
]


HEADER = ('import PerfectPower.Reflect\n\n'
          '/-! Machine-generated by `python3 python/make_lean_certificates.py` from the pp-cert/1\n'
          'certificates in `certs/{sub}/` (python/perfectpower/certfmt.py, `to_lean`): {what} as data,\n'
          'checked by the verified checker `PerfectPower.Reflect.{checker}` (`{sound}`).\n'
          'Do not edit by hand. -/\n\n'
          'namespace PerfectPower.Generated\nopen PerfectPower\n\n')


def write_family(root, sub, certs, what, checker, sound, lean_name):
    import json
    from perfectpower.certfmt import canonical, to_lean
    d = root / 'certs' / sub
    d.mkdir(parents=True, exist_ok=True)
    for c in certs:
        (d / f"{c['name']}.json").write_text(json.dumps(c, indent=1, sort_keys=True) + '\n')
    text = (HEADER.format(sub=sub, what=what, checker=checker, sound=sound)
            + '\n'.join(to_lean(c) for c in certs) + '\nend PerfectPower.Generated\n')
    out = root / 'PerfectPower' / 'Generated' / lean_name
    out.write_text(text)
    print(out, len(certs), 'certificates')


def main():
    import json
    from perfectpower.certfmt import produce_runge, produce_sandwich
    root = Path(__file__).resolve().parents[1]
    (root / 'PerfectPower' / 'Generated').mkdir(exist_ok=True)
    entries = [e for e in ENTRIES if len(sys.argv) < 2 or e[0] in sys.argv[1:]]
    runge = [produce_runge(n, f, d, T_max=6, x0_max=300) for n, f, d in entries]
    write_family(root, 'runge', runge, 'Runge certificates', 'rungeCheck', 'rungeCheck_sound', 'Runge.lean')
    sandwich = [produce_sandwich(n, f, d) for n, f, d in SANDWICH_ENTRIES]
    write_family(root, 'sandwich', sandwich, 'interval-sandwich certificates', 'check', 'check_sound',
                 'Sandwich.lean')
    stats = {c['name']: {'coefficients': c['statement']['F'], 'd': c['statement']['d'],
                         'tail_start': c['data']['tail_start'], 'tail_t': c['data']['tail_t'],
                         'pieces': len(c['data']['segments']),
                         'intervals': sum(1 for s in c['data']['segments'] if s['k'] == 'ival'),
                         'points': sum(1 for s in c['data']['segments'] if s['k'] != 'ival'),
                         'hits': c['statement']['hits']} for c in sandwich}
    (root / 'receipts' / 'sandwich_certificates.json').write_text(json.dumps(stats, indent=2) + '\n')


if __name__ == '__main__':
    main()
