"""Rewrite the machine-generated counts block in README.md from audit and receipt outputs.

Run after ./audit/check_axioms.sh (which writes audit/axioms_report.txt).  `make verify` fails
if the block changes, so the README can never quote a stale count.
"""
import json
import re
from collections import Counter
from pathlib import Path

root = Path(__file__).resolve().parents[1]
report = (root / 'audit' / 'axioms_report.txt').read_text().splitlines()
audited = [l for l in report if 'depends on axioms' in l]
standard = [l for l in audited if l.endswith('[propext, Classical.choice, Quot.sound]')]
generated = [l for l in audited if 'PerfectPower.Generated.' in l]
atlas = json.loads((root / 'receipts' / 'atlas_benchmarks.json').read_text())
labels = Counter(r['certification'] for r in atlas['rows'])
lines = [
    f'- Lean declarations audited: **{len(audited)}**; using only `propext`, `Classical.choice`, '
    f'`Quot.sound`: **{len(standard)}**.',
    f'- Machine-generated Lean hit-set certificates: **{len(generated)}**.',
    '- Atlas families by certification label: '
    + ', '.join(f'`{k}` {v}' for k, v in sorted(labels.items())) + '.',
]
cub = root / 'receipts' / 'cubic_crossval.json'
if cub.exists():
    s = json.loads(cub.read_text())['summary']
    lines.append(f'- Cubic cross-validation ($m^2=n^3+an+b$, $|a|,|b|\\le{s["bound"]}$): '
                 f'{s["certified_rows"]}/{s["curves"]} certified by Sage, '
                 f'{len(s["disagreements"])} disagreements with the scan to $10^5$.')
adv = root / 'receipts' / 'adversarial_runge.json'
if adv.exists():
    s = json.loads(adv.read_text())['summary']
    lines.append(f'- Adversarial Runge test: {s["trials"]} planted-hit trials, {s["failures"]} failures, '
                 f'planted hits up to {s["max_planted_found"]:,}.')
mc = root / 'receipts' / 'mordell_census_summary.json'
if mc.exists():
    s = json.loads(mc.read_text())
    lab = s['labels']
    lines.append(f'- Mordell census $y^2=x^3+k$, $0<|k|\\le{s["K"]}$: {s["curves"]} curves; '
                 f'{lab["certified_by_independent_computation"]} certified by Sage, '
                 f'{lab["conditional_on_unproven_rank"]} conditional on an unproven rank, '
                 f'{lab["scan_only"]} scan only; {len(s["scan_disagreements"])} disagreements with the scan '
                 f'$|x|\\le10^5$; best Hall ratio {s["top_hall_ratios"][0]["ratio"]} '
                 f'($k={s["top_hall_ratios"][0]["k"]}$).')
pc = root / 'receipts' / 'pillai_census_summary.json'
if pc.exists():
    s = json.loads(pc.read_text())
    lines.append(f'- Pillai gap census: {s["pairs"]} pairs of perfect powers $\\le {s["B"].replace("^", "^{")}}}$ at distance '
                 f'$\\le {s["K"]}$ (exact within the bound).')
block = '<!-- counts:begin (generated by python/make_counts.py; do not edit) -->\n' + \
        '\n'.join(lines) + '\n<!-- counts:end -->'
readme = root / 'README.md'
text = readme.read_text()
text = re.sub(r'<!-- counts:begin.*?<!-- counts:end -->', lambda m: block, text, flags=re.S)
readme.write_text(text)
print('\n'.join(lines))
