"""Complete point lists for y^2 = x^3 - D from the branch compiler (`branch_descent.py`), as Lean.

For every D with 1 <= D <= 100 among the curves the compiler cannot otherwise enumerate
(`receipts/mordell_obstructions.json`), the branch compiler runs; each COMPLETE certificate is
emitted as a theorem in `PerfectPower/Generated/MordellBranch.lean` (checked by `lake build`),
and every curve (closed or open, with its open branches) is recorded in
`receipts/mordell_branch.json`.
"""
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'python'))

from perfectpower.branch_descent import compile_curve, lean_theorem  # noqa: E402

HEADER = '''import PerfectPower.DescentBranch

/-!
# Complete point lists from the branch compiler (generated by `python/make_lean_mordell_branch.py`)

Each theorem is `DescentBranch.complete_of_branch` with a kernel-checked certificate: every table
entry of the Thue lattice argument is a field cube (its branch is a reducible cubic, listed by
divisors) or impossible modulo `m`; every candidate is filtered back onto the curve.
-/

namespace PerfectPower.Generated.MordellBranch

open PerfectPower

'''


def main():
    ledger = json.loads((ROOT / 'receipts' / 'mordell_obstructions.json').read_text())
    Ds = sorted(-r['k'] for r in ledger['rows'] if r['k'] < 0)
    census = {}
    with open(ROOT / 'data' / 'mordell_census.csv') as f:
        for row in csv.DictReader(f):
            census[int(row['k'])] = row
    published = {r['k']: (r.get('expert_scan') or {}).get('published_signed_count') for r in ledger['rows']}
    recs, blocks = [], []
    for D in Ds:
        c = compile_curve(D)
        rec = {k: v for k, v in c.items() if k not in ('entries',)}
        rec['entries'] = len(c.get('entries', []))
        rec['cube_entries'] = sum('cube' in e for e in c.get('entries', []))
        rec['mod_entries'] = sum('mod' in e for e in c.get('entries', []))
        if c['status'] == 'COMPLETE':
            name = f'minus{D}'
            blocks.append(lean_theorem(name, c))
            rec['lean'] = f'PerfectPower.Generated.MordellBranch.{name}'
        rec['points'] = [list(p) for p in c.get('points', [])]
        row = census.get(-D)
        rec['sage_rank'] = int(row['rank']) if row else None
        rec['sage_census_x'] = sorted(int(v) for v in row['x_coordinates'].split()) if row else None
        rec['published_signed_count'] = published.get(-D)
        if c['status'] == 'COMPLETE':
            xs = sorted({x for x, _ in c['points']})
            rec['agrees_with_sage'] = rec['sage_census_x'] == xs
            rec['agrees_with_published'] = rec['published_signed_count'] == len(c['points'])
        recs.append(rec)
    (ROOT / 'PerfectPower' / 'Generated' / 'MordellBranch.lean').write_text(
        HEADER + '\n'.join(blocks) + '\nend PerfectPower.Generated.MordellBranch\n')
    closed = [r for r in recs if r['status'] == 'COMPLETE']
    out = {'curves': len(recs), 'complete': len(closed), 'open': len(recs) - len(closed),
           'complete_D': [r['D'] for r in closed],
           'complete_agree_with_sage': sum(bool(r.get('agrees_with_sage')) for r in closed),
           'complete_agree_with_published': sum(bool(r.get('agrees_with_published')) for r in closed),
           'complete_by_sage_rank': {str(k): sum(r['sage_rank'] == k for r in closed) for k in sorted({r['sage_rank'] for r in closed})},
           'rule': 'COMPLETE only when every table entry is a field cube or locally impossible, '
                   'and the Lean theorem compiles; an entry that is neither is an irreducible '
                   'Thue equation and the curve stays OPEN_BRANCH',
           'curves_detail': recs}
    (ROOT / 'receipts' / 'mordell_branch.json').write_text(json.dumps(out, indent=1) + '\n')
    print(f"{len(recs)} curves y^2 = x^3 - D: {len(closed)} complete lists emitted, {out['open']} with open branches; "
          f"complete lists agree with Sage {out['complete_agree_with_sage']}/{len(closed)}, "
          f"with published counts {out['complete_agree_with_published']}/{len(closed)}; ranks {out['complete_by_sage_rank']}")
    if out['complete_agree_with_sage'] != len(closed) or out['complete_agree_with_published'] != len(closed):
        raise SystemExit('a certified list disagrees with an independent computation')


if __name__ == '__main__':
    main()
