"""Emit PerfectPower/Generated/Genus1.lean from receipts/genus1_crossval.json.

For every genus-one family whose Sage computation is labelled INDEPENDENT_COMPUTATION, the file
contains
  * the model's integral points (from Sage) as data,
  * a named hypothesis `IntegralPoints_<name>`: every integral point of the model is listed,
  * a theorem proving the complete hit list from that hypothesis, by the verified checkers
    `Genus1.cubicOK` / `Genus1.quadOK` (kernel evaluation) and `Genus1.cubic_sound` /
    `Genus1.quad_sound`.
Lean checks the reduction, the pull-back, that every listed point lies on the model, and a witness
for every hit.  The hypothesis (completeness of Sage's list) is NOT proved in Lean: these rows are
LEAN_REDUCTION_PLUS_INDEPENDENT_POINTS, not LEAN_CERTIFIED.
"""
import json
import sys
from math import isqrt
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from perfectpower.lean_emit import _expr  # noqa: E402

root = Path(__file__).resolve().parents[1]


def icbrt(v):
    s = -1 if v < 0 else 1
    r = round(abs(v) ** (1 / 3)) if v else 0
    for k in (r - 1, r, r + 1):
        if k >= 0 and k ** 3 == abs(v):
            return s * k
    raise ValueError(v)


def tag(f):
    return '_'.join(('m' + str(-c)) if c < 0 else str(c) for c in f)


def lst_pairs(ps):
    return '[' + ', '.join(f'({u}, {v})' for u, v in ps) + ']'


def main():
    rec = json.loads((root / 'receipts' / 'genus1_crossval.json').read_text())
    rows = [r for r in rec['rows'] if r['certification'] == 'INDEPENDENT_COMPUTATION']
    out = ['import PerfectPower.Genus1', '',
           '/-! Machine-generated by `python3 python/make_lean_genus1.py` from',
           '`receipts/genus1_crossval.json`.  Each theorem proves a complete hit list *from the named',
           'hypothesis* `IntegralPoints_…` that Sage\'s list of integral points on the Weierstrass model',
           'is complete; that hypothesis is not proved in Lean.  Do not edit by hand. -/', '',
           'set_option maxHeartbeats 1000000', '',
           'namespace PerfectPower.Generated.Genus1', '', 'open PerfectPower PerfectPower.Genus1', '']
    names = []
    for r in rows:
        f = r['F_low_to_high']
        pts = [tuple(p) for p in r['model_integral_points']]
        hits = r['hits']
        if r['kind'] == 'cubic':
            e, c, b, a = f
            d, name = 2, f'g1_sq_{tag(f)}'
            wit = [(n, isqrt(e + c * n + b * n * n + a * n ** 3)) for n in hits]
            model, checker, sound, args = 'cubicModel', 'cubicOK', 'cubic_sound', f'({a}) ({b}) ({c}) ({e})'
            evl = f'[{e}, {c}, {b}, {a}]'
        else:
            c, b, a = f
            d, name = 3, f'g1_cube_{tag(f)}'
            wit = [(n, icbrt(c + b * n + a * n * n)) for n in hits]
            model, checker, sound, args = 'quadModel', 'quadOK', 'quad_sound', f'({a}) ({b}) ({c})'
            evl = f'[{c}, {b}, {a}]'
        names.append(name)
        Fz = _expr(f, 'z')
        hitset = '{' + ', '.join(map(str, hits)) + '}' if hits else '∅'
        wl = '[' + ', '.join(f'({n}, {m})' for n, m in wit) + ']'
        out.append(f'''/-- Sage's integral points on the model of `{name}`. -/
def pts_{name} : List (ℤ × ℤ) := {lst_pairs(pts)}

/-- Hypothesis: every integral point of the Weierstrass model of `{name}` is listed. -/
def IntegralPoints_{name} : Prop :=
  IntegralPointsOn ({model} {args}).1 ({model} {args}).2 pts_{name}

theorem {name}_ok : {checker} {args} pts_{name} {wl} = true := by decide +kernel

/-- Complete hit list, given `IntegralPoints_{name}`: for `n ≥ 1`, `{_expr(f, "n")} = m ^ {d}` iff
`n ∈ {hitset}`. -/
theorem {name}_hits (hpts : IntegralPoints_{name}) (n : ℕ) (hn : 1 ≤ n) :
    IsHit {d} (let z : ℤ := n; {Fz}) ↔ n ∈ ({hitset} : Finset ℕ) := by
  have h := {sound} hpts {name}_ok n hn
  have e : Reflect.ev {evl} n = (let z : ℤ := n; {Fz}) := by simp only [Reflect.ev]; ring
  rw [e] at h
  rw [h]
  simp
''')
    out.append('end PerfectPower.Generated.Genus1')
    (root / 'PerfectPower' / 'Generated' / 'Genus1.lean').write_text('\n'.join(out) + '\n')
    (root / 'receipts' / 'genus1_lean.json').write_text(json.dumps(
        {'theorems': len(names), 'label': 'LEAN_REDUCTION_PLUS_INDEPENDENT_POINTS',
         'names': names}, indent=1) + '\n')
    print(len(names), 'genus-one reduction theorems')


if __name__ == '__main__':
    main()
