"""Generate `PerfectPower/Generated/Field756.lean`: the seven Thue classes of the shared field 756
and the curves `y^2 = x^3 - D`, `D = 7, 28, 63`, under named external bounds.

Input: `receipts/field756_bound.json` (`crosscheck/thue_bound_field756.py`: PARI structure,
Matveev, interval reduction) and `receipts/thue_graph.json` (the classes and their transport
matrices).  Before emitting anything, this script replays every check in Python:
- the unit inverses;
- the box: every lattice element of `±γ0 ε1^e1 ε2^e2`, `|e_i| <= H`, decodes to a listed solution,
  and every listed solution with `|b| > V0` is found in the box (a positive control);
- the small-`b` search with the Cauchy bound;
- per curve: every open branch lies in one of the seven classes, and the candidate `y` values from
  the listed solutions give exactly the points of the Sage census.

Each class theorem is `UnitBox.thue_list` with the hypothesis `bound_i : Prop` left explicit; each
curve theorem is `DescentThueList.complete_of_lists`, with the bounds of its classes as hypotheses.

Run: python3 python/make_lean_field756.py
Writes PerfectPower/Generated/Field756.lean and receipts/field756_certificate.json.
"""
from __future__ import annotations

import csv
import json
import sys
from math import isqrt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'python'))

from perfectpower.branch_descent import compile_curve, lean_args  # noqa: E402
from perfectpower.descent import W1, W2  # noqa: E402


def _i(x):
    return f'({x})' if x < 0 else str(x)


def z3_lean(t):
    return '(' + ', '.join(_i(v) for v in t) + ')'


def form_lean(F):
    return '(' + ', '.join(_i(c) for c in F) + ')'


def mat_lean(T):
    return f'(({_i(T[0][0])}, {_i(T[0][1])}), ({_i(T[1][0])}, {_i(T[1][1])}))'


def pairs_lean(L):
    return '[' + ', '.join(f'({_i(a)}, {_i(b)})' for a, b in L) + ']'


def mul(P, Q, x, y):
    a, b, c = x
    d, e, f = y
    c0, c1, c2, c3, c4 = a * d, a * e + b * d, a * f + b * e + c * d, b * f + c * e, c * f
    return (c0 + Q * c3, c1 + P * c3 + Q * c4, c2 + P * c4)


def inverse(P, Q, u):
    """Inverse of a unit by solving the 3x3 multiplication matrix exactly."""
    from fractions import Fraction
    cols = [mul(P, Q, u, e) for e in ((1, 0, 0), (0, 1, 0), (0, 0, 1))]
    A = [[Fraction(cols[j][i]) for j in range(3)] + [Fraction(int(i == 0))] for i in range(3)]
    for c in range(3):
        r = next(r for r in range(c, 3) if A[r][c] != 0)
        A[c], A[r] = A[r], A[c]
        A[c] = [x / A[c][c] for x in A[c]]
        for r in range(3):
            if r != c:
                A[r] = [x - A[r][c] * y for x, y in zip(A[r], A[c])]
    inv = tuple(A[i][3] for i in range(3))
    assert all(x.denominator == 1 for x in inv)
    inv = tuple(int(x) for x in inv)
    assert mul(P, Q, u, inv) == (1, 0, 0)
    return inv


def pw(P, Q, x, n):
    r = (1, 0, 0)
    for _ in range(n):
        r = mul(P, Q, r, x)
    return r


def fam(P, Q, g0, e1, e1i, e2, e2i, B):
    def zp(x, xi, i):
        return pw(P, Q, x, i - B) if i >= B else pw(P, Q, xi, B - i)
    return [mul(P, Q, mul(P, Q, g0, zp(e1, e1i, i)), zp(e2, e2i, j))
            for i in range(2 * B + 1) for j in range(2 * B + 1)]


def enc(c0, phi, a, b):
    return (c0 * a - b * phi[0], -(b * phi[1]), -(b * phi[2]))


def _tdiv(x, y):          # Lean `Int.ediv` (Euclidean), as `/` on ℤ
    q = x // y
    if (x - q * y) < 0:
        q += 1 if y < 0 else -1
    return q


def dec(c0, phi, g):
    b = -_tdiv(g[1], phi[1]) if phi[2] == 0 else -_tdiv(g[2], phi[2])
    return (_tdiv(g[0] + b * phi[0], c0), b)


def evalF(F, a, b):
    c0, c1, c2, c3 = F
    return c0 * a ** 3 + c1 * a * a * b + c2 * a * b * b + c3 * b ** 3


def small_hits(F, M, V):
    out = []
    for b in range(-V, V + 1):
        S = abs(F[1] * b) + abs(F[2] * b * b) + abs(F[3] * b ** 3 - M) + 1
        for a in range(-S, S + 1):
            if evalF(F, a, b) == M:
                out.append((a, b))
    return out


def icbrt(n):
    if n < 0:
        return -icbrt(-n)
    x = int(round(n ** (1 / 3)))
    while x ** 3 > n:
        x -= 1
    while (x + 1) ** 3 <= n:
        x += 1
    return x


HEADER = '''import PerfectPower.UnitBox
import PerfectPower.DescentThueList

/-!
# The shared field 756: seven Thue classes and three curves, under named external bounds
(generated by `python/make_lean_field756.py`)

`K = ℚ(x)`, `x³ = 6x + 2`, `O_K = ℤ[x]`, discriminant 756.  Seven GL₂(ℤ)-classes of open branch
equations of `y² = x³ − D`, `D ∈ {7, 28, 63}`, live in this field (`MORDELL_BRANCH.md` §7.3).

* `bound_i : Prop` is the **external** certificate for class `i` (`UnitBox.ExtBound`): every
  solution with `|b| > V` has `c₀a − bφ = ±γ₀ ε₁^{e₁} ε₂^{e₂}`, `|eᵢ| ≤ H`.  It comes from
  `crosscheck/thue_bound_field756.py` (PARI `bnfcertify`, `bnfisintnorm`; Matveev; interval
  reduction) and is **not** proved in Lean.
* `class_i (h : bound_i)`: the complete solution list.  The box and the small-`b` search are
  checked by the kernel.
* `minusD (h… : bound_i …)`: the complete list of integral points of `y² = x³ − D`
  (`DescentThueList.complete_of_lists`), conditional on the bounds of the curve's classes only.
-/

namespace PerfectPower.Generated.Field756

open PerfectPower ThueLocal UnitBox

'''


def main():
    data = json.loads((ROOT / 'receipts' / 'field756_bound.json').read_text())
    graph = json.loads((ROOT / 'receipts' / 'thue_graph.json').read_text())
    gcls = {c['id']: c for c in graph['classes']}
    P, Q = data['P'], data['Q']
    e1, e2 = (tuple(u) for u in data['units'])
    e1i, e2i = inverse(P, Q, e1), inverse(P, Q, e2)
    out = [HEADER,
           f'/-- `ε₁`. -/\ndef e1 : Z3 := {z3_lean(e1)}\n/-- `ε₁⁻¹`. -/\ndef e1i : Z3 := {z3_lean(e1i)}\n'
           f'/-- `ε₂`. -/\ndef e2 : Z3 := {z3_lean(e2)}\n/-- `ε₂⁻¹`. -/\ndef e2i : Z3 := {z3_lean(e2i)}\n',
           f'theorem e1_inv : mul {P} {Q} e1 e1i = (1, 0, 0) := by decide\n'
           f'theorem e2_inv : mul {P} {Q} e2 e2i = (1, 0, 0) := by decide\n']
    report = []
    lists = {}
    for c in data['classes']:
        i, F, M, phi = c['class'], tuple(c['form']), c['M'], tuple(c['phi'])
        g0s = [tuple(g) for g in c['gammas']]
        B, V = c['H_bound'], c['V0']
        L = sorted(tuple(x) for x in c['pari_thue'])
        assert tuple(gcls[i]['representative']) == F and gcls[i]['M'] == M
        assert phi[1] != 0 or phi[2] != 0
        hits = set()
        for g0 in g0s:
            for g in fam(P, Q, g0, e1, e1i, e2, e2i, B):
                for h in (g, tuple(-x for x in g)):
                    d = dec(F[0], phi, h)
                    if enc(F[0], phi, *d) == h and evalF(F, *d) == M:
                        hits.add(d)
        assert hits <= set(L), f'class {i}: box hit outside the list: {hits - set(L)}'
        big = {x for x in L if abs(x[1]) > V}
        assert big <= hits, f'class {i}: positive control failed: {big - hits}'
        sm = set(small_hits(F, M, V))
        assert sm <= set(L) and {x for x in L if abs(x[1]) <= V} <= sm
        lists[i] = L
        report.append({'class': i, 'curves': c['curves'], 'B': B, 'V': V, 'box_size': len(g0s) * (2 * B + 1) ** 2,
                       'box_hits': sorted(hits), 'small_b_hits': sorted(sm), 'list': L})
        out.append(
            f"/-- The external bound for class {i} (`D ∈ {c['curves']}`, `F = {list(F)}`, `M = {M}`): "
            f"`|b| > {V} ⇒ |eᵢ| ≤ {B}`. -/\n"
            f"def bound_{i} : Prop :=\n  ExtBound {form_lean(F)} {M} {P} {Q} {z3_lean(phi)} [{', '.join(z3_lean(g) for g in g0s)}] "
            f"e1 e1i e2 e2i {B} {V}\n\n"
            f"/-- **Class {i}, complete under `bound_{i}`**: `{list(F)}` takes the value {M} exactly at "
            f"{len(L)} point(s); the box ({len(g0s)} × {2 * B + 1}² elements) and the search `|b| ≤ {V}` "
            f"are kernel-checked. -/\n"
            f"theorem class_{i} (h : bound_{i}) (u v : ℤ) :\n    evalF {form_lean(F)} u v = {M} ↔ (u, v) ∈ "
            f"({pairs_lean(L)} : List (ℤ × ℤ)) :=\n"
            f"  thue_list _ _ _ _ _ _ _ _ _ _ _ _ _ (by decide) (by decide) h (by decide +kernel) "
            f"(by decide +kernel) (by decide +kernel) u v\n")
    census = {}
    with open(ROOT / 'data' / 'mordell_census.csv') as f:
        for row in csv.DictReader(f):
            census[int(row['k'])] = sorted(int(v) for v in row['x_coordinates'].split())
    curves = []
    for D in (7, 28, 63):
        c = compile_curve(D)
        a = lean_args(c)
        rec = next(x for x in graph['curves'] if x['D'] == D)
        ids = rec['classes']
        thuesL, ys = [], set(a['Ys'])
        for e in c['open']:
            m = next((m, cid) for cid in ids for m in gcls[cid]['members']
                     if (m['D'], m['k'], m['p'], m['q']) == (D, e['k'], e['p'], e['q']))
            mem, cid = m
            T = mem['T']
            thuesL.append(f"({_i(e['k'])}, {_i(e['p'])}, {_i(e['q'])}, {mat_lean(T)})")
            k3 = e['k'] ** 3
            for (u, v) in lists[cid]:
                aa, bb = T[0][0] * u + T[0][1] * v, T[1][0] * u + T[1][1] * v
                W = e['p'] * W1(D, aa, bb) + D * e['q'] * W2(D, aa, bb)
                if W % k3 == 0:
                    ys.add(W // k3)
        ys = sorted(ys)
        pts = []
        for y in ys:
            x = icbrt(y * y + D)
            if x ** 3 == y * y + D:
                pts.append((x, y))
        assert sorted({x for x, _ in pts}) == census.get(-D, []), f'D = {D}: disagrees with the Sage census'
        curves.append({'D': D, 'classes': ids, 'open_branches': len(c['open']), 'points': pts,
                       'candidate_ys': ys, 'agrees_with_sage': True})
        cubes = '[' + ', '.join('(' + ', '.join(_i(v) for v in t) + ')' for t in a['cubes']) + ']'
        mods = '[' + ', '.join('(' + ', '.join(_i(v) for v in t) + ')' for t in a['mods']) + ']'
        listed = '[' + ', '.join(
            f"({form_lean(gcls[i]['representative'])}, {gcls[i]['M']}, {pairs_lean(lists[i])})" for i in ids) + ']'
        hyps = ' '.join(f'(h{i} : bound_{i})' for i in ids)
        pat = ' | '.join(['rfl'] * len(ids))
        cases = ' '.join(f'| exact (class_{i} h{i} u v).mp' for i in ids)
        out.append(
            f"set_option maxHeartbeats 0 in\n"
            f"/-- **The integral points of `y^2 = x^3 - {D}`, under the bounds of classes {ids}**: "
            f"{len(pts)} point(s).  {len(a['cubes'])} field-cube and {len(a['mods'])} local branches; "
            f"{len(thuesL)} branches transported to the listed classes. -/\n"
            f"theorem minus{D} {hyps} (x y : ℤ) :\n    y ^ 2 = x ^ 3 - {D} ↔ (x, y) ∈ ({pairs_lean(pts)} : List (ℤ × ℤ)) :=\n"
            f"  DescentThueList.complete_of_lists {D} (by norm_num) {c['r']} {c['t']} (by norm_num) (by norm_num)"
            f" {c['K']} {c['Q']}\n    (by norm_num) (by norm_num)\n"
            f"    {cubes}\n    {mods}\n    [] []\n    [{', '.join(thuesL)}]\n    {listed}\n"
            f"    (by simp)\n"
            f"    (by intro c hc u v; simp only [List.mem_cons, List.mem_nil_iff, or_false] at hc\n"
            f"        rcases hc with {pat} <;> first {cases})\n"
            f"    {'[' + ', '.join(_i(y) for y in ys) + ']'}\n"
            f"    {pairs_lean(pts)}\n    (by decide +kernel) (by decide +kernel) x y\n")
    out.append('end PerfectPower.Generated.Field756\n')
    (ROOT / 'PerfectPower' / 'Generated' / 'Field756.lean').write_text('\n'.join(out))
    (ROOT / 'receipts' / 'field756_certificate.json').write_text(json.dumps(
        {'label': 'Lean theorems conditional on the named external bounds bound_i (Generated/Field756.lean); '
                  'box, small-b search and branch transport are kernel-checked',
         'units': [list(e1), list(e2)], 'inverses': [list(e1i), list(e2i)], 'classes': report, 'curves': curves},
        indent=1, default=list) + '\n')
    for r in report:
        print(f"class {r['class']:2d}: B={r['B']} V={r['V']} box {r['box_size']} hits {r['box_hits']} small {r['small_b_hits']}")
    for c in curves:
        print(f"D={c['D']}: classes {c['classes']}, {c['open_branches']} open branches, points {c['points']}, Ys {c['candidate_ys']}")


if __name__ == '__main__':
    main()
