"""Emit PerfectPower/Generated/MordellPoints.lean from data/mordell_census.csv.

Lean's role here is deliberately narrow: each chunk theorem checks, by kernel evaluation
(`decide`), that every listed triple (k, x, y) satisfies y^2 = x^3 + k, and that the chunk has the
stated length.  It does NOT check that the census lists are complete; completeness is Sage's claim
(see docs/TRUST_BOUNDARY.md).
"""
import csv
from math import isqrt
from pathlib import Path

CHUNK = 400
root = Path(__file__).resolve().parents[1]
pts = []
for r in csv.DictReader(open(root / 'data' / 'mordell_census.csv')):
    k = int(r['k'])
    for x in r['x_coordinates'].split():
        x = int(x)
        y = isqrt(x ** 3 + k)
        assert y * y == x ** 3 + k
        pts.append((k, x, y))
out = ['/-! Machine-generated by `python3 python/make_lean_census.py` from `data/mordell_census.csv`.',
       '',
       'Each theorem checks by kernel evaluation that every listed `(k, x, y)` satisfies',
       '`y^2 = x^3 + k`, and fixes the chunk length.  **Completeness of the census is not checked',
       'here**: it is certified externally by Sage (Mordell-Weil basis + elliptic-logarithm sieving).',
       f'Total points (one per x, y >= 0): {len(pts)}. -/', '',
       'namespace PerfectPower.Generated.Mordell', '']
names = []
for i in range(0, len(pts), CHUNK):
    part = pts[i:i + CHUNK]
    n = f'chunk{i // CHUNK}'
    names.append(n)
    body = ',\n  '.join(f'({k}, {x}, {y})' for k, x, y in part)
    out.append(f'/-- Census points {i}..{i + len(part) - 1} as `(k, x, y)`. -/')
    out.append(f'def {n} : List (Int × Int × Int) := [\n  {body}]')
    out.append(f'/-- Every point of `{n}` lies on its curve `y^2 = x^3 + k`; the chunk has {len(part)} points. -/')
    out.append(f'theorem {n}_valid : {n}.all (fun p => p.2.2 ^ 2 == p.2.1 ^ 3 + p.1) = true ∧ '
               f'{n}.length = {len(part)} := by decide')
    out.append('')
conj = ' ∧\n    '.join(f'{n}.all (fun p => p.2.2 ^ 2 == p.2.1 ^ 3 + p.1) = true' for n in names)
out.append(f'/-- All {len(pts)} census points lie on their curves (completeness is not claimed). -/')
out.append(f'theorem census_points_valid :\n    {conj} :=')
proofs = [f'{n}_valid.1' for n in names]
out.append('  ' + (proofs[0] if len(proofs) == 1 else '⟨' + ', '.join(proofs) + '⟩'))
out.append('')
out.append('end PerfectPower.Generated.Mordell')
(root / 'PerfectPower' / 'Generated' / 'MordellPoints.lean').write_text('\n'.join(out) + '\n')
print(len(pts), 'points in', len(names), 'chunks')
