"""Rewrite the machine-generated counts block in README.md from audit and receipt outputs.

Run after ./audit/check_axioms.sh (which writes audit/axioms_report.txt).  `make verify` fails
if the block changes, so the README can never quote a stale count.
"""
import json
import re
from collections import Counter
from pathlib import Path

root = Path(__file__).resolve().parents[1]
report = (root / 'audit' / 'axioms_report.txt').read_text().splitlines()
def _std(l):
    if 'does not depend on any axioms' in l:
        return True
    m = re.search(r'depends on axioms: \[(.*)\]$', l)
    return bool(m) and set(a.strip() for a in m.group(1).split(',')) <= {'propext', 'Classical.choice', 'Quot.sound'}


audited = [l for l in report if 'depend' in l]
standard = [l for l in audited if _std(l)]
generated = [l for l in audited if 'PerfectPower.Generated.' in l and 'Mordell' not in l
             and '.cert_' not in l]
atlas = json.loads((root / 'receipts' / 'atlas_benchmarks.json').read_text())
labels = Counter(r['certification'] for r in atlas['rows'])
lines = [
    f'- Lean declarations audited: **{len(audited)}**; using only `propext`, `Classical.choice`, '
    f'`Quot.sound` (or a subset): **{len(standard)}**.',
    f'- Machine-generated Lean hit-set certificates: **{len(generated)}**.',
    '- Atlas families by certification label: '
    + ', '.join(f'`{k}` {v}' for k, v in sorted(labels.items())) + '.',
]
cub = root / 'receipts' / 'cubic_crossval.json'
if cub.exists():
    s = json.loads(cub.read_text())['summary']
    lines.append(f'- Cubic cross-validation ($m^2=n^3+an+b$, $|a|,|b|\\le{s["bound"]}$): '
                 f'{s["certified_rows"]}/{s["curves"]} certified by Sage, '
                 f'{len(s["disagreements"])} disagreements with the scan to $10^5$.')
adv = root / 'receipts' / 'adversarial_runge.json'
if adv.exists():
    s = json.loads(adv.read_text())['summary']
    lines.append(f'- Adversarial Runge test: {s["trials"]} planted-hit trials, {s["failures"]} failures, '
                 f'planted hits up to {s["max_planted_found"]:,}.')
mc = root / 'receipts' / 'mordell_census_summary.json'
if mc.exists():
    s = json.loads(mc.read_text())
    lab = s['labels']
    lines.append(f'- Mordell census $y^2=x^3+k$, $0<|k|\\le{s["K"]}$: {s["curves"]} curves, '
                 f'{s.get("total_points", "?")} integral points; labels '
                 + ', '.join(f'`{a}` {b}' for a, b in sorted(lab.items()))
                 + f'; {len(s["scan_disagreements"])} scan disagreements ($|x|\\le10^5$); best Hall ratio '
                 f'{s["top_hall_ratios"][0]["ratio"]} ($k={s["top_hall_ratios"][0]["k"]}$, '
                 f'$x={s["top_hall_ratios"][0]["x"]}$).')
g1 = root / 'receipts' / 'genus1_crossval.json'
if g1.exists():
    s = json.loads(g1.read_text())
    far = max(s['hits_beyond_scan'], key=lambda r: r['max_hit']) if s['hits_beyond_scan'] else None
    lines.append(f'- Genus-one cross-validation (non-monic/shifted $m^2=$ cubic, $m^3=$ quadratic): '
                 f'{s["trials"]} families; labels '
                 + ', '.join(f'`{a}` {b}' for a, b in sorted(s['labels'].items()))
                 + f'; {len(s["scan_disagreements"])} disagreements with the exact scan to $10^6$; '
                 f'{len(s["hits_beyond_scan"])} certified hits beyond it'
                 + (f' (largest $n={far["max_hit"]:,}$)' if far else '') + '.')
tg = root / 'receipts' / 'theorem_g_check.json'
if tg.exists():
    s = json.loads(tg.read_text())
    lines.append(f'- Theorem G check ($d\\le{s["d_max"]}$, $\\deg F\\le{s["degree_max"]}$): {s["cases"]} cases; '
                 f'Singular genus in all {s["cases"]}, Sage places at infinity in {s["n_inf_computed"]}; '
                 f'{len(s["disagreements"])} disagreements with ' + r"$\chi=d'(1-S)$.")
pc = root / 'receipts' / 'pillai_census_summary.json'
if pc.exists():
    s = json.loads(pc.read_text())
    lines.append(f'- Pillai gap census: {s["pairs"]} pairs of perfect powers $\\le {s["B"].replace("^", "^{")}}}$ at distance '
                 f'$\\le {s["K"]}$ (exact within the bound).')
block = '<!-- counts:begin (generated by python/make_counts.py; do not edit) -->\n' + \
        '\n'.join(lines) + '\n<!-- counts:end -->'
readme = root / 'README.md'
text = readme.read_text()
text = re.sub(r'<!-- counts:begin.*?<!-- counts:end -->', lambda m: block, text, flags=re.S)
readme.write_text(text)
print('\n'.join(lines))
