"""Exact integral cubic-order embeddings among the orders of receipts/order_cost.json, and their
Lean certificates (PerfectPower/Generated/OrderMaps.lean, `OrderEmbedding.OrderMap` / `OrderIso`).

The census (the complete finite search for generator images below) is from the order-transport
review of fb30592; the Lean emission and the receipt wiring were added here.

Original notes: exact integral cubic-order embeddings from the existing cost receipt.

Input: orders R(P,Q)=Z[t]/(t^3-P*t-Q), positive discriminant.
Output: checked images of the domain generator in each candidate codomain.
A determinant ±1 proves an order isomorphism; other nonzero determinants
prove embeddings of the reported finite additive index, not surjectivity.
No package dependencies, unit search, floating point, or maximal orders.
"""
import argparse,json,math,pathlib
ONE=(1,0,0);BASIS=(ONE,(0,1,0),(0,0,1))

def mul(P,Q,u,v):
 a,b,c=u;d,e,f=v
 return (a*d+Q*(b*f+c*e),a*e+b*d+P*(b*f+c*e)+Q*c*f,a*f+b*e+c*d+P*c*f)

def norm(P,Q,g):
 a,b,c=g
 return a*((a+P*c)**2-(P*b+Q*c)*b)-Q*c*(b*(a+P*c)-(P*b+Q*c)*c)+Q*b*(b*b-(a+P*c)*c)

def det(M):
 a,b,c=M[0];d,e,f=M[1];g,h,i=M[2]
 return a*(e*i-f*h)-b*(d*i-f*g)+c*(d*h-e*g)

def apply(M,u):return tuple(sum(M[i][j]*u[j] for j in range(3)) for i in range(3))

def certify(domain,codomain,image):
 p,q=domain;P,Q=codomain;g=tuple(image);g2=mul(P,Q,g,g);g3=mul(P,Q,g2,g)
 if g3!=(p*g[0]+q,p*g[1],p*g[2]):return None
 M=[[ONE[i],g[i],g2[i]] for i in range(3)];d=det(M)
 if not d:return None
 assert d*d*(4*P**3-27*Q**2)==4*p**3-27*q*q
 for x in BASIS:
  for y in BASIS:assert apply(M,mul(p,q,x,y))==mul(P,Q,apply(M,x),apply(M,y))
 # Independent exact points supplement the universal bilinear identity check.
 for a in range(-3,4):
  for b in range(-3,4):
   for c in range(-3,4):assert norm(p,q,(a,b,c))==norm(P,Q,apply(M,(a,b,c)))
 return dict(domain=list(domain),codomain=list(codomain),generator_image=list(g),matrix=M,
             determinant=d,index=abs(d),kind='ISOMORPHISM' if abs(d)==1 else 'EMBEDDING',
             evidence='EXACT_INTEGER_ARITHMETIC; Lean transport theorem not supplied')

def embeddings(domain,codomain):
 p,q=domain;P,Q=codomain;disc=4*P**3-27*Q*Q
 # trace(g)=0 fixes a=-2Pc/3. The trace-square equation is
 # (6Pb+9Qc)^2 + 3*disc*c^2 = 36Pp, giving a finite *complete* search.
 cmax=math.isqrt((12*P*p)//disc);out=[]
 for c in range(-cmax,cmax+1):
  if (2*P*c)%3:continue
  a=-(2*P*c)//3
  bmax=(math.isqrt(36*P*p)+9*abs(Q*c))//(6*P)
  for b in range(-bmax,bmax+1):
   if (6*P*b+9*Q*c)**2+3*disc*c*c!=36*P*p:continue
   if norm(P,Q,(a,b,c))!=q:continue
   cert=certify(domain,codomain,(a,b,c))
   if cert:out.append(cert)
 return out


LEAN_HEAD = """import PerfectPower.OrderEmbedding

/-!
# Maps between the cubic orders of the Thue workload (generated by `python/order_transport.py`)

Each `map_i : OrderMap p q P Q` sends the generator of `ℤ[t]/(t³ − pt − q)` to `g` in
`ℤ[t]/(t³ − Pt − Q)`; `map_mul` and `map_nrm` are proved by `ring`, `det_i` gives the additive
index `|det|`, and `inj_i` the injectivity (`emb_injective`, from `det_i ≠ 0`).  Index 1 with the reverse map present gives `iso_*` (`OrderIso`), along which unit
generation transfers (`OrderEmbedding.unitGen_transport`).  An index `> 1` map is an embedding: it
moves source equations forward (`OrderEmbedding.nrm_enc_of_map`), not unit generation back.
-/

namespace PerfectPower.Generated.OrderMaps

open PerfectPower UnitBox UnitPremises OrderEmbedding
"""


def _z3(g):
    return '(' + ', '.join(f'({x})' if x < 0 else str(x) for x in g) + ')'


def lean_maps(edges):
    out = [LEAN_HEAD]
    for i, e in enumerate(edges):
        (p, q), (P, Q), g, d = e['domain'], e['codomain'], e['generator_image'], e['determinant']
        kind = 'an isomorphism' if abs(d) == 1 else f'an embedding of index {abs(d)}'
        out.append(
            f'/-- `ℤ[t]/(t³ − {p}t − {q}) → ℤ[t]/(t³ − {P}t − {Q})`, `t ↦ {_z3(g)}`: {kind}. -/\n'
            f'def map_{i} : OrderMap {p} {q} {P} {Q} where\n'
            f'  g := {_z3(g)}\n'
            f'  map_mul := by\n    rintro ⟨a, b, c⟩ ⟨d, e, f⟩\n    simp only [emb, mul, Prod.mk.injEq]\n'
            f'    refine ⟨by ring, by ring, by ring⟩\n'
            f'  map_nrm := by\n    rintro ⟨a, b, c⟩\n    simp only [emb, mul, nrm]\n    ring\n\n'
            f'theorem det_{i} : OrderEmbedding.det {P} {Q} {_z3(g)} = {d} := by decide\n\n'
            f'theorem inj_{i} : Function.Injective (OrderEmbedding.emb {P} {Q} {_z3(g)}) :=\n'
            f'  OrderEmbedding.emb_injective (by rw [det_{i}]; decide)\n')
    isos = []
    for i, e in enumerate(edges):
        if abs(e['determinant']) != 1:
            continue
        for j, f in enumerate(edges):
            if j > i and f['domain'] == e['codomain'] and f['codomain'] == e['domain'] and abs(f['determinant']) == 1:
                (p, q), (P, Q) = e['domain'], e['codomain']
                isos.append((i, j))
                out.append(
                    f'/-- `ℤ[t]/(t³ − {p}t − {q}) ≅ ℤ[t]/(t³ − {P}t − {Q})` (`map_{i}`, inverse `map_{j}`). -/\n'
                    f'def iso_{i}_{j} : OrderIso {p} {q} {P} {Q} :=\n'
                    f'  {{ map_{i} with\n    inv := map_{j}\n'
                    f'    left := by\n      rintro ⟨a, b, c⟩\n      simp only [emb, mul, map_{i}, map_{j}, Prod.mk.injEq]\n'
                    f'      refine ⟨by ring, by ring, by ring⟩\n'
                    f'    right := by\n      rintro ⟨a, b, c⟩\n      simp only [emb, mul, map_{i}, map_{j}, Prod.mk.injEq]\n'
                    f'      refine ⟨by ring, by ring, by ring⟩ }}\n')
    out.append('end PerfectPower.Generated.OrderMaps\n')
    return '\n'.join(out), isos


def emb(P, Q, g, x):
    """`OrderEmbedding.emb`: `(a, b, c) ↦ a + b g + c g²`."""
    g2 = mul(P, Q, g, g)
    return (x[0] + x[1] * g[0] + x[2] * g2[0], x[1] * g[1] + x[2] * g2[1], x[1] * g[2] + x[2] * g2[2])


# orders with unit generation proved in Lean outside the census receipt
PROVED_ORDERS = [(6, 2), (6, 3), (9, 6), (15, 12), (18, 12)]


def census(cost):
    """All checked maps between the orders of a cost receipt (as in `main`)."""
    orders = {tuple(o['key']): o for o in cost['orders']}
    edges = []
    for s in orders:
        for t in orders:
            if s == t:
                continue
            ds = orders[s]['disc']; dt = orders[t]['disc']
            if ds < dt or ds % dt:
                continue
            ratio = ds // dt
            if math.isqrt(ratio) ** 2 != ratio:
                continue
            edges.extend(embeddings(s, t))
    return edges

def main():
 root=pathlib.Path(__file__).resolve().parents[1]
 ap=argparse.ArgumentParser();ap.add_argument('cost_receipt',nargs='?',default=str(root/'receipts'/'order_cost_fb30592.json'));ap.add_argument('--output',default=str(root/'receipts'/'order_transports.json'));args=ap.parse_args()
 cost=json.loads(pathlib.Path(args.cost_receipt).read_text());orders={tuple(o['key']):o for o in cost['orders']};edges=[]
 for s in orders:
  for t in orders:
   if s==t:continue
   ds=orders[s]['disc'];dt=orders[t]['disc']
   if ds<dt or ds%dt:continue
   ratio=ds//dt
   if math.isqrt(ratio)**2!=ratio:continue
   edges.extend(embeddings(s,t))
 # orders whose unit generation is already a Lean theorem, as further targets (appended, so the
 # indices of the census above stay fixed): a map into one of them needs no new unit proof
 for s in orders:
  for t in PROVED_ORDERS:
   if t in orders:continue
   ds=orders[s]['disc'];dt=4*t[0]**3-27*t[1]**2
   if ds<dt or ds%dt or math.isqrt(ds//dt)**2!=ds//dt:continue
   edges.extend(embeddings(s,t))
 choices=[]
 for s,o in orders.items():
  targets=[(o.get('cost'),s,None)] if o.get('cost') is not None else []
  for e in edges:
   if tuple(e['domain'])==s:
    t=tuple(e['codomain']);c=orders[t].get('cost') if t in orders else 0
    if c is not None:targets.append((c,t,e))
  targets.sort(key=lambda x:(x[0],x[1]))
  if targets:
   c,t,e=targets[0];choices.append(dict(domain=list(s),original_cost=o.get('cost'),chosen_order=list(t),unitgen_proxy_cost=c,transport=e))
 curves=[]
 for curve in cost['curves']:
  cc=[next(x for x in choices if x['domain']==o) for o in curve['orders'] if any(x['domain']==o for x in choices)]
  unique={tuple(c['chosen_order']):c['unitgen_proxy_cost'] for c in cc}
  curves.append(dict(D=curve['D'],old_unitgen=curve['C_unitgen'],new_unitgen_proxy=sum(unique.values()),
                    all_order_costs_available=len(cc)==len(curve['orders']),
                    source_repricing_required=True,chosen_orders=[list(x) for x in sorted(unique)]))
 text,isos=lean_maps(edges)
 (root/'PerfectPower'/'Generated'/'OrderMaps.lean').write_text(text)
 for i,e in enumerate(edges):e['lean']=f'Generated.OrderMaps.map_{i}';e['evidence']='EXACT_INTEGER_ARITHMETIC; Lean: map_mul, map_nrm by ring, det by decide'
 out={'census_base_commit':'fb30592a288e0ee1e928802a94eeef2a921f3b46','orders':len(orders),'embeddings':edges,'lean_isomorphisms':[f'iso_{i}_{j}' for i,j in isos],
      'choices':choices,'curves':curves,'warning':'The maps are Lean-checked (Generated/OrderMaps.lean); the unit-generation costs are estimates, and source certificates in a target order must be regenerated.'}
 pathlib.Path(args.output).write_text(json.dumps(out,indent=2)+'\n')
 print('orders',len(orders),'checked directed maps',len(edges),'orders with costs',len(choices),'chosen targets',len({tuple(c['chosen_order']) for c in choices}))
 for c in choices:
  if c['domain']!=c['chosen_order']:print(c['domain'],'->',c['chosen_order'],'index',c['transport']['index'],'cost',c['original_cost'],'->',c['unitgen_proxy_cost'])
 for c in curves:
  if c['D'] in [39,60,47,95]:print('curve',c)

if __name__=='__main__':main()
