"""Nonmonic Thue sources with no solution, through norm orbits (`RankOneNorm.lean`).

For a class `F = (a, B, C, d)` with `|a| > 1` and no known point, `H(au, v) = a² F(u, v)` with
`H = X³ + BX²Y + aCXY² + a²dY³` monic (`LatticeTransport.monic_identity`).  With the shift of
`positive_k_next.monic_order`, `F(u, v) = 1` gives `w = (au + hv, −v, 0)` in `ℤ[z]` with
`N(w) = a²` and `w₂ = 0`.  This script finds, exactly:
* the fundamental unit `η` of `ℤ[z]` (as in `rank_one_sources`), and a norm-`a²` certificate
  (`RankOneNorm.condNB`: `|re| ≤ R₀`, `κ²J² ≥ a²`, the bound `C`);
* the list `L` of slab elements of norm `±a²` that are not certified small (`slabNB`);
* a prime `q` with periods `M`, `M'` such that `q ∤ (γ η^r)₂` for all `r < M`, and likewise for
  `ε`, for every `γ ∈ L` (`orbitB`).
Then `F(u, v) = 1` has no solution (`RankOneNorm.no_corner_zero`).  The kernel re-checks all of it.

Run: python3 python/rank_one_norm.py
"""
from __future__ import annotations

import json
import math
import sys
from fractions import Fraction as Fr
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'python'))

import positive_k_next as PK  # noqa: E402
import rank_one_sources as R  # noqa: E402

# (k, class F = (a, B, C, d), η of the monic order of F's monic reduction)
TARGETS = [
    (11, (-2, 0, -3, -3), (9337, 1682, 1144)),
]


def certN(P, Q, eta, N, den=10 ** 9):
    t = R.real_root(P, Q)
    lo, hi = Fr(math.floor(t * den), den), Fr(math.ceil(t * den), den)
    T = max(abs(lo), abs(hi))
    t2lo = lo * lo if lo >= 0 else hi * hi if hi <= 0 else Fr(0)
    K, Dn = 3 * t2lo / 4 - P, 3 * t2lo - P
    J = Fr(math.ceil(math.sqrt(N / float(K)) * 10 ** 6 + 1), 10 ** 6)
    assert K * J * J >= N
    R0 = Fr(math.isqrt(N - 1) + 1 if N > 1 else 1)
    assert R0 * R0 >= N
    E = R.sigQ(lo, eta) + R.rad(eta, lo, hi)
    assert R.sigQ(lo, eta) - R.rad(eta, lo, hi) > 1
    C = math.floor((E + R0 + Fr(3, 2) * T * J) / Dn)
    assert E + R0 + Fr(3, 2) * T * J < (C + 1) * Dn
    return {'lo': lo, 'hi': hi, 'J': J, 'C': C, 'R0': R0, '_T': T, '_t2lo': t2lo}


def slabN(P, c):
    """Mirror of the enumeration of `RankOneNorm.slabNB`."""
    lo, hi, J, T, t2lo, R0 = c['lo'], c['hi'], c['J'], c['_T'], c['_t2lo'], c['R0']
    for cc in range(-c['C'], c['C'] + 1):
        for b in R.ints(R.lmin(Fr(cc), lo, hi) - J, R.lmax(Fr(cc), lo, hi) + J):
            for a in R.ints(-R0 + R.lmin(Fr(b), lo, hi) / 2 - cc * P + R.lmin(Fr(cc), t2lo, T * T) / 2,
                            R0 + R.lmax(Fr(b), lo, hi) / 2 - cc * P + R.lmax(Fr(cc), t2lo, T * T) / 2):
                yield (a, b, cc)


def period(P, Q, g, q, Mmax=20000):
    x = g
    for M in range(1, Mmax + 1):
        A = R.Mx(P, Q, x)
        if all((A[i][j] - (i == j)) % q == 0 for i in range(3) for j in range(3)):
            return M
        x = R.mul(P, Q, x, g)
    return None


def orbit_ok(P, Q, gam, g, q, M):
    x = gam
    for _ in range(M):
        if x[2] % q == 0:
            return False
        x = R.mul(P, Q, x, g)
    return True


def solve(k, F, eta):
    a, B, C, d = F
    mo = PK.monic_order([-1, -B, -a * C, -a * a * d])
    P, Q, h = -mo['p'], -mo['q'], mo['u_shift']
    N = a * a
    eta, _ = R.fundamental(P, Q, eta)
    eps = R.inverse(P, Q, eta)
    c = certN(P, Q, eta, N)
    L = sorted({g for g in slabN(P, c) if abs(R.nrm(P, Q, g)) == N and R.pHi(g, c['lo'], c['hi']) >= 1})
    out = {'k': k, 'form': list(F), 'a': a, 'N': N, 'P': P, 'Q': Q, 'h': h, 'eta': list(eta), 'eps': list(eps),
           'cert': {x: str(v) for x, v in c.items() if not x.startswith('_')}, 'reps': [list(g) for g in L],
           'slab_elements': sum(1 for _ in slabN(P, c)), '_c': c}
    for q in R.PRIMES:
        M, M1 = period(P, Q, eta, q), period(P, Q, eps, q)
        if M and M1 and all(orbit_ok(P, Q, g, eta, q, M) and orbit_ok(P, Q, g, eps, q, M1) for g in L):
            out.update({'q': q, 'M': M, 'M_eps': M1, 'status': 'empty'})
            return out
    out['status'] = 'no_congruence'
    return out


def lean(r):
    P, Q, c, h, a = r['P'], r['Q'], r['_c'], r['h'], r['a']
    PQ = f'{R._i(P)} {R._i(Q)}'
    L = '[' + ', '.join(R._z3(g) for g in r['reps']) + ']'
    A, B, C, D = r['form']
    k = r['k']
    return f"""import PerfectPower.RankOneNorm

/-!
# `y² = x³ + {k}`: the nonmonic class `{tuple(r['form'])}` has no solution (generated by `python/rank_one_norm.py`)

`F(u, v) = 1` gives `w = ({a}u + {h}v, −v, 0)` of norm `{r['N']}` in `ℤ[z]`, `z³ = ({P}) z + ({Q})`
(monic reduction). Every element of norm `±{r['N']}` is `γ ηⁿ` with `γ` in the slab list, and no
`γ ηⁿ` has `z²` coordinate `0` modulo {r['q']} (`RankOneNorm.no_corner_zero`).
-/

set_option Elab.async false

namespace PerfectPower.Generated.RankOneNorm.K{k}

open PerfectPower UnitBox UnitPremises RankOne RankOneNorm

/-- The fundamental unit of `ℤ[z]`. -/
def η : Z3 := {R._z3(r['eta'])}

/-- `η⁻¹`. -/
def ε : Z3 := {R._z3(r['eps'])}

/-- The norm-`{r['N']}` certificate. -/
def c : Cert := ⟨{R._q(c['lo'])}, {R._q(c['hi'])}, {R._q(c['J'])}, {c['C']}⟩

/-- The representatives of norm `±{r['N']}` that the slab cannot certify small. -/
def L : List Z3 := {L}

theorem h1 : mul {PQ} η ε = (1, 0, 0) := by decide
theorem h2 : mul {PQ} ε η = (1, 0, 0) := by decide
theorem n1 : nrm {PQ} η = 1 := by decide
theorem n2 : nrm {PQ} ε = 1 := by decide
theorem cond : condNB {PQ} η c {r['N']} {R._q(c['R0'])} = true := by decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem slab : slabNB {PQ} c {r['N']} {R._q(c['R0'])} L = true := by decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem orbits : L.all (fun γ => orbitB {PQ} γ η {r['q']} {r['M']} && orbitB {PQ} γ ε {r['q']} {r['M_eps']}) = true := by
  decide +kernel

/-- **`{A}u³ + ({B})u²v + ({C})uv² + ({D})v³ = 1` has no integer solution.** -/
theorem empty (u v : ℤ) : {R._i(A)} * u ^ 3 + {R._i(B)} * u ^ 2 * v + {R._i(C)} * u * v ^ 2 + {R._i(D)} * v ^ 3 ≠ 1 := by
  intro hF
  have hw : nrm {PQ} ({R._i(a)} * u + {h} * v, -v, 0) = ({r['N']} : ℕ) := by
    simp only [nrm]; push_cast; linear_combination ({a} : ℤ) ^ 2 * hF
  exact no_corner_zero h1 h2 n1 n2 cond slab (by norm_num) orbits _ (Or.inl hw) rfl

end PerfectPower.Generated.RankOneNorm.K{k}
"""


def main():
    res = []
    d = ROOT / 'PerfectPower' / 'Generated' / 'RankOneNorm'
    d.mkdir(exist_ok=True)
    for k, F, eta in TARGETS:
        r = solve(k, F, eta)
        if r['status'] == 'empty':
            (d / f'K{k}.lean').write_text(lean(r))
        r.pop('_c')
        res.append(r)
    (ROOT / 'receipts' / 'rank_one_norm.json').write_text(json.dumps(
        {'scope': 'nonmonic positive-k sources proved empty through norm orbits (RankOneNorm); '
                  're-checked by the Lean kernel', 'sources': res}, indent=1, default=str) + '\n')
    return res


if __name__ == '__main__':
    for r in main():
        print(r['k'], r['form'], r['status'], 'reps', r['reps'], 'q', r.get('q'), r.get('M'), r.get('M_eps'),
              'slab', r['slab_elements'])
