import PerfectPower.Continuation.DenominatorReduction

#print axioms PerfectPower.RationalYun.radical_integer_reduction
#print axioms PerfectPower.RationalYun.Decomposition.integer_radical_reduction
#print axioms PerfectPower.RationalYun.Decomposition.integer_pell_reduction
#print axioms PerfectPower.RationalYun.Decomposition.quotientPart
#print axioms PerfectPower.RationalYun.Decomposition.remainderPart
#print axioms PerfectPower.RationalYun.Decomposition.powerSplit
#print axioms PerfectPower.RationalYun.Decomposition.weighted_degree
#print axioms PerfectPower.RationalYun.Decomposition.single_remainder
#print axioms PerfectPower.RationalYun.Decomposition.uniform_remainder
#print axioms PerfectPower.RationalYun.Decomposition.lead_eq_leadingCoeff
#print axioms PerfectPower.RationalYun.Decomposition.radical_shape
#print axioms PerfectPower.RationalYun.Decomposition.pellPart
#print axioms PerfectPower.RationalYun.Decomposition.pell_shape
#print axioms PerfectPower.RationalYun.unique_summand_of_sum_one
#print axioms PerfectPower.RationalYun.Decomposition.badDegree
#print axioms PerfectPower.RationalYun.Decomposition.radical_shape_of_badDegree_one
#print axioms PerfectPower.RationalYun.RatPower
#print axioms PerfectPower.RationalYun.ratPower_mul_pow_iff
#print axioms PerfectPower.RationalYun.integer_factor_reduction
#print axioms PerfectPower.RationalYun.Decomposition.hit_reduction
#print axioms PerfectPower.RationalYun.rat_even_power_reduction
#print axioms PerfectPower.RationalYun.pell_factor_reduction
#print axioms PerfectPower.RationalYun.opposite_squares_iff_zero
#print axioms PerfectPower.RationalYun.bag
#print axioms PerfectPower.RationalYun.layerSet
#print axioms PerfectPower.RationalYun.layer
#print axioms PerfectPower.RationalYun.normalized_irreducibles_coprime
#print axioms PerfectPower.RationalYun.layer_mem
#print axioms PerfectPower.RationalYun.layer_monic
#print axioms PerfectPower.RationalYun.squarefree_product
#print axioms PerfectPower.RationalYun.layer_squarefree
#print axioms PerfectPower.RationalYun.layers_coprime
#print axioms PerfectPower.RationalYun.grouped_product
#print axioms PerfectPower.RationalYun.ofNonzero
#print axioms PerfectPower.RationalYun.exists_decomposition
#print axioms PerfectPower.RationalYun.exists_integer_decomposition
#print axioms PerfectPower.RationalYun.Decomposition.ne_zero
#print axioms PerfectPower.RationalYun.decomposition_iff_nonzero
#print axioms PerfectPower.RationalYun.not_isCoprime_integer_X_X_add_two
#print axioms PerfectPower.RationalYun.isCoprime_rational_X_X_add_two
